ZNC: CConfig Class Reference
CConfig Class Reference
#include <Config.h>
Public Types
typedef std::map< CString, VCString > EntryMap
typedef std::map< CString, CConfigEntry > SubConfig
typedef std::map< CString, SubConfig > SubConfigMap
typedef EntryMap::const_iterator EntryMapIterator
typedef SubConfigMap::const_iterator SubConfigMapIterator
Public Member Functions
CConfig ()
EntryMapIterator BeginEntries () const
EntryMapIterator EndEntries () const
SubConfigMapIterator BeginSubConfigs () const
SubConfigMapIterator EndSubConfigs () const
void AddKeyValuePair (const CString &sName, const CString &sValue)
bool AddSubConfig (const CString &sTag, const CString &sName, CConfig Config)
bool FindStringVector (const CString &sName, VCString &vsList, bool bErase=true)
bool FindStringEntry (const CString &sName, CString &sRes, const CString &sDefault="")
bool FindBoolEntry (const CString &sName, bool &bRes, bool bDefault=false)
bool FindUIntEntry (const CString &sName, unsigned int &uRes, unsigned int uDefault=0)
bool FindUShortEntry (const CString &sName, unsigned short &uRes, unsigned short uDefault=0)
bool FindDoubleEntry (const CString &sName, double &fRes, double fDefault=0)
bool FindSubConfig (const CString &sName, SubConfig &Config, bool bErase=true)
bool empty () const
bool Parse (CFile &file, CString &sErrorMsg)
void Write (CFile &file, unsigned int iIndentation=0)
Member Typedef Documentation
EntryMap
typedef std::map<CString, VCString> CConfig::EntryMap
EntryMapIterator
typedef EntryMap::const_iterator CConfig::EntryMapIterator
SubConfig
typedef std::map<CString, CConfigEntry> CConfig::SubConfig
SubConfigMap
typedef std::map<CString, SubConfig> CConfig::SubConfigMap
SubConfigMapIterator
typedef SubConfigMap::const_iterator CConfig::SubConfigMapIterator
Constructor & Destructor Documentation
CConfig()
CConfig::CConfig () inline
Member Function Documentation
AddKeyValuePair()
void CConfig::AddKeyValuePair (const CString & sName, const CString & sValue) inline
AddSubConfig()
bool CConfig::AddSubConfig (const CString & sTag, const CString & sName, CConfig Config) inline
BeginEntries()
EntryMapIterator CConfig::BeginEntries () const inline
BeginSubConfigs()
SubConfigMapIterator CConfig::BeginSubConfigs () const inline
empty()
bool CConfig::empty () const inline
EndEntries()
EntryMapIterator CConfig::EndEntries () const inline
EndSubConfigs()
SubConfigMapIterator CConfig::EndSubConfigs () const inline
FindBoolEntry()
bool CConfig::FindBoolEntry (const CString & sName, bool & bRes, bool bDefault = false) inline
References CString::ToBool().
FindDoubleEntry()
bool CConfig::FindDoubleEntry (const CString & sName, double & fRes, double fDefault = 0) inline
References CString::ToDouble().
FindStringEntry()
bool CConfig::FindStringEntry (const CString & sName, CString & sRes, const CString & sDefault = "") inline
FindStringVector()
bool CConfig::FindStringVector (const CString & sName, VCString & vsList, bool bErase = true) inline
FindSubConfig()
bool CConfig::FindSubConfig (const CString & sName, SubConfig & Config, bool bErase = true) inline
FindUIntEntry()
bool CConfig::FindUIntEntry (const CString & sName, unsigned int & uRes, unsigned int uDefault = 0) inline
References CString::ToUInt().
FindUShortEntry()
bool CConfig::FindUShortEntry (const CString & sName, unsigned short & uRes, unsigned short uDefault = 0) inline
References CString::ToUShort().
Parse()
bool CConfig::Parse (CFile & file, CString & sErrorMsg)
Write()
void CConfig::Write (CFile & file, unsigned int iIndentation = 0)
The documentation for this class was generated from the following file:
Config.h