ZNC: CBufLine Class Reference
CBufLine Class Reference
#include <Buffer.h>
Public Member Functions
CBufLine ()
CBufLine (const CMessage &Format, const CString &sText="")
CBufLine (const CString &sFormat, const CString &sText="", const timeval *ts=nullptr, const MCString &mssTags=MCString::EmptyMap)
~CBufLine ()
CMessage ToMessage (const CClient &Client, const MCString &mssParams) const
CString GetLine (const CClient &Client, const MCString &mssParams) const
void UpdateTime ()
bool Equals (const CMessage &Format) const
void SetFormat (const CString &sFormat)
void SetText (const CString &sText)
void SetTime (const timeval &ts)
void SetTags (const MCString &mssTags)
const CString & GetCommand () const
CString GetFormat () const
const CString & GetText () const
timeval GetTime () const
const MCString & GetTags () const
Protected Attributes
CMessage m_Message
CString m_sText
Constructor & Destructor Documentation
CBufLine() [1/3]
CBufLine::CBufLine () inline
CBufLine() [2/3]
CBufLine::CBufLine (const CMessage & Format, const CString & sText = "")
CBufLine() [3/3]
CBufLine::CBufLine (const CString & sFormat, const CString & sText = "", const timeval * ts = nullptr, const MCString & mssTags = MCString::EmptyMap)
Deprecated:
~CBufLine()
CBufLine::~CBufLine ()
Member Function Documentation
Equals()
bool CBufLine::Equals (const CMessage & Format) const inline
References CMessage::Equals(), and m_Message.
GetCommand()
const CString & CBufLine::GetCommand () const inline
References CMessage::GetCommand(), and m_Message.
GetFormat()
CString CBufLine::GetFormat () const inline
References CMessage::ExcludeTags, m_Message, and CMessage::ToString().
GetLine()
CString CBufLine::GetLine (const CClient & Client, const MCString & mssParams) const
Deprecated:
Use ToMessage() instead
GetTags()
const MCString & CBufLine::GetTags () const inline
References CMessage::GetTags(), and m_Message.
GetText()
const CString & CBufLine::GetText () const inline
References m_sText.
GetTime()
timeval CBufLine::GetTime () const inline
References CMessage::GetTime(), and m_Message.
SetFormat()
void CBufLine::SetFormat (const CString & sFormat) inline
References m_Message, and CMessage::Parse().
SetTags()
void CBufLine::SetTags (const MCString & mssTags) inline
References m_Message, and CMessage::SetTags().
SetText()
void CBufLine::SetText (const CString & sText) inline
References m_sText.
SetTime()
void CBufLine::SetTime (const timeval & ts) inline
References m_Message, and CMessage::SetTime().
ToMessage()
CMessage CBufLine::ToMessage (const CClient & Client, const MCString & mssParams) const
UpdateTime()
void CBufLine::UpdateTime ()
Deprecated:
Member Data Documentation
m_Message
CMessage CBufLine::m_Message protected
Referenced by Equals(), GetCommand(), GetFormat(), GetTags(), GetTime(), SetFormat(), SetTags(), and SetTime().
m_sText
CString CBufLine::m_sText protected
Referenced by GetText(), and SetText().
The documentation for this class was generated from the following file:
Buffer.h