ZNC: CTemplate Class Reference
CTemplate Class Reference
#include <Template.h>
Public Types
enum status_t {
MCS_SUCCESS = 0, MCS_EOPEN = 1, MCS_EWRITE = 2, MCS_EWRITEFIL = 3,
MCS_EREADFIL = 4
}
Status codes that can be returned by WriteToDisk() and ReadFromDisk().
Public Member Functions
CTemplate ()
CTemplate (const CString &sFileName)
CTemplate (const CSmartPtr< CTemplateOptions > &Options, CTemplate *pParent=NULL)
virtual ~CTemplate ()
void AddTagHandler (CSmartPtr< CTemplateTagHandler > spTagHandler)
Class for implementing custom tags in subclasses.
std::vector< CSmartPtr
< CTemplateTagHandler > > & GetTagHandlers ()
CString ResolveLiteral (const CString &sString)
void Init ()
CTemplate * GetParent (bool bRoot)
CString ExpandFile (const CString &sFilename, bool bFromInc=false)
bool SetFile (const CString &sFileName)
void SetPath (const CString &sPath)
CString MakePath (const CString &sPath) const
void PrependPath (const CString &sPath, bool bIncludesOnly=false)
void AppendPath (const CString &sPath, bool bIncludesOnly=false)
void RemovePath (const CString &sPath)
void ClearPaths ()
bool PrintString (CString &sRet)
bool Print (std::ostream &oOut)
bool Print (const CString &sFileName, std::ostream &oOut)
bool ValidIf (const CString &sArgs)
bool ValidExpr (const CString &sExpr)
bool IsTrue (const CString &sName)
bool HasLoop (const CString &sName)
CString GetValue (const CString &sName, bool bFromIf=false)
CTemplate & AddRow (const CString &sName)
CTemplate * GetRow (const CString &sName, unsigned int uIndex)
std::vector< CTemplate * > * GetLoop (const CString &sName)
void DelCurLoopContext ()
CTemplateLoopContext * GetCurLoopContext ()
CTemplate * GetCurTemplate ()
const CString & GetFileName () const
enum status_t WriteToDisk (const CString &sPath, mode_t iMode=0644) const
Write this map to a file.
enum status_t ReadFromDisk (const CString &sPath)
Read a map from a file.
virtual bool WriteFilter (CString &sKey, CString &sValue) const
Filter used while writing this map.
virtual bool ReadFilter (CString &sKey, CString &sValue) const
Filter used while reading this map.
virtual CString & Encode (CString &sValue) const
Encode a value so that it can safely be parsed by ReadFromDisk().
virtual CString & Decode (CString &sValue) const
Undo the effects of Encode().
Public Attributes
K keys
STL member.
T elements
STL member.
Static Public Attributes
static const MCString EmptyMap
A static instance of an empty map.
Member Enumeration Documentation
enum MCString::status_t [inherited]
Status codes that can be returned by WriteToDisk() and ReadFromDisk().
Enumerator:
MCS_SUCCESS
No errors.
MCS_EOPEN
Opening the file failed.
MCS_EWRITE
Writing to the file failed.
MCS_EWRITEFIL
WriteFilter() failed.
MCS_EREADFIL
ReadFilter() failed.
Constructor & Destructor Documentation
CTemplate::CTemplate () [inline]
References Init().
CTemplate::CTemplate (const CString & sFileName) [inline]
References Init().
CTemplate::CTemplate (const CSmartPtr< CTemplateOptions > & Options, CTemplate * pParent = NULL) [inline]
References Init().
virtual CTemplate::~CTemplate () [virtual]
Member Function Documentation
CTemplate& CTemplate::AddRow (const CString & sName)
void CTemplate::AddTagHandler (CSmartPtr< CTemplateTagHandler > spTagHandler) [inline]
Class for implementing custom tags in subclasses.
void CTemplate::AppendPath (const CString & sPath, bool bIncludesOnly = false)
void CTemplate::ClearPaths ()
virtual CString& MCString::Decode (CString & sValue) const [virtual, inherited]
Undo the effects of Encode().
This is an internal function.
void CTemplate::DelCurLoopContext ()
virtual CString& MCString::Encode (CString & sValue) const [virtual, inherited]
Encode a value so that it can safely be parsed by ReadFromDisk().
This is an internal function.
CString CTemplate::ExpandFile (const CString & sFilename, bool bFromInc = false)
CTemplateLoopContext* CTemplate::GetCurLoopContext ()
CTemplate* CTemplate::GetCurTemplate ()
const CString& CTemplate::GetFileName () const [inline]
std::vector<CTemplate*>* CTemplate::GetLoop (const CString & sName)
CTemplate* CTemplate::GetParent (bool bRoot)
CTemplate* CTemplate::GetRow (const CString & sName, unsigned int uIndex)
std::vector<CSmartPtr<CTemplateTagHandler> >& CTemplate::GetTagHandlers () [inline]
References GetTagHandlers().
Referenced by GetTagHandlers().
CString CTemplate::GetValue (const CString & sName, bool bFromIf = false)
bool CTemplate::HasLoop (const CString & sName)
void CTemplate::Init ()
Referenced by CTemplate().
bool CTemplate::IsTrue (const CString & sName)
CString CTemplate::MakePath (const CString & sPath) const
void CTemplate::PrependPath (const CString & sPath, bool bIncludesOnly = false)
bool CTemplate::Print (std::ostream & oOut)
bool CTemplate::Print (const CString & sFileName, std::ostream & oOut)
bool CTemplate::PrintString (CString & sRet)
virtual bool MCString::ReadFilter (CString & sKey, CString & sValue) const [inline, virtual, inherited]
Filter used while reading this map.
This function is called by ReadFromDisk() for each pair that is beging read. This function has the chance to modify the data that is being read.
Parameters:
sKey The key that was read. Can be modified.
sValue The value that was read. Can be modified.
Returns:
true unless ReadFromDisk() should fail with MCS_EWRITEFIL.
enum status_t MCString::ReadFromDisk (const CString & sPath) [inherited]
Read a map from a file.
Parameters:
sPath The file name to read from.
Returns:
The result of the operation.
See also:
ReadFilter.
void CTemplate::RemovePath (const CString & sPath)
CString CTemplate::ResolveLiteral (const CString & sString)
bool CTemplate::SetFile (const CString & sFileName)
void CTemplate::SetPath (const CString & sPath)
bool CTemplate::ValidExpr (const CString & sExpr)
bool CTemplate::ValidIf (const CString & sArgs)
virtual bool MCString::WriteFilter (CString & sKey, CString & sValue) const [inline, virtual, inherited]
Filter used while writing this map.
This function is called by WriteToDisk() for each pair that is going to be written. This function has the chance to modify the data that will be written.
Parameters:
sKey The key that will be written. Can be modified.
sValue The value that will be written. Can be modified.
Returns:
true unless WriteToDisk() should fail with MCS_EWRITEFIL.
enum status_t MCString::WriteToDisk (const CString & sPath, mode_t iMode = 0644) const [inherited]
Write this map to a file.
Parameters:
sPath The file name to write to.
iMode The mode for the file.
Returns:
The result of the operation.
See also:
WriteFilter.
Member Data Documentation
template<typename K, typename T> T std::map< K, T >::elements [inherited]
STL member.
const MCString MCString::EmptyMap [static, inherited]
A static instance of an empty map.
template<typename K, typename T> K std::map< K, T >::keys [inherited]
STL member.
The documentation for this class was generated from the following file:
Template.h