ZNC: CClientAuth Class Reference
CClientAuth Class Reference
#include <Client.h>
Public Member Functions
CClientAuth (CClient *pClient, const CString &sUsername, const CString &sPassword)
virtual ~CClientAuth ()
CClientAuth (const CClientAuth &)=delete
CClientAuth & operator= (const CClientAuth &)=delete
void Invalidate () override
void AcceptedLogin (CUser &User) override
void RefusedLogin (const CString &sReason) override
virtual void SetLoginInfo (const CString &sUsername, const CString &sPassword, CZNCSock *pSock)
void AcceptLogin (CUser &User)
void RefuseLogin (const CString &sReason)
const CString & GetUsername () const
const CString & GetPassword () const
Csock * GetSocket () const
CString GetRemoteIP () const
Protected Attributes
CClient * m_pClient
Constructor & Destructor Documentation
CClientAuth() [1/2]
CClientAuth::CClientAuth (CClient * pClient, const CString & sUsername, const CString & sPassword)
~CClientAuth()
virtual CClientAuth::~CClientAuth () inline virtual
References CAuthBase::operator=().
CClientAuth() [2/2]
CClientAuth::CClientAuth (const CClientAuth &) delete
Member Function Documentation
AcceptedLogin()
void CClientAuth::AcceptedLogin (CUser & User) override virtual
Implements CAuthBase.
AcceptLogin()
void CAuthBase::AcceptLogin (CUser & User) inherited
Referenced by CClient::CClient(), and CAuthBase::SetLoginInfo().
GetPassword()
const CString& CAuthBase::GetPassword () const inline inherited
GetRemoteIP()
CString CAuthBase::GetRemoteIP () const inherited
Referenced by CAuthBase::GetSocket().
GetSocket()
Csock* CAuthBase::GetSocket () const inline inherited
References CAuthBase::AcceptedLogin(), CAuthBase::GetRemoteIP(), CAuthBase::Invalidate(), and CAuthBase::RefusedLogin().
GetUsername()
const CString& CAuthBase::GetUsername () const inline inherited
Invalidate()
void CClientAuth::Invalidate () inline override virtual
Reimplemented from CAuthBase.
References CAuthBase::AcceptedLogin(), CAuthBase::Invalidate(), and CAuthBase::RefusedLogin().
operator=()
CClientAuth& CClientAuth::operator= (const CClientAuth &) delete
RefusedLogin()
void CClientAuth::RefusedLogin (const CString & sReason) override virtual
Implements CAuthBase.
RefuseLogin()
void CAuthBase::RefuseLogin (const CString & sReason) inherited
Referenced by CClient::CClient(), and CAuthBase::SetLoginInfo().
SetLoginInfo()
virtual void CAuthBase::SetLoginInfo (const CString & sUsername, const CString & sPassword, CZNCSock * pSock) inline virtual inherited
References CAuthBase::AcceptLogin(), and CAuthBase::RefuseLogin().
Member Data Documentation
m_pClient
CClient* CClientAuth::m_pClient protected
The documentation for this class was generated from the following file:
Client.h