ZNC: testing::internal::MatchesRegexMatcher Class Reference
testing::internal::MatchesRegexMatcher Class Reference
#include <gmock-matchers.h>
Public Member Functions
MatchesRegexMatcher (const RE *regex, bool full_match)
template<typename CharType >
bool MatchAndExplain (CharType *s, MatchResultListener *listener) const
template<class MatcheeStringType >
bool MatchAndExplain (const MatcheeStringType &s, MatchResultListener *) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Constructor & Destructor Documentation
testing::internal::MatchesRegexMatcher::MatchesRegexMatcher (const RE * regex, bool full_match) [inline]
Member Function Documentation
void testing::internal::MatchesRegexMatcher::DescribeNegationTo (::std::ostream * os) const [inline]
References testing::internal::RE::pattern().
void testing::internal::MatchesRegexMatcher::DescribeTo (::std::ostream * os) const [inline]
References testing::internal::RE::pattern().
template<typename CharType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (CharType * s, MatchResultListener * listener) const [inline]
template<class MatcheeStringType > bool testing::internal::MatchesRegexMatcher::MatchAndExplain (const MatcheeStringType & s, MatchResultListener *) const [inline]
References testing::internal::RE::FullMatch(), and testing::internal::RE::PartialMatch().
The documentation for this class was generated from the following file:
gmock-matchers.h