ZNC: CAuthBase Class Reference
CAuthBase Class Reference abstract
#include <Client.h>
Public Member Functions
CAuthBase (const CString &sUsername, const CString &sPassword, CZNCSock *pSock)
virtual ~CAuthBase ()
CAuthBase (const CAuthBase &)=delete
CAuthBase & operator= (const CAuthBase &)=delete
virtual void SetLoginInfo (const CString &sUsername, const CString &sPassword, CZNCSock *pSock)
void AcceptLogin (CUser &User)
void RefuseLogin (const CString &sReason)
const CString & GetUsername () const
const CString & GetPassword () const
Csock * GetSocket () const
CString GetRemoteIP () const
virtual void Invalidate ()
Protected Member Functions
virtual void AcceptedLogin (CUser &User)=0
virtual void RefusedLogin (const CString &sReason)=0
Static Private Member Functions
static CString t_s (const CString &sEnglish, const CString &sContext="")
static CInlineFormatMessage t_f (const CString &sEnglish, const CString &sContext="")
static CInlineFormatMessage t_p (const CString &sEnglish, const CString &sEnglishes, int iNum, const CString &sContext="")
static CDelayedTranslation t_d (const CString &sEnglish, const CString &sContext="")
Constructor & Destructor Documentation
CAuthBase::CAuthBase (const CString & sUsername, const CString & sPassword, CZNCSock * pSock) inline
Referenced by ~CAuthBase().
virtual CAuthBase::~CAuthBase () inline virtual
References CAuthBase(), and operator=().
CAuthBase::CAuthBase (const CAuthBase &) delete
Member Function Documentation
virtual void CAuthBase::AcceptedLogin (CUser & User) protected pure virtual
Implemented in CClientAuth.
Referenced by GetSocket(), and CClientAuth::Invalidate().
void CAuthBase::AcceptLogin (CUser & User)
Referenced by CClient::CClient(), and SetLoginInfo().
const CString& CAuthBase::GetPassword () const inline
CString CAuthBase::GetRemoteIP () const
Referenced by GetSocket().
Csock* CAuthBase::GetSocket () const inline
References AcceptedLogin(), GetRemoteIP(), Invalidate(), and RefusedLogin().
const CString& CAuthBase::GetUsername () const inline
virtual void CAuthBase::Invalidate () virtual
Reimplemented in CClientAuth.
Referenced by GetSocket(), and CClientAuth::Invalidate().
CAuthBase& CAuthBase::operator= (const CAuthBase &) delete
Referenced by CClient::CClient(), ~CAuthBase(), and CClientAuth::~CClientAuth().
virtual void CAuthBase::RefusedLogin (const CString & sReason) protected pure virtual
Implemented in CClientAuth.
Referenced by GetSocket(), and CClientAuth::Invalidate().
void CAuthBase::RefuseLogin (const CString & sReason)
Referenced by CClient::CClient(), and SetLoginInfo().
virtual void CAuthBase::SetLoginInfo (const CString & sUsername, const CString & sPassword, CZNCSock * pSock) inline virtual
References AcceptLogin(), and RefuseLogin().
The documentation for this class was generated from the following file:
Client.h