ZNC: CSSSListener Class Reference
CSSSListener Class Reference
#include <Csocket.h>
Public Member Functions
CSSSListener (uint16_t iPort, const CS_STRING &sBindHost="")
void SetDetach (bool b)
bool GetDetach () const
uint16_t GetPort () const
const CS_STRING & GetSockName () const
const CS_STRING & GetBindHost () const
bool GetIsSSL () const
int GetMaxConns () const
uint32_t GetTimeout () const
CSSockAddr::EAFRequire GetAFRequire () const
const CS_STRING & GetCipher () const
const CS_STRING & GetDHParamLocation () const
const CS_STRING & GetKeyLocation () const
const CS_STRING & GetPemLocation () const
const CS_STRING & GetPemPass () const
uint32_t GetRequireClientCertFlags () const
void SetPort (uint16_t iPort)
sets the port to listen on. Set to 0 to listen on a random port
void SetSockName (const CS_STRING &sSockName)
sets the sock name for later reference (ie FindSockByName)
void SetBindHost (const CS_STRING &sBindHost)
sets the host to bind to
void SetIsSSL (bool b)
set to true to enable SSL
void SetMaxConns (int i)
set max connections as called by accept()
void SetTimeout (uint32_t i)
sets the listen timeout. The listener class will close after timeout has been reached if not 0
void SetAFRequire (CSSockAddr::EAFRequire iAFRequire)
sets the AF family type required
void SetCipher (const CS_STRING &s)
set the cipher strength to use, default is HIGH
void SetPemLocation (const CS_STRING &s)
set the location of the pemfile
void SetKeyLocation (const CS_STRING &s)
set the location of the keyfile
void SetDHParamLocation (const CS_STRING &s)
set the location of the dhparamfile
void SetPemPass (const CS_STRING &s)
set the pemfile pass
void SetRequiresClientCert (bool b)
set to true if require a client certificate (deprecated
void SetRequireClientCertFlags (unsigned int iRequireCertFlags)
bitwise flags, 0 means don't require cert, SSL_VERIFY_PEER verifies peers, SSL_VERIFY_FAIL_IF_NO_PEER_CERT will cause the connection to fail if no cert
Constructor & Destructor Documentation
CSSSListener::CSSSListener (uint16_t iPort, const CS_STRING & sBindHost = "") inline
Member Function Documentation
CSSockAddr::EAFRequire CSListener::GetAFRequire () const inline inherited
const CS_STRING& CSListener::GetBindHost () const inline inherited
const CS_STRING& CSListener::GetCipher () const inline inherited
bool CSListener::GetDetach () const inline inherited
const CS_STRING& CSListener::GetDHParamLocation () const inline inherited
bool CSListener::GetIsSSL () const inline inherited
const CS_STRING& CSListener::GetKeyLocation () const inline inherited
int CSListener::GetMaxConns () const inline inherited
const CS_STRING& CSListener::GetPemLocation () const inline inherited
const CS_STRING& CSListener::GetPemPass () const inline inherited
uint16_t CSListener::GetPort () const inline inherited
uint32_t CSListener::GetRequireClientCertFlags () const inline inherited
const CS_STRING& CSListener::GetSockName () const inline inherited
uint32_t CSListener::GetTimeout () const inline inherited
void CSListener::SetAFRequire (CSSockAddr::EAFRequire iAFRequire) inline inherited
sets the AF family type required
Referenced by CSockManager::ListenHost(), and CSockManager::ListenRand().
void CSListener::SetBindHost (const CS_STRING & sBindHost) inline inherited
sets the host to bind to
void CSListener::SetCipher (const CS_STRING & s) inline inherited
set the cipher strength to use, default is HIGH
void CSListener::SetDetach (bool b) inline inherited
void CSListener::SetDHParamLocation (const CS_STRING & s) inline inherited
set the location of the dhparamfile
void CSListener::SetIsSSL (bool b) inline inherited
set to true to enable SSL
Referenced by CSockManager::ListenHost(), and CSockManager::ListenRand().
void CSListener::SetKeyLocation (const CS_STRING & s) inline inherited
set the location of the keyfile
void CSListener::SetMaxConns (int i) inline inherited
set max connections as called by accept()
Referenced by CSockManager::ListenHost(), and CSockManager::ListenRand().
void CSListener::SetPemLocation (const CS_STRING & s) inline inherited
set the location of the pemfile
void CSListener::SetPemPass (const CS_STRING & s) inline inherited
set the pemfile pass
void CSListener::SetPort (uint16_t iPort) inline inherited
sets the port to listen on. Set to 0 to listen on a random port
void CSListener::SetRequireClientCertFlags (unsigned int iRequireCertFlags) inline inherited
bitwise flags, 0 means don't require cert, SSL_VERIFY_PEER verifies peers, SSL_VERIFY_FAIL_IF_NO_PEER_CERT will cause the connection to fail if no cert
void CSListener::SetRequiresClientCert (bool b) inline inherited
set to true if require a client certificate (deprecated
See Also
SetRequireClientCertFlags)
void CSListener::SetSockName (const CS_STRING & sSockName) inline inherited
sets the sock name for later reference (ie FindSockByName)
Referenced by CSockManager::ListenHost(), and CSockManager::ListenRand().
void CSListener::SetTimeout (uint32_t i) inline inherited
sets the listen timeout. The listener class will close after timeout has been reached if not 0
Referenced by CSockManager::ListenHost(), and CSockManager::ListenRand().
The documentation for this class was generated from the following file:
Csocket.h