ZNC: CDir Class Reference
CDir Class Reference
#include <FileUtils.h>
Public Member Functions
CDir (const CString &sDir)
CDir ()
~CDir ()
void CleanUp ()
size_t Fill (const CString &sDir)
size_t FillByWildcard (const CString &sDir, const CString &sWildcard)
unsigned int Chmod (mode_t mode)
unsigned int Delete ()
CFile::EFileAttr GetSortAttr () const
bool IsDescending () const
Static Public Member Functions
static unsigned int Chmod (mode_t mode, const CString &sWildcard, const CString &sDir=".")
static unsigned int Delete (const CString &sWildcard, const CString &sDir=".")
static CString CheckPathPrefix (const CString &sPath, const CString &sAdd, const CString &sHomeDir="")
static CString ChangeDir (const CString &sPath, const CString &sAdd, const CString &sHomeDir="")
static bool MakeDir (const CString &sPath, mode_t iMode=0700)
static CString GetCWD ()
Public Attributes
T elements
STL member.
Protected Attributes
CFile::EFileAttr m_eSortAttr
bool m_bDesc
Constructor & Destructor Documentation
CDir() [1/2]
CDir::CDir (const CString & sDir) inline
References Fill().
CDir() [2/2]
CDir::CDir () inline
~CDir()
CDir::~CDir () inline
References CleanUp().
Member Function Documentation
ChangeDir()
static CString CDir::ChangeDir (const CString & sPath, const CString & sAdd, const CString & sHomeDir = "") static
CheckPathPrefix()
static CString CDir::CheckPathPrefix (const CString & sPath, const CString & sAdd, const CString & sHomeDir = "") static
Chmod() [1/2]
unsigned int CDir::Chmod (mode_t mode) inline
Chmod() [2/2]
static unsigned int CDir::Chmod (mode_t mode, const CString & sWildcard, const CString & sDir = ".") inline static
References Chmod(), and FillByWildcard().
Referenced by Chmod().
CleanUp()
void CDir::CleanUp () inline
Referenced by ~CDir(), and FillByWildcard().
Delete() [1/2]
unsigned int CDir::Delete () inline
Delete() [2/2]
static unsigned int CDir::Delete (const CString & sWildcard, const CString & sDir = ".") inline static
References Delete(), and FillByWildcard().
Referenced by Delete().
Fill()
size_t CDir::Fill (const CString & sDir) inline
References FillByWildcard().
Referenced by CDir().
FillByWildcard()
size_t CDir::FillByWildcard (const CString & sDir, const CString & sWildcard) inline
References CleanUp(), CString::TrimSuffix_n(), and CString::WildCmp().
Referenced by Chmod(), Delete(), and Fill().
GetCWD()
static CString CDir::GetCWD () inline static
GetSortAttr()
CFile::EFileAttr CDir::GetSortAttr () const inline
References m_eSortAttr.
IsDescending()
bool CDir::IsDescending () const inline
References m_bDesc.
MakeDir()
static bool CDir::MakeDir (const CString & sPath, mode_t iMode = 0700) static
Member Data Documentation
elements
T std::vector< T >::elements inherited
STL member.
m_bDesc
bool CDir::m_bDesc protected
Referenced by IsDescending().
m_eSortAttr
CFile::EFileAttr CDir::m_eSortAttr protected
Referenced by GetSortAttr().
The documentation for this class was generated from the following file:
FileUtils.h