ZNC: CIRCSock Class Reference
CIRCSock Class Reference
#include <IRCSock.h>
Public Types
enum EChanModeArgs { ListArg = 0, HasArg = 1, ArgWhenSet = 2, NoArg = 3 }
enum ETConn {
OUTBOUND = 0, LISTENER = 1, INBOUND = 2, OUTBOUND = 0,
LISTENER = 1, INBOUND = 2
}
enum ETConn {
OUTBOUND = 0, LISTENER = 1, INBOUND = 2, OUTBOUND = 0,
LISTENER = 1, INBOUND = 2
}
enum EFRead {
READ_EOF = 0, READ_ERR = -1, READ_EAGAIN = -2, READ_CONNREFUSED = -3,
READ_TIMEDOUT = -4, READ_EOF = 0, READ_ERR = -1, READ_EAGAIN = -2,
READ_CONNREFUSED = -3, READ_TIMEDOUT = -4
}
enum EFRead {
READ_EOF = 0, READ_ERR = -1, READ_EAGAIN = -2, READ_CONNREFUSED = -3,
READ_TIMEDOUT = -4, READ_EOF = 0, READ_ERR = -1, READ_EAGAIN = -2,
READ_CONNREFUSED = -3, READ_TIMEDOUT = -4
}
enum EFSelect {
SEL_OK = 0, SEL_TIMEOUT = -1, SEL_EAGAIN = -2, SEL_ERR = -3,
SEL_OK = 0, SEL_TIMEOUT = -1, SEL_EAGAIN = -2, SEL_ERR = -3
}
enum EFSelect {
SEL_OK = 0, SEL_TIMEOUT = -1, SEL_EAGAIN = -2, SEL_ERR = -3,
SEL_OK = 0, SEL_TIMEOUT = -1, SEL_EAGAIN = -2, SEL_ERR = -3
}
enum ESSLMethod {
SSL23 = 0, SSL2 = 2, SSL3 = 3, TLS1 = 4,
TLS11 = 5, TLS12 = 6, SSL23 = 0, SSL2 = 2,
SSL3 = 3, TLS1 = 4, TLS11 = 5, TLS12 = 6
}
enum ESSLMethod {
SSL23 = 0, SSL2 = 2, SSL3 = 3, TLS1 = 4,
TLS11 = 5, TLS12 = 6, SSL23 = 0, SSL2 = 2,
SSL3 = 3, TLS1 = 4, TLS11 = 5, TLS12 = 6
}
enum EDisableProtocol {
EDP_None = 0, EDP_SSLv2 = 1, EDP_SSLv3 = 2, EDP_TLSv1 = 4,
EDP_TLSv1_1 = 8, EDP_TLSv1_2 = 16, EDP_SSL = (EDP_SSLv2|EDP_SSLv3), EDP_None = 0,
EDP_SSLv2 = 1, EDP_SSLv3 = 2, EDP_TLSv1 = 4, EDP_TLSv1_1 = 8,
EDP_TLSv1_2 = 16, EDP_SSL = (EDP_SSLv2|EDP_SSLv3)
}
enum EDisableProtocol {
EDP_None = 0, EDP_SSLv2 = 1, EDP_SSLv3 = 2, EDP_TLSv1 = 4,
EDP_TLSv1_1 = 8, EDP_TLSv1_2 = 16, EDP_SSL = (EDP_SSLv2|EDP_SSLv3), EDP_None = 0,
EDP_SSLv2 = 1, EDP_SSLv3 = 2, EDP_TLSv1 = 4, EDP_TLSv1_1 = 8,
EDP_TLSv1_2 = 16, EDP_SSL = (EDP_SSLv2|EDP_SSLv3)
}
enum ECONState {
CST_START = 0, CST_DNS = CST_START, CST_BINDVHOST = 1, CST_DESTDNS = 2,
CST_CONNECT = 3, CST_CONNECTSSL = 4, CST_OK = 5, CST_START = 0,
CST_DNS = CST_START, CST_BINDVHOST = 1, CST_DESTDNS = 2, CST_CONNECT = 3,
CST_CONNECTSSL = 4, CST_OK = 5
}
enum ECONState {
CST_START = 0, CST_DNS = CST_START, CST_BINDVHOST = 1, CST_DESTDNS = 2,
CST_CONNECT = 3, CST_CONNECTSSL = 4, CST_OK = 5, CST_START = 0,
CST_DNS = CST_START, CST_BINDVHOST = 1, CST_DESTDNS = 2, CST_CONNECT = 3,
CST_CONNECTSSL = 4, CST_OK = 5
}
enum ECloseType {
CLT_DONT = 0, CLT_NOW = 1, CLT_AFTERWRITE = 2, CLT_DEREFERENCE = 3,
CLT_DONT = 0, CLT_NOW = 1, CLT_AFTERWRITE = 2, CLT_DEREFERENCE = 3
}
enum ECloseType {
CLT_DONT = 0, CLT_NOW = 1, CLT_AFTERWRITE = 2, CLT_DEREFERENCE = 3,
CLT_DONT = 0, CLT_NOW = 1, CLT_AFTERWRITE = 2, CLT_DEREFERENCE = 3
}
enum { TMO_READ = 1, TMO_WRITE = 2, TMO_ACCEPT = 4, TMO_ALL = TMO_READ|TMO_WRITE|TMO_ACCEPT }
this timeout isn't just connection timeout, but also timeout on NOT recieving data, to disable this set it to 0 then the normal TCP timeout will apply (basically TCP will kill a dead connection) Set the timeout, set to 0 to never timeout
enum EDNSLType { DNS_VHOST, DNS_DEST, DNS_VHOST, DNS_DEST }
enum EDNSLType { DNS_VHOST, DNS_DEST, DNS_VHOST, DNS_DEST }
enum { TMO_READ = 1, TMO_WRITE = 2, TMO_ACCEPT = 4, TMO_ALL = TMO_READ|TMO_WRITE|TMO_ACCEPT }
this timeout isn't just connection timeout, but also timeout on NOT recieving data, to disable this set it to 0 then the normal TCP timeout will apply (basically TCP will kill a dead connection) Set the timeout, set to 0 to never timeout
Public Member Functions
CIRCSock (CIRCNetwork *pNetwork)
virtual ~CIRCSock ()
CIRCSock (const CIRCSock &)
CIRCSock & operator= (const CIRCSock &)
void ReadLine (const CString &sData) override
void Connected () override
Connected event.
void Disconnected () override
Disconnected event.
void ConnectionRefused () override
Connection Refused Event.
void SockError (int iErrno, const CString &sDescription) override
void Timeout () override
Sock Timed out event.
void ReachedMaxBuffer () override
This WARNING event is called when your buffer for readline exceeds the warning threshold and triggers this event.
void PutIRC (const CString &sLine)
void PutIRCQuick (const CString &sLine)
Should be used for PONG only.
void ResetChans ()
void Quit (const CString &sQuitMsg="")
void PauseCap ()
You can call this from CModule::OnServerCapResult to suspend sending other CAP requests and CAP END for a while.
void ResumeCap ()
If you used PauseCap, call this when CAP negotiation and logging in should be resumed again.
void SetPass (const CString &s)
unsigned int GetMaxNickLen () const
EChanModeArgs GetModeType (unsigned char uMode) const
unsigned char GetPermFromMode (unsigned char uMode) const
const std::map< unsigned char,
EChanModeArgs > & GetChanModes () const
bool IsPermChar (const char c) const
bool IsPermMode (const char c) const
const CString & GetPerms () const
const CString & GetPermModes () const
CString GetNickMask () const
const CString & GetNick () const
const CString & GetPass () const
CIRCNetwork * GetNetwork () const
bool HasNamesx () const
bool HasUHNames () const
bool HasAwayNotify () const
bool HasAccountNotify () const
bool HasExtendedJoin () const
bool HasServerTime () const
const std::set< unsigned char > & GetUserModes () const
bool IsAuthed () const
const SCString & GetAcceptedCaps () const
bool IsCapAccepted (const CString &sCap)
const MCString & GetISupport () const
CString GetISupport (const CString &sKey, const CString &sDefault="") const
void ForwardRaw353 (const CMessage &Message) const
void ForwardRaw353 (const CMessage &Message, CClient *pClient) const
int ConvertAddress (const struct sockaddr_storage *pAddr, socklen_t iAddrLen, CS_STRING &sIP, u_short *piPort) const override
virtual int ConvertAddress (const struct sockaddr_storage *pAddr, socklen_t iAddrLen, CS_STRING &sIP, uint16_t *piPort) const
retrieve name info (numeric only) for a given sockaddr_storage
int VerifyPeerCertificate (int iPreVerify, X509_STORE_CTX *pStoreCTX) override
this is hooked in via SSL_set_verify, and be default it just returns 1 meaning success
void SSLHandShakeFinished () override
called once the SSL handshake is complete, this is triggered via SSL_CB_HANDSHAKE_DONE in SSL_set_info_callback()
void SetHostToVerifySSL (const CString &sHost)
CString GetSSLPeerFingerprint () const
void SetSSLTrustedPeerFingerprints (const SCString &ssFPs)
void SetEncoding (const CString &)
virtual CString GetRemoteIP () const
virtual Csock * GetSockObj (const CS_STRING &sHostname, uint16_t iPort)
override this for accept sockets
virtual Csock * GetSockObj (const CS_STRING &sHostname, uint16_t iPort)
override this for accept sockets
virtual void Dereference ()
in the event you pass this class to Copy(), you MUST call this function or on the original Csock other wise bad side effects will happen (double deletes, weird sock closures, etc) if you call this function and have not handled the internal pointers, other bad things can happend (memory leaks, fd leaks, etc) the whole point of this function is to allow this class to go away without shutting down
virtual void Dereference ()
in the event you pass this class to Copy(), you MUST call this function or on the original Csock other wise bad side effects will happen (double deletes, weird sock closures, etc) if you call this function and have not handled the internal pointers, other bad things can happend (memory leaks, fd leaks, etc) the whole point of this function is to allow this class to go away without shutting down
virtual void Copy (const Csock &cCopy)
use this to copy a sock from one to the other, override it if you have special needs in the event of a copy
virtual void Copy (const Csock &cCopy)
use this to copy a sock from one to the other, override it if you have special needs in the event of a copy
Csock & operator<< (const CS_STRING &s)
Csock & operator<< (std::ostream &(*io)(std::ostream &))
Csock & operator<< (int32_t i)
Csock & operator<< (uint32_t i)
Csock & operator<< (int64_t i)
Csock & operator<< (uint64_t i)
Csock & operator<< (float i)
Csock & operator<< (double i)
Csock & operator<< (const CS_STRING &s)
Csock & operator<< (std::ostream &(*io)(std::ostream &))
Csock & operator<< (int32_t i)
Csock & operator<< (uint32_t i)
Csock & operator<< (int64_t i)
Csock & operator<< (uint64_t i)
Csock & operator<< (float i)
Csock & operator<< (double i)
virtual bool Connect ()
Create the connection, this is used by the socket manager, and shouldn't be called directly by the user.
virtual bool Connect ()
Create the connection, this is used by the socket manager, and shouldn't be called directly by the user.
virtual bool Listen (uint16_t iPort, int iMaxConns=SOMAXCONN, const CS_STRING &sBindHost="", uint32_t iTimeout=0, bool bDetach=false)
Listens for connections.
virtual bool Listen (uint16_t iPort, int iMaxConns=SOMAXCONN, const CS_STRING &sBindHost="", uint32_t iTimeout=0, bool bDetach=false)
Listens for connections.
virtual cs_sock_t Accept (CS_STRING &sHost, uint16_t &iRPort)
Accept an inbound connection, this is used internally.
virtual cs_sock_t Accept (CS_STRING &sHost, uint16_t &iRPort)
Accept an inbound connection, this is used internally.
virtual bool AcceptSSL ()
Accept an inbound SSL connection, this is used internally and called after Accept.
virtual bool AcceptSSL ()
Accept an inbound SSL connection, this is used internally and called after Accept.
virtual bool SSLClientSetup ()
This sets up the SSL Client, this is used internally.
virtual bool SSLClientSetup ()
This sets up the SSL Client, this is used internally.
virtual bool SSLServerSetup ()
This sets up the SSL Server, this is used internally.
virtual bool SSLServerSetup ()
This sets up the SSL Server, this is used internally.
virtual bool ConnectSSL ()
Create the SSL connection.
virtual bool ConnectSSL ()
Create the SSL connection.
bool StartTLS ()
start a TLS connection on an existing plain connection
bool StartTLS ()
start a TLS connection on an existing plain connection
virtual bool Write (const char *data, size_t len)
Write data to the socket.
virtual bool Write (const CS_STRING &sData)
Write a text string to the socket.
virtual bool Write (const char *data, size_t len)
Write data to the socket.
virtual bool Write (const CS_STRING &sData)
Write a text string to the socket.
virtual cs_ssize_t Read (char *data, size_t len)
Read from the socket Just pass in a pointer, big enough to hold len bytes.
virtual cs_ssize_t Read (char *data, size_t len)
Read from the socket Just pass in a pointer, big enough to hold len bytes.
CS_STRING GetLocalIP () const
CS_STRING GetLocalIP () const
virtual bool IsConnected () const
Tells you if the socket is connected.
virtual bool IsConnected () const
Tells you if the socket is connected.
virtual void SetIsConnected (bool b)
Sets the sock, telling it its connected (internal use only)
virtual void SetIsConnected (bool b)
Sets the sock, telling it its connected (internal use only)
cs_sock_t & GetRSock ()
returns a reference to the sock
const cs_sock_t & GetRSock () const
cs_sock_t & GetRSock ()
returns a reference to the sock
const cs_sock_t & GetRSock () const
void SetRSock (cs_sock_t iSock)
void SetRSock (cs_sock_t iSock)
cs_sock_t & GetWSock ()
const cs_sock_t & GetWSock () const
cs_sock_t & GetWSock ()
const cs_sock_t & GetWSock () const
void SetWSock (cs_sock_t iSock)
void SetWSock (cs_sock_t iSock)
void SetSock (cs_sock_t iSock)
void SetSock (cs_sock_t iSock)
cs_sock_t & GetSock ()
const cs_sock_t & GetSock () const
cs_sock_t & GetSock ()
const cs_sock_t & GetSock () const
void CallSockError (int iErrno, const CS_STRING &sDescription="")
calls SockError, if sDescription is not set, then strerror is used to pull out a default description
void CallSockError (int iErrno, const CS_STRING &sDescription="")
calls SockError, if sDescription is not set, then strerror is used to pull out a default description
virtual void ResetTimer ()
resets the time counter, this is virtual in the event you need an event on the timer being Reset
virtual void ResetTimer ()
resets the time counter, this is virtual in the event you need an event on the timer being Reset
void PauseRead ()
will pause/unpause reading on this socket
void PauseRead ()
will pause/unpause reading on this socket
void UnPauseRead ()
void UnPauseRead ()
bool IsReadPaused () const
bool IsReadPaused () const
void SetTimeout (int iTimeout, uint32_t iTimeoutType=TMO_ALL)
Currently this uses the same value for all timeouts, and iTimeoutType merely states which event will be checked for timeouts.
void SetTimeout (int iTimeout, uint32_t iTimeoutType=TMO_ALL)
Currently this uses the same value for all timeouts, and iTimeoutType merely states which event will be checked for timeouts.
void SetTimeoutType (uint32_t iTimeoutType)
void SetTimeoutType (uint32_t iTimeoutType)
int GetTimeout () const
int GetTimeout () const
uint32_t GetTimeoutType () const
uint32_t GetTimeoutType () const
virtual bool CheckTimeout (time_t iNow)
returns true if the socket has timed out
virtual bool CheckTimeout (time_t iNow)
returns true if the socket has timed out
virtual void PushBuff (const char *data, size_t len, bool bStartAtZero=false)
pushes data up on the buffer, if a line is ready it calls the ReadLine event
virtual void PushBuff (const char *data, size_t len, bool bStartAtZero=false)
pushes data up on the buffer, if a line is ready it calls the ReadLine event
CS_STRING & GetInternalReadBuffer ()
This gives access to the internal read buffer, if your not going to use ReadLine(), then you may want to clear this out (if its binary data and not many '\n')
CS_STRING & GetInternalReadBuffer ()
This gives access to the internal read buffer, if your not going to use ReadLine(), then you may want to clear this out (if its binary data and not many '\n')
CS_STRING & GetInternalWriteBuffer ()
This gives access to the internal write buffer.
CS_STRING & GetInternalWriteBuffer ()
This gives access to the internal write buffer.
void SetMaxBufferThreshold (uint32_t iThreshold)
sets the max buffered threshold when EnableReadLine() is enabled
void SetMaxBufferThreshold (uint32_t iThreshold)
sets the max buffered threshold when EnableReadLine() is enabled
uint32_t GetMaxBufferThreshold () const
uint32_t GetMaxBufferThreshold () const
int GetType () const
Returns the connection type from enum eConnType.
int GetType () const
Returns the connection type from enum eConnType.
void SetType (int iType)
void SetType (int iType)
const CS_STRING & GetSockName () const
Returns a reference to the socket name.
const CS_STRING & GetSockName () const
Returns a reference to the socket name.
void SetSockName (const CS_STRING &sName)
void SetSockName (const CS_STRING &sName)
const CS_STRING & GetHostName () const
Returns a reference to the host name.
const CS_STRING & GetHostName () const
Returns a reference to the host name.
void SetHostName (const CS_STRING &sHostname)
void SetHostName (const CS_STRING &sHostname)
uint64_t GetStartTime () const
Gets the starting time of this socket.
uint64_t GetStartTime () const
Gets the starting time of this socket.
void ResetStartTime ()
Resets the start time.
void ResetStartTime ()
Resets the start time.
uint64_t GetBytesRead () const
Gets the amount of data read during the existence of the socket.
uint64_t GetBytesRead () const
Gets the amount of data read during the existence of the socket.
void ResetBytesRead ()
void ResetBytesRead ()
uint64_t GetBytesWritten () const
Gets the amount of data written during the existence of the socket.
uint64_t GetBytesWritten () const
Gets the amount of data written during the existence of the socket.
void ResetBytesWritten ()
void ResetBytesWritten ()
double GetAvgRead (uint64_t iSample=1000) const
Get Avg Read Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
double GetAvgRead (uint64_t iSample=1000) const
Get Avg Read Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
double GetAvgWrite (uint64_t iSample=1000) const
Get Avg Write Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
double GetAvgWrite (uint64_t iSample=1000) const
Get Avg Write Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
uint16_t GetRemotePort () const
Returns the remote port.
uint16_t GetRemotePort () const
Returns the remote port.
uint16_t GetLocalPort () const
Returns the local port.
uint16_t GetLocalPort () const
Returns the local port.
uint16_t GetPort () const
Returns the port.
uint16_t GetPort () const
Returns the port.
void SetPort (uint16_t iPort)
void SetPort (uint16_t iPort)
void Close (ECloseType eCloseType=CLT_NOW)
just mark us as closed, the parent can pick it up
void Close (ECloseType eCloseType=CLT_NOW)
just mark us as closed, the parent can pick it up
ECloseType GetCloseType () const
returns int of type to close
ECloseType GetCloseType () const
returns int of type to close
bool IsClosed () const
bool IsClosed () const
void NonBlockingIO ()
Use this to change your fd's to blocking or none blocking.
void NonBlockingIO ()
Use this to change your fd's to blocking or none blocking.
bool GetSSL () const
Return true if this socket is using ssl. Note this does not mean the SSL state is finished, but simply that its configured to use ssl.
bool GetSSL () const
Return true if this socket is using ssl. Note this does not mean the SSL state is finished, but simply that its configured to use ssl.
void SetSSL (bool b)
void SetSSL (bool b)
void DisableSSLProtocols (u_int uDisableOpts)
bitwise setter,
void DisableSSLProtocols (u_int uDisableOpts)
bitwise setter,
void DisableSSLCompression ()
allow disabling compression
void DisableSSLCompression ()
allow disabling compression
void FollowSSLCipherServerPreference ()
select the ciphers in server-preferred order
void FollowSSLCipherServerPreference ()
select the ciphers in server-preferred order
void SetCipher (const CS_STRING &sCipher)
Set the cipher type (openssl cipher [to see ciphers available])
void SetCipher (const CS_STRING &sCipher)
Set the cipher type (openssl cipher [to see ciphers available])
const CS_STRING & GetCipher () const
const CS_STRING & GetCipher () const
void SetPemLocation (const CS_STRING &sPemFile)
Set the pem file location.
void SetPemLocation (const CS_STRING &sPemFile)
Set the pem file location.
const CS_STRING & GetPemLocation () const
const CS_STRING & GetPemLocation () const
void SetPemPass (const CS_STRING &sPassword)
void SetPemPass (const CS_STRING &sPassword)
const CS_STRING & GetPemPass () const
const CS_STRING & GetPemPass () const
void SetSSLMethod (int iMethod)
Set the SSL method type.
void SetSSLMethod (int iMethod)
Set the SSL method type.
int GetSSLMethod () const
int GetSSLMethod () const
void SetSSLObject (SSL *ssl, bool bDeleteExisting=false)
void SetSSLObject (SSL *ssl, bool bDeleteExisting=false)
SSL * GetSSLObject () const
SSL * GetSSLObject () const
void SetCTXObject (SSL_CTX *sslCtx, bool bDeleteExisting=false)
void SetCTXObject (SSL_CTX *sslCtx, bool bDeleteExisting=false)
SSL_SESSION * GetSSLSession () const
SSL_SESSION * GetSSLSession () const
void SetCertVerifyCB (FPCertVerifyCB pFP)
setting this to NULL will allow the default openssl verification process kick in
void SetCertVerifyCB (FPCertVerifyCB pFP)
setting this to NULL will allow the default openssl verification process kick in
bool HasWriteBuffer () const
Get the send buffer.
bool HasWriteBuffer () const
Get the send buffer.
void ClearWriteBuffer ()
void ClearWriteBuffer ()
bool SslIsEstablished () const
is SSL_accept finished ? is the ssl properly finished (from write no error)
bool SslIsEstablished () const
is SSL_accept finished ? is the ssl properly finished (from write no error)
bool ConnectInetd (bool bIsSSL=false, const CS_STRING &sHostname="")
Use this to bind this socket to inetd.
bool ConnectInetd (bool bIsSSL=false, const CS_STRING &sHostname="")
Use this to bind this socket to inetd.
bool ConnectFD (int iReadFD, int iWriteFD, const CS_STRING &sName, bool bIsSSL=false, ETConn eDirection=INBOUND)
Tie this guy to an existing real file descriptor.
bool ConnectFD (int iReadFD, int iWriteFD, const CS_STRING &sName, bool bIsSSL=false, ETConn eDirection=INBOUND)
Tie this guy to an existing real file descriptor.
X509 * GetX509 () const
Get the peer's X509 cert.
X509 * GetX509 () const
Get the peer's X509 cert.
CS_STRING GetPeerPubKey () const
Returns the peer's public key.
CS_STRING GetPeerPubKey () const
Returns the peer's public key.
long GetPeerFingerprint (CS_STRING &sFP) const
Returns the peer's certificate finger print.
long GetPeerFingerprint (CS_STRING &sFP) const
Returns the peer's certificate finger print.
uint32_t GetRequireClientCertFlags () const
uint32_t GetRequireClientCertFlags () const
void SetRequiresClientCert (bool bRequiresCert)
legacy, deprecated
void SetRequiresClientCert (bool bRequiresCert)
legacy, deprecated
void SetRequireClientCertFlags (uint32_t iRequireClientCertFlags)
bitwise flags, 0 means don't require cert, SSL_VERIFY_PEER verifies peers, SSL_VERIFY_FAIL_IF_NO_PEER_CERT will cause the connection to fail if no cert
void SetRequireClientCertFlags (uint32_t iRequireClientCertFlags)
bitwise flags, 0 means don't require cert, SSL_VERIFY_PEER verifies peers, SSL_VERIFY_FAIL_IF_NO_PEER_CERT will cause the connection to fail if no cert
virtual void SetParentSockName (const CS_STRING &sParentName)
Set The INBOUND Parent sockname.
virtual void SetParentSockName (const CS_STRING &sParentName)
Set The INBOUND Parent sockname.
const CS_STRING & GetParentSockName () const
const CS_STRING & GetParentSockName () const
virtual void SetRate (uint32_t iBytes, uint64_t iMilliseconds)
sets the rate at which we can send data
virtual void SetRate (uint32_t iBytes, uint64_t iMilliseconds)
sets the rate at which we can send data
uint32_t GetRateBytes () const
uint32_t GetRateBytes () const
uint64_t GetRateTime () const
uint64_t GetRateTime () const
virtual void ReadData (const char *data, size_t len)
Ready to read data event.
virtual void ReadData (const char *data, size_t len)
Ready to read data event.
virtual void ReadLine (const CS_STRING &sLine)
Ready to Read a full line event.
void EnableReadLine ()
set the value of m_bEnableReadLine to true, we don't want to store a buffer for ReadLine, unless we want it
void EnableReadLine ()
set the value of m_bEnableReadLine to true, we don't want to store a buffer for ReadLine, unless we want it
void DisableReadLine ()
void DisableReadLine ()
bool HasReadLine () const
returns the value of m_bEnableReadLine, if ReadLine is enabled
bool HasReadLine () const
returns the value of m_bEnableReadLine, if ReadLine is enabled
virtual void SockError (int iErrno, const CS_STRING &sDescription)
A sock error occured event.
virtual bool ConnectionFrom (const CS_STRING &sHost, uint16_t iPort)
Incoming Connection Event return false and the connection will fail default returns true.
virtual bool ConnectionFrom (const CS_STRING &sHost, uint16_t iPort)
Incoming Connection Event return false and the connection will fail default returns true.
virtual void Listening (const CS_STRING &sBindIP, uint16_t uPort)
called when type is LISTENER and the listening port is up and running
virtual void Listening (const CS_STRING &sBindIP, uint16_t uPort)
called when type is LISTENER and the listening port is up and running
virtual void ReadPaused ()
This gets called every iteration of CSocketManager::Select() if the socket is ReadPaused.
virtual void ReadPaused ()
This gets called every iteration of CSocketManager::Select() if the socket is ReadPaused.
virtual void SSLFinishSetup (SSL *pSSL)
Gets called immediatly after the m_ssl member is setup and initialized, useful if you need to assign anything to this ssl session via SSL_set_ex_data.
virtual void SSLFinishSetup (SSL *pSSL)
Gets called immediatly after the m_ssl member is setup and initialized, useful if you need to assign anything to this ssl session via SSL_set_ex_data.
virtual bool SNIConfigureServer (const CS_STRING &sHostname, CS_STRING &sPemFile, CS_STRING &sPemPass)
gets called when a SNI request is sent, and used to configure a SNI session
virtual bool SNIConfigureServer (const CS_STRING &sHostname, CS_STRING &sPemFile, CS_STRING &sPemPass)
gets called when a SNI request is sent, and used to configure a SNI session
virtual bool SNIConfigureClient (CS_STRING &sHostname)
called to configure the SNI client
virtual bool SNIConfigureClient (CS_STRING &sHostname)
called to configure the SNI client
SSL_CTX * SetupServerCTX ()
creates a new SSL_CTX based on the setup of this sock
SSL_CTX * SetupServerCTX ()
creates a new SSL_CTX based on the setup of this sock
time_t GetTimeSinceLastDataTransaction (time_t iNow=0) const
return how long it has been (in seconds) since the last read or successful write
time_t GetTimeSinceLastDataTransaction (time_t iNow=0) const
return how long it has been (in seconds) since the last read or successful write
time_t GetLastCheckTimeout () const
time_t GetLastCheckTimeout () const
time_t GetNextCheckTimeout (time_t iNow=0) const
Returns the time when CheckTimeout() should be called next.
time_t GetNextCheckTimeout (time_t iNow=0) const
Returns the time when CheckTimeout() should be called next.
virtual int GetPending () const
return the data imediatly ready for read
virtual int GetPending () const
return the data imediatly ready for read
ECONState GetConState () const
returns the current connection state
ECONState GetConState () const
returns the current connection state
void SetConState (ECONState eState)
sets the connection state to eState
void SetConState (ECONState eState)
sets the connection state to eState
bool CreateSocksFD ()
grabs fd's for the sockets
bool CreateSocksFD ()
grabs fd's for the sockets
void CloseSocksFD ()
puts the socks back to the state they were prior to calling CreateSocksFD
void CloseSocksFD ()
puts the socks back to the state they were prior to calling CreateSocksFD
const CS_STRING & GetBindHost () const
const CS_STRING & GetBindHost () const
void SetBindHost (const CS_STRING &sBindHost)
void SetBindHost (const CS_STRING &sBindHost)
int DNSLookup (EDNSLType eDNSLType)
dns lookup
int DNSLookup (EDNSLType eDNSLType)
dns lookup
bool SetupVHost ()
this is only used on outbound connections, listeners bind in a different spot
bool SetupVHost ()
this is only used on outbound connections, listeners bind in a different spot
bool GetIPv6 () const
bool GetIPv6 () const
void SetIPv6 (bool b)
void SetIPv6 (bool b)
void SetAFRequire (CSSockAddr::EAFRequire iAFRequire)
void SetAFRequire (CSSockAddr::EAFRequire iAFRequire)
bool AllowWrite (uint64_t &iNOW) const
returns true if this socket can write its data, primarily used with rate shaping, initialize iNOW to 0 and it sets it on the first call
bool AllowWrite (uint64_t &iNOW) const
returns true if this socket can write its data, primarily used with rate shaping, initialize iNOW to 0 and it sets it on the first call
void SetSkipConnect (bool b)
void SetSkipConnect (bool b)
virtual int GetAddrInfo (const CS_STRING &sHostname, CSSockAddr &csSockAddr)
override this call with your own DNS lookup method if you have one.
virtual int GetAddrInfo (const CS_STRING &sHostname, CSSockAddr &csSockAddr)
override this call with your own DNS lookup method if you have one.
int GetMaxConns () const
returns the number of max pending connections when type is LISTENER
int GetMaxConns () const
returns the number of max pending connections when type is LISTENER
void CleanupCrons ()
void CleanupCrons ()
void CleanupFDMonitors ()
void CleanupFDMonitors ()
const std::vector< CCron * > & GetCrons () const
returns a const reference to the crons associated to this socket
const std::vector< CCron * > & GetCrons () const
returns a const reference to the crons associated to this socket
virtual void Cron ()
This has a garbage collecter, and is used internall to call the jobs.
virtual void Cron ()
This has a garbage collecter, and is used internall to call the jobs.
virtual void AddCron (CCron *pcCron)
insert a newly created cron
virtual void AddCron (CCron *pcCron)
insert a newly created cron
virtual void DelCron (const CS_STRING &sName, bool bDeleteAll=true, bool bCaseSensitive=true)
deletes a cron by name
virtual void DelCron (uint32_t iPos)
delete cron by idx
virtual void DelCron (const CS_STRING &sName, bool bDeleteAll=true, bool bCaseSensitive=true)
deletes a cron by name
virtual void DelCron (uint32_t iPos)
delete cron by idx
virtual void DelCronByAddr (CCron *pcCron)
delete cron by address
virtual void DelCronByAddr (CCron *pcCron)
delete cron by address
void CheckFDs (const std::map< cs_sock_t, short > &miiReadyFds)
void CheckFDs (const std::map< cs_sock_t, short > &miiReadyFds)
void AssignFDs (std::map< cs_sock_t, short > &miiReadyFds, struct timeval *tvtimeout)
void AssignFDs (std::map< cs_sock_t, short > &miiReadyFds, struct timeval *tvtimeout)
void MonitorFD (CSMonitorFD *pMonitorFD)
add an FD set to monitor
void MonitorFD (CSMonitorFD *pMonitorFD)
add an FD set to monitor
Static Public Member Functions
static bool IsFloodProtected (double fRate)
Protected Types
enum { errnoBadSSLCert = 12569 }
Protected Attributes
bool m_bAuthed
bool m_bNamesx
bool m_bUHNames
bool m_bAwayNotify
bool m_bAccountNotify
bool m_bExtendedJoin
bool m_bServerTime
CString m_sPerms
CString m_sPermModes
std::set< unsigned char > m_scUserModes
std::map< unsigned char,
EChanModeArgs > m_mueChanModes
CIRCNetwork * m_pNetwork
CNick m_Nick
CString m_sPass
std::map< CString, CChan * > m_msChans
unsigned int m_uMaxNickLen
unsigned int m_uCapPaused
SCString m_ssAcceptedCaps
SCString m_ssPendingCaps
time_t m_lastCTCP
unsigned int m_uNumCTCP
MCString m_mISupport
std::deque< CString > m_vsSendQueue
short int m_iSendsAllowed
unsigned short int m_uFloodBurst
double m_fFloodRate
bool m_bFloodProtection
std::vector< CCron * > m_vcCrons
std::vector< CSMonitorFD * > m_vcMonitorFD
Static Protected Attributes
static const time_t m_uCTCPFloodTime
static const unsigned int m_uCTCPFloodCount
Friends
class CIRCFloodTimer
Member Enumeration Documentation
anonymous enum [inherited]
this timeout isn't just connection timeout, but also timeout on NOT recieving data, to disable this set it to 0 then the normal TCP timeout will apply (basically TCP will kill a dead connection) Set the timeout, set to 0 to never timeout
Enumerator:
TMO_READ
TMO_WRITE
TMO_ACCEPT
TMO_ALL
anonymous enum [protected, inherited]
Enumerator:
errnoBadSSLCert
anonymous enum [inherited]
this timeout isn't just connection timeout, but also timeout on NOT recieving data, to disable this set it to 0 then the normal TCP timeout will apply (basically TCP will kill a dead connection) Set the timeout, set to 0 to never timeout
Enumerator:
TMO_READ
TMO_WRITE
TMO_ACCEPT
TMO_ALL
enum CIRCSock::EChanModeArgs
Enumerator:
ListArg
HasArg
ArgWhenSet
NoArg
enum Csock::ECloseType [inherited]
Enumerator:
CLT_DONT
don't close DER
CLT_NOW
close immediatly
CLT_AFTERWRITE
close after finishing writing the buffer
CLT_DEREFERENCE
used after copy in Csock::Dereference() to cleanup a sock thats being shutdown
CLT_DONT
don't close DER
CLT_NOW
close immediatly
CLT_AFTERWRITE
close after finishing writing the buffer
CLT_DEREFERENCE
used after copy in Csock::Dereference() to cleanup a sock thats being shutdown
enum Csock::ECloseType [inherited]
Enumerator:
CLT_DONT
don't close DER
CLT_NOW
close immediatly
CLT_AFTERWRITE
close after finishing writing the buffer
CLT_DEREFERENCE
used after copy in Csock::Dereference() to cleanup a sock thats being shutdown
CLT_DONT
don't close DER
CLT_NOW
close immediatly
CLT_AFTERWRITE
close after finishing writing the buffer
CLT_DEREFERENCE
used after copy in Csock::Dereference() to cleanup a sock thats being shutdown
enum Csock::ECONState [inherited]
Enumerator:
CST_START
CST_DNS
CST_BINDVHOST
CST_DESTDNS
CST_CONNECT
CST_CONNECTSSL
CST_OK
CST_START
CST_DNS
CST_BINDVHOST
CST_DESTDNS
CST_CONNECT
CST_CONNECTSSL
CST_OK
enum Csock::ECONState [inherited]
Enumerator:
CST_START
CST_DNS
CST_BINDVHOST
CST_DESTDNS
CST_CONNECT
CST_CONNECTSSL
CST_OK
CST_START
CST_DNS
CST_BINDVHOST
CST_DESTDNS
CST_CONNECT
CST_CONNECTSSL
CST_OK
enum Csock::EDisableProtocol [inherited]
Enumerator:
EDP_None
disable nothing
EDP_SSLv2
disable SSL version 2
EDP_SSLv3
disable SSL version 3
EDP_TLSv1
disable TLS version 1
EDP_TLSv1_1
disable TLS version 1.1
EDP_TLSv1_2
disable TLS version 1.2
EDP_SSL
EDP_None
disable nothing
EDP_SSLv2
disable SSL version 2
EDP_SSLv3
disable SSL version 3
EDP_TLSv1
disable TLS version 1
EDP_TLSv1_1
disable TLS version 1.1
EDP_TLSv1_2
disable TLS version 1.2
EDP_SSL
enum Csock::EDisableProtocol [inherited]
Enumerator:
EDP_None
disable nothing
EDP_SSLv2
disable SSL version 2
EDP_SSLv3
disable SSL version 3
EDP_TLSv1
disable TLS version 1
EDP_TLSv1_1
disable TLS version 1.1
EDP_TLSv1_2
disable TLS version 1.2
EDP_SSL
EDP_None
disable nothing
EDP_SSLv2
disable SSL version 2
EDP_SSLv3
disable SSL version 3
EDP_TLSv1
disable TLS version 1
EDP_TLSv1_1
disable TLS version 1.1
EDP_TLSv1_2
disable TLS version 1.2
EDP_SSL
enum Csock::EDNSLType [inherited]
Enumerator:
DNS_VHOST
this lookup is for the vhost bind
DNS_DEST
this lookup is for the destination address
DNS_VHOST
this lookup is for the vhost bind
DNS_DEST
this lookup is for the destination address
enum Csock::EDNSLType [inherited]
Enumerator:
DNS_VHOST
this lookup is for the vhost bind
DNS_DEST
this lookup is for the destination address
DNS_VHOST
this lookup is for the vhost bind
DNS_DEST
this lookup is for the destination address
enum Csock::EFRead [inherited]
Enumerator:
READ_EOF
End Of File, done reading.
READ_ERR
Error on the socket, socket closed, done reading.
READ_EAGAIN
Try to get data again.
READ_CONNREFUSED
Connection Refused.
READ_TIMEDOUT
Connection timed out.
READ_EOF
End Of File, done reading.
READ_ERR
Error on the socket, socket closed, done reading.
READ_EAGAIN
Try to get data again.
READ_CONNREFUSED
Connection Refused.
READ_TIMEDOUT
Connection timed out.
enum Csock::EFRead [inherited]
Enumerator:
READ_EOF
End Of File, done reading.
READ_ERR
Error on the socket, socket closed, done reading.
READ_EAGAIN
Try to get data again.
READ_CONNREFUSED
Connection Refused.
READ_TIMEDOUT
Connection timed out.
READ_EOF
End Of File, done reading.
READ_ERR
Error on the socket, socket closed, done reading.
READ_EAGAIN
Try to get data again.
READ_CONNREFUSED
Connection Refused.
READ_TIMEDOUT
Connection timed out.
enum Csock::EFSelect [inherited]
Enumerator:
SEL_OK
Select passed ok.
SEL_TIMEOUT
Select timed out.
SEL_EAGAIN
Select wants you to try again.
SEL_ERR
Select recieved an error.
SEL_OK
Select passed ok.
SEL_TIMEOUT
Select timed out.
SEL_EAGAIN
Select wants you to try again.
SEL_ERR
Select recieved an error.
enum Csock::EFSelect [inherited]
Enumerator:
SEL_OK
Select passed ok.
SEL_TIMEOUT
Select timed out.
SEL_EAGAIN
Select wants you to try again.
SEL_ERR
Select recieved an error.
SEL_OK
Select passed ok.
SEL_TIMEOUT
Select timed out.
SEL_EAGAIN
Select wants you to try again.
SEL_ERR
Select recieved an error.
enum Csock::ESSLMethod [inherited]
Enumerator:
SSL23
SSL2
SSL3
TLS1
TLS11
TLS12
SSL23
SSL2
SSL3
TLS1
TLS11
TLS12
enum Csock::ESSLMethod [inherited]
Enumerator:
SSL23
SSL2
SSL3
TLS1
TLS11
TLS12
SSL23
SSL2
SSL3
TLS1
TLS11
TLS12
enum Csock::ETConn [inherited]
Enumerator:
OUTBOUND
outbound connection
LISTENER
a socket accepting connections
INBOUND
an inbound connection, passed from LISTENER
OUTBOUND
outbound connection
LISTENER
a socket accepting connections
INBOUND
an inbound connection, passed from LISTENER
enum Csock::ETConn [inherited]
Enumerator:
OUTBOUND
outbound connection
LISTENER
a socket accepting connections
INBOUND
an inbound connection, passed from LISTENER
OUTBOUND
outbound connection
LISTENER
a socket accepting connections
INBOUND
an inbound connection, passed from LISTENER
Constructor & Destructor Documentation
CIRCSock::CIRCSock (CIRCNetwork * pNetwork)
virtual CIRCSock::~CIRCSock () [virtual]
CIRCSock::CIRCSock (const CIRCSock &)
Member Function Documentation
virtual cs_sock_t Csock::Accept (CS_STRING & sHost, uint16_t & iRPort) [virtual, inherited]
Accept an inbound connection, this is used internally.
virtual cs_sock_t Csock::Accept (CS_STRING & sHost, uint16_t & iRPort) [virtual, inherited]
Accept an inbound connection, this is used internally.
virtual bool Csock::AcceptSSL () [virtual, inherited]
Accept an inbound SSL connection, this is used internally and called after Accept.
virtual bool Csock::AcceptSSL () [virtual, inherited]
Accept an inbound SSL connection, this is used internally and called after Accept.
virtual void CSockCommon::AddCron (CCron * pcCron) [virtual, inherited]
insert a newly created cron
virtual void CSockCommon::AddCron (CCron * pcCron) [virtual, inherited]
insert a newly created cron
bool Csock::AllowWrite (uint64_t & iNOW) const [inherited]
returns true if this socket can write its data, primarily used with rate shaping, initialize iNOW to 0 and it sets it on the first call
bool Csock::AllowWrite (uint64_t & iNOW) const [inherited]
returns true if this socket can write its data, primarily used with rate shaping, initialize iNOW to 0 and it sets it on the first call
void CSockCommon::AssignFDs (std::map< cs_sock_t, short > & miiReadyFds, struct timeval * tvtimeout) [inherited]
void CSockCommon::AssignFDs (std::map< cs_sock_t, short > & miiReadyFds, struct timeval * tvtimeout) [inherited]
void Csock::CallSockError (int iErrno, const CS_STRING & sDescription = "") [inherited]
calls SockError, if sDescription is not set, then strerror is used to pull out a default description
Parameters:
iErrno the errno to send
sDescription the description of the error that occurred
void Csock::CallSockError (int iErrno, const CS_STRING & sDescription = "") [inherited]
calls SockError, if sDescription is not set, then strerror is used to pull out a default description
Parameters:
iErrno the errno to send
sDescription the description of the error that occurred
void CSockCommon::CheckFDs (const std::map< cs_sock_t, short > & miiReadyFds) [inherited]
void CSockCommon::CheckFDs (const std::map< cs_sock_t, short > & miiReadyFds) [inherited]
virtual bool Csock::CheckTimeout (time_t iNow) [virtual, inherited]
returns true if the socket has timed out
virtual bool Csock::CheckTimeout (time_t iNow) [virtual, inherited]
returns true if the socket has timed out
void CSockCommon::CleanupCrons () [inherited]
void CSockCommon::CleanupCrons () [inherited]
void CSockCommon::CleanupFDMonitors () [inherited]
void CSockCommon::CleanupFDMonitors () [inherited]
void Csock::ClearWriteBuffer () [inherited]
void Csock::ClearWriteBuffer () [inherited]
void Csock::Close (ECloseType eCloseType = CLT_NOW) [inherited]
just mark us as closed, the parent can pick it up
Referenced by CExecSock::Kill().
void Csock::Close (ECloseType eCloseType = CLT_NOW) [inherited]
just mark us as closed, the parent can pick it up
void Csock::CloseSocksFD () [inherited]
puts the socks back to the state they were prior to calling CreateSocksFD
void Csock::CloseSocksFD () [inherited]
puts the socks back to the state they were prior to calling CreateSocksFD
virtual bool Csock::Connect () [virtual, inherited]
Create the connection, this is used by the socket manager, and shouldn't be called directly by the user.
Returns:
true on success
virtual bool Csock::Connect () [virtual, inherited]
Create the connection, this is used by the socket manager, and shouldn't be called directly by the user.
Returns:
true on success
void CIRCSock::Connected () [override, virtual]
Connected event.
Reimplemented from Csock.
bool Csock::ConnectFD (int iReadFD, int iWriteFD, const CS_STRING & sName, bool bIsSSL = false, ETConn eDirection = INBOUND) [inherited]
Tie this guy to an existing real file descriptor.
Referenced by CExecSock::Execute().
bool Csock::ConnectFD (int iReadFD, int iWriteFD, const CS_STRING & sName, bool bIsSSL = false, ETConn eDirection = INBOUND) [inherited]
Tie this guy to an existing real file descriptor.
bool Csock::ConnectInetd (bool bIsSSL = false, const CS_STRING & sHostname = "") [inherited]
Use this to bind this socket to inetd.
bool Csock::ConnectInetd (bool bIsSSL = false, const CS_STRING & sHostname = "") [inherited]
Use this to bind this socket to inetd.
virtual bool Csock::ConnectionFrom (const CS_STRING & sHost, uint16_t iPort) [inline, virtual, inherited]
Incoming Connection Event return false and the connection will fail default returns true.
virtual bool Csock::ConnectionFrom (const CS_STRING & sHost, uint16_t iPort) [inline, virtual, inherited]
Incoming Connection Event return false and the connection will fail default returns true.
void CIRCSock::ConnectionRefused () [override, virtual]
Connection Refused Event.
Reimplemented from Csock.
virtual bool Csock::ConnectSSL () [virtual, inherited]
Create the SSL connection.
Returns:
true on success
This is used by the socket manager, and shouldn't be called directly by the user.
virtual bool Csock::ConnectSSL () [virtual, inherited]
Create the SSL connection.
Returns:
true on success
This is used by the socket manager, and shouldn't be called directly by the user.
int CZNCSock::ConvertAddress (const struct sockaddr_storage * pAddr, socklen_t iAddrLen, CS_STRING & sIP, u_short * piPort) const [override, inherited]
virtual int Csock::ConvertAddress (const struct sockaddr_storage * pAddr, socklen_t iAddrLen, CS_STRING & sIP, uint16_t * piPort) const [virtual, inherited]
retrieve name info (numeric only) for a given sockaddr_storage
Parameters:
pAddr the sockaddr_storage
iAddrLen the length
sIP filled with the IP from getnameinfo
piPort if not null, filled with the port
Returns:
0 on success.
In the event you want to do additional work before or after getnameinfo is called, you can override this and do just that. One example is in the event that an ipv6 ip is a mapped ipv4 mapped, you can check like so.
if(pAddr->ss_family == AF_INET6 && IN6_IS_ADDR_V4MAPPED(&(((const struct sockaddr_in6 *)pAddr)->sin6_addr))
virtual void Csock::Copy (const Csock & cCopy) [virtual, inherited]
use this to copy a sock from one to the other, override it if you have special needs in the event of a copy
virtual void Csock::Copy (const Csock & cCopy) [virtual, inherited]
use this to copy a sock from one to the other, override it if you have special needs in the event of a copy
bool Csock::CreateSocksFD () [inherited]
grabs fd's for the sockets
bool Csock::CreateSocksFD () [inherited]
grabs fd's for the sockets
virtual void CSockCommon::Cron () [virtual, inherited]
This has a garbage collecter, and is used internall to call the jobs.
virtual void CSockCommon::Cron () [virtual, inherited]
This has a garbage collecter, and is used internall to call the jobs.
virtual void CSockCommon::DelCron (const CS_STRING & sName, bool bDeleteAll = true, bool bCaseSensitive = true) [virtual, inherited]
deletes a cron by name
Parameters:
sName the name of the cron
bDeleteAll delete all crons that match sName
bCaseSensitive use strcmp or strcasecmp
virtual void CSockCommon::DelCron (const CS_STRING & sName, bool bDeleteAll = true, bool bCaseSensitive = true) [virtual, inherited]
deletes a cron by name
Parameters:
sName the name of the cron
bDeleteAll delete all crons that match sName
bCaseSensitive use strcmp or strcasecmp
virtual void CSockCommon::DelCron (uint32_t iPos) [virtual, inherited]
delete cron by idx
virtual void CSockCommon::DelCron (uint32_t iPos) [virtual, inherited]
delete cron by idx
virtual void CSockCommon::DelCronByAddr (CCron * pcCron) [virtual, inherited]
delete cron by address
virtual void CSockCommon::DelCronByAddr (CCron * pcCron) [virtual, inherited]
delete cron by address
virtual void Csock::Dereference () [virtual, inherited]
in the event you pass this class to Copy(), you MUST call this function or on the original Csock other wise bad side effects will happen (double deletes, weird sock closures, etc) if you call this function and have not handled the internal pointers, other bad things can happend (memory leaks, fd leaks, etc) the whole point of this function is to allow this class to go away without shutting down
virtual void Csock::Dereference () [virtual, inherited]
in the event you pass this class to Copy(), you MUST call this function or on the original Csock other wise bad side effects will happen (double deletes, weird sock closures, etc) if you call this function and have not handled the internal pointers, other bad things can happend (memory leaks, fd leaks, etc) the whole point of this function is to allow this class to go away without shutting down
void Csock::DisableReadLine () [inherited]
void Csock::DisableReadLine () [inherited]
void Csock::DisableSSLCompression () [inline, inherited]
allow disabling compression
void Csock::DisableSSLCompression () [inline, inherited]
allow disabling compression
void Csock::DisableSSLProtocols (u_int uDisableOpts) [inline, inherited]
bitwise setter,
See also:
EDisableProtocol
void Csock::DisableSSLProtocols (u_int uDisableOpts) [inline, inherited]
bitwise setter,
See also:
EDisableProtocol
void CIRCSock::Disconnected () [override, virtual]
Disconnected event.
Reimplemented from Csock.
int Csock::DNSLookup (EDNSLType eDNSLType) [inherited]
dns lookup
See also:
EDNSLType
Returns:
0 for success, EAGAIN to check back again (same arguments as before), ETIMEDOUT on failure
int Csock::DNSLookup (EDNSLType eDNSLType) [inherited]
dns lookup
See also:
EDNSLType
Returns:
0 for success, EAGAIN to check back again (same arguments as before), ETIMEDOUT on failure
void Csock::EnableReadLine () [inherited]
set the value of m_bEnableReadLine to true, we don't want to store a buffer for ReadLine, unless we want it
void Csock::EnableReadLine () [inherited]
set the value of m_bEnableReadLine to true, we don't want to store a buffer for ReadLine, unless we want it
void Csock::FollowSSLCipherServerPreference () [inline, inherited]
select the ciphers in server-preferred order
void Csock::FollowSSLCipherServerPreference () [inline, inherited]
select the ciphers in server-preferred order
void CIRCSock::ForwardRaw353 (const CMessage & Message) const
void CIRCSock::ForwardRaw353 (const CMessage & Message, CClient * pClient) const
const SCString& CIRCSock::GetAcceptedCaps () const [inline]
References m_ssAcceptedCaps.
virtual int Csock::GetAddrInfo (const CS_STRING & sHostname, CSSockAddr & csSockAddr) [virtual, inherited]
override this call with your own DNS lookup method if you have one.
By default this function is blocking
Parameters:
sHostname the hostname to resolve
csSockAddr the destination sock address info
See also:
CSSockAddr
Returns:
0 on success, ETIMEDOUT if no lookup was found, EAGAIN if you should check again later for an answer
virtual int Csock::GetAddrInfo (const CS_STRING & sHostname, CSSockAddr & csSockAddr) [virtual, inherited]
override this call with your own DNS lookup method if you have one.
By default this function is blocking
Parameters:
sHostname the hostname to resolve
csSockAddr the destination sock address info
See also:
CSSockAddr
Returns:
0 on success, ETIMEDOUT if no lookup was found, EAGAIN if you should check again later for an answer
double Csock::GetAvgRead (uint64_t iSample = 1000) const [inherited]
Get Avg Read Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
double Csock::GetAvgRead (uint64_t iSample = 1000) const [inherited]
Get Avg Read Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
double Csock::GetAvgWrite (uint64_t iSample = 1000) const [inherited]
Get Avg Write Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
double Csock::GetAvgWrite (uint64_t iSample = 1000) const [inherited]
Get Avg Write Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
const CS_STRING& Csock::GetBindHost () const [inline, inherited]
const CS_STRING& Csock::GetBindHost () const [inline, inherited]
uint64_t Csock::GetBytesRead () const [inherited]
Gets the amount of data read during the existence of the socket.
uint64_t Csock::GetBytesRead () const [inherited]
Gets the amount of data read during the existence of the socket.
uint64_t Csock::GetBytesWritten () const [inherited]
Gets the amount of data written during the existence of the socket.
uint64_t Csock::GetBytesWritten () const [inherited]
Gets the amount of data written during the existence of the socket.
const std::map<unsigned char, EChanModeArgs>& CIRCSock::GetChanModes () const [inline]
References m_mueChanModes.
const CS_STRING& Csock::GetCipher () const [inherited]
const CS_STRING& Csock::GetCipher () const [inherited]
ECloseType Csock::GetCloseType () const [inline, inherited]
returns int of type to close
See also:
ECloseType
ECloseType Csock::GetCloseType () const [inline, inherited]
returns int of type to close
See also:
ECloseType
ECONState Csock::GetConState () const [inline, inherited]
returns the current connection state
ECONState Csock::GetConState () const [inline, inherited]
returns the current connection state
const std::vector<CCron *>& CSockCommon::GetCrons () const [inline, inherited]
returns a const reference to the crons associated to this socket
const std::vector<CCron *>& CSockCommon::GetCrons () const [inline, inherited]
returns a const reference to the crons associated to this socket
const CS_STRING& Csock::GetHostName () const [inherited]
Returns a reference to the host name.
const CS_STRING& Csock::GetHostName () const [inherited]
Returns a reference to the host name.
CS_STRING& Csock::GetInternalReadBuffer () [inherited]
This gives access to the internal read buffer, if your not going to use ReadLine(), then you may want to clear this out (if its binary data and not many '\n')
CS_STRING& Csock::GetInternalReadBuffer () [inherited]
This gives access to the internal read buffer, if your not going to use ReadLine(), then you may want to clear this out (if its binary data and not many '\n')
CS_STRING& Csock::GetInternalWriteBuffer () [inherited]
This gives access to the internal write buffer.
If you want to check if the send queue fills up, check here.
CS_STRING& Csock::GetInternalWriteBuffer () [inherited]
This gives access to the internal write buffer.
If you want to check if the send queue fills up, check here.
bool Csock::GetIPv6 () const [inline, inherited]
bool Csock::GetIPv6 () const [inline, inherited]
const MCString& CIRCSock::GetISupport () const [inline]
References m_mISupport.
CString CIRCSock::GetISupport (const CString & sKey, const CString & sDefault = "") const
time_t Csock::GetLastCheckTimeout () const [inline, inherited]
time_t Csock::GetLastCheckTimeout () const [inline, inherited]
CS_STRING Csock::GetLocalIP () const [inherited]
CS_STRING Csock::GetLocalIP () const [inherited]
uint16_t Csock::GetLocalPort () const [inherited]
Returns the local port.
uint16_t Csock::GetLocalPort () const [inherited]
Returns the local port.
uint32_t Csock::GetMaxBufferThreshold () const [inherited]
uint32_t Csock::GetMaxBufferThreshold () const [inherited]
int Csock::GetMaxConns () const [inline, inherited]
returns the number of max pending connections when type is LISTENER
int Csock::GetMaxConns () const [inline, inherited]
returns the number of max pending connections when type is LISTENER
unsigned int CIRCSock::GetMaxNickLen () const [inline]
References m_uMaxNickLen.
EChanModeArgs CIRCSock::GetModeType (unsigned char uMode) const
CIRCNetwork* CIRCSock::GetNetwork () const [inline]
References m_pNetwork.
time_t Csock::GetNextCheckTimeout (time_t iNow = 0) const [inherited]
Returns the time when CheckTimeout() should be called next.
time_t Csock::GetNextCheckTimeout (time_t iNow = 0) const [inherited]
Returns the time when CheckTimeout() should be called next.
const CString& CIRCSock::GetNick () const [inline]
References CNick::GetNick(), and m_Nick.
CString CIRCSock::GetNickMask () const [inline]
References CNick::GetNickMask(), and m_Nick.
const CS_STRING& Csock::GetParentSockName () const [inherited]
const CS_STRING& Csock::GetParentSockName () const [inherited]
const CString& CIRCSock::GetPass () const [inline]
References m_sPass.
long Csock::GetPeerFingerprint (CS_STRING & sFP) const [inherited]
Returns the peer's certificate finger print.
long Csock::GetPeerFingerprint (CS_STRING & sFP) const [inherited]
Returns the peer's certificate finger print.
CS_STRING Csock::GetPeerPubKey () const [inherited]
Returns the peer's public key.
CS_STRING Csock::GetPeerPubKey () const [inherited]
Returns the peer's public key.
const CS_STRING& Csock::GetPemLocation () const [inherited]
const CS_STRING& Csock::GetPemLocation () const [inherited]
const CS_STRING& Csock::GetPemPass () const [inherited]
const CS_STRING& Csock::GetPemPass () const [inherited]
virtual int Csock::GetPending () const [virtual, inherited]
return the data imediatly ready for read
virtual int Csock::GetPending () const [virtual, inherited]
return the data imediatly ready for read
unsigned char CIRCSock::GetPermFromMode (unsigned char uMode) const
const CString& CIRCSock::GetPermModes () const [inline]
References m_sPermModes.
Referenced by IsPermMode().
const CString& CIRCSock::GetPerms () const [inline]
References m_sPerms.
Referenced by IsPermChar().
uint16_t Csock::GetPort () const [inherited]
Returns the port.
uint16_t Csock::GetPort () const [inherited]
Returns the port.
uint32_t Csock::GetRateBytes () const [inherited]
uint32_t Csock::GetRateBytes () const [inherited]
uint64_t Csock::GetRateTime () const [inherited]
uint64_t Csock::GetRateTime () const [inherited]
virtual CString CZNCSock::GetRemoteIP () const [inline, virtual, inherited]
Reimplemented from Csock.
Reimplemented in CHTTPSock.
uint16_t Csock::GetRemotePort () const [inherited]
Returns the remote port.
uint16_t Csock::GetRemotePort () const [inherited]
Returns the remote port.
uint32_t Csock::GetRequireClientCertFlags () const [inherited]
uint32_t Csock::GetRequireClientCertFlags () const [inherited]
cs_sock_t& Csock::GetRSock () [inherited]
returns a reference to the sock
Referenced by CExecSock::~CExecSock().
cs_sock_t& Csock::GetRSock () [inherited]
returns a reference to the sock
const cs_sock_t& Csock::GetRSock () const [inherited]
const cs_sock_t& Csock::GetRSock () const [inherited]
cs_sock_t& Csock::GetSock () [inherited]
cs_sock_t& Csock::GetSock () [inherited]
const cs_sock_t& Csock::GetSock () const [inherited]
const cs_sock_t& Csock::GetSock () const [inherited]
const CS_STRING& Csock::GetSockName () const [inherited]
Returns a reference to the socket name.
const CS_STRING& Csock::GetSockName () const [inherited]
Returns a reference to the socket name.
virtual Csock* Csock::GetSockObj (const CS_STRING & sHostname, uint16_t iPort) [virtual, inherited]
override this for accept sockets
virtual Csock* Csock::GetSockObj (const CS_STRING & sHostname, uint16_t iPort) [virtual, inherited]
override this for accept sockets
bool Csock::GetSSL () const [inherited]
Return true if this socket is using ssl. Note this does not mean the SSL state is finished, but simply that its configured to use ssl.
bool Csock::GetSSL () const [inherited]
Return true if this socket is using ssl. Note this does not mean the SSL state is finished, but simply that its configured to use ssl.
int Csock::GetSSLMethod () const [inherited]
int Csock::GetSSLMethod () const [inherited]
SSL* Csock::GetSSLObject () const [inherited]
SSL* Csock::GetSSLObject () const [inherited]
CString CZNCSock::GetSSLPeerFingerprint () const [inherited]
SSL_SESSION* Csock::GetSSLSession () const [inherited]
SSL_SESSION* Csock::GetSSLSession () const [inherited]
uint64_t Csock::GetStartTime () const [inherited]
Gets the starting time of this socket.
uint64_t Csock::GetStartTime () const [inherited]
Gets the starting time of this socket.
int Csock::GetTimeout () const [inherited]
int Csock::GetTimeout () const [inherited]
uint32_t Csock::GetTimeoutType () const [inherited]
uint32_t Csock::GetTimeoutType () const [inherited]
time_t Csock::GetTimeSinceLastDataTransaction (time_t iNow = 0) const [inherited]
return how long it has been (in seconds) since the last read or successful write
time_t Csock::GetTimeSinceLastDataTransaction (time_t iNow = 0) const [inherited]
return how long it has been (in seconds) since the last read or successful write
int Csock::GetType () const [inherited]
Returns the connection type from enum eConnType.
int Csock::GetType () const [inherited]
Returns the connection type from enum eConnType.
const std::set<unsigned char>& CIRCSock::GetUserModes () const [inline]
References m_scUserModes.
cs_sock_t& Csock::GetWSock () [inherited]
Referenced by CExecSock::~CExecSock().
cs_sock_t& Csock::GetWSock () [inherited]
const cs_sock_t& Csock::GetWSock () const [inherited]
const cs_sock_t& Csock::GetWSock () const [inherited]
X509* Csock::GetX509 () const [inherited]
Get the peer's X509 cert.
it is up to you, the caller to call X509_free() on this object
X509* Csock::GetX509 () const [inherited]
Get the peer's X509 cert.
it is up to you, the caller to call X509_free() on this object
bool CIRCSock::HasAccountNotify () const [inline]
References m_bAccountNotify.
bool CIRCSock::HasAwayNotify () const [inline]
References m_bAwayNotify.
bool CIRCSock::HasExtendedJoin () const [inline]
References m_bExtendedJoin.
bool CIRCSock::HasNamesx () const [inline]
References m_bNamesx.
bool Csock::HasReadLine () const [inline, inherited]
returns the value of m_bEnableReadLine, if ReadLine is enabled
bool Csock::HasReadLine () const [inline, inherited]
returns the value of m_bEnableReadLine, if ReadLine is enabled
bool CIRCSock::HasServerTime () const [inline]
References m_bServerTime.
bool CIRCSock::HasUHNames () const [inline]
References m_bUHNames.
bool Csock::HasWriteBuffer () const [inherited]
Get the send buffer.
bool Csock::HasWriteBuffer () const [inherited]
Get the send buffer.
bool CIRCSock::IsAuthed () const [inline]
References m_bAuthed.
bool CIRCSock::IsCapAccepted (const CString & sCap) [inline]
References m_ssAcceptedCaps.
bool Csock::IsClosed () const [inline, inherited]
bool Csock::IsClosed () const [inline, inherited]
virtual bool Csock::IsConnected () const [virtual, inherited]
Tells you if the socket is connected.
virtual bool Csock::IsConnected () const [virtual, inherited]
Tells you if the socket is connected.
static bool CIRCSock::IsFloodProtected (double fRate) [static]
bool CIRCSock::IsPermChar (const char c) const [inline]
References GetPerms().
bool CIRCSock::IsPermMode (const char c) const [inline]
References GetPermModes().
bool Csock::IsReadPaused () const [inherited]
bool Csock::IsReadPaused () const [inherited]
virtual bool Csock::Listen (uint16_t iPort, int iMaxConns = SOMAXCONN, const CS_STRING & sBindHost = "", uint32_t iTimeout = 0, bool bDetach = false) [virtual, inherited]
Listens for connections.
Parameters:
iPort the port to listen on
iMaxConns the maximum amount of pending connections to allow
sBindHost the vhost on which to listen
iTimeout if no connections come in by this timeout, the listener is closed
bDetach don't block waiting for port to come up, instead detach and return immediately
virtual bool Csock::Listen (uint16_t iPort, int iMaxConns = SOMAXCONN, const CS_STRING & sBindHost = "", uint32_t iTimeout = 0, bool bDetach = false) [virtual, inherited]
Listens for connections.
Parameters:
iPort the port to listen on
iMaxConns the maximum amount of pending connections to allow
sBindHost the vhost on which to listen
iTimeout if no connections come in by this timeout, the listener is closed
bDetach don't block waiting for port to come up, instead detach and return immediately
virtual void Csock::Listening (const CS_STRING & sBindIP, uint16_t uPort) [inline, virtual, inherited]
called when type is LISTENER and the listening port is up and running
Parameters:
sBindIP the IP that is being bound to. Empty if no bind restriction
uPort the listening port
virtual void Csock::Listening (const CS_STRING & sBindIP, uint16_t uPort) [inline, virtual, inherited]
called when type is LISTENER and the listening port is up and running
Parameters:
sBindIP the IP that is being bound to. Empty if no bind restriction
uPort the listening port
void CSockCommon::MonitorFD (CSMonitorFD * pMonitorFD) [inline, inherited]
add an FD set to monitor
void CSockCommon::MonitorFD (CSMonitorFD * pMonitorFD) [inline, inherited]
add an FD set to monitor
void Csock::NonBlockingIO () [inherited]
Use this to change your fd's to blocking or none blocking.
void Csock::NonBlockingIO () [inherited]
Use this to change your fd's to blocking or none blocking.
Csock& Csock::operator<< (const CS_STRING & s) [inherited]
Csock& Csock::operator<< (const CS_STRING & s) [inherited]
Csock& Csock::operator<< (std::ostream &(*)(std::ostream &) io) [inherited]
Csock& Csock::operator<< (std::ostream &(*)(std::ostream &) io) [inherited]
Csock& Csock::operator<< (int32_t i) [inherited]
Csock& Csock::operator<< (int32_t i) [inherited]
Csock& Csock::operator<< (uint32_t i) [inherited]
Csock& Csock::operator<< (uint32_t i) [inherited]
Csock& Csock::operator<< (int64_t i) [inherited]
Csock& Csock::operator<< (int64_t i) [inherited]
Csock& Csock::operator<< (uint64_t i) [inherited]
Csock& Csock::operator<< (uint64_t i) [inherited]
Csock& Csock::operator<< (float i) [inherited]
Csock& Csock::operator<< (float i) [inherited]
Csock& Csock::operator<< (double i) [inherited]
Csock& Csock::operator<< (double i) [inherited]
CIRCSock& CIRCSock::operator= (const CIRCSock &)
void CIRCSock::PauseCap ()
You can call this from CModule::OnServerCapResult to suspend sending other CAP requests and CAP END for a while.
Each call to PauseCap should be balanced with a call to ResumeCap.
void Csock::PauseRead () [inherited]
will pause/unpause reading on this socket
void Csock::PauseRead () [inherited]
will pause/unpause reading on this socket
virtual void Csock::PushBuff (const char * data, size_t len, bool bStartAtZero = false) [virtual, inherited]
pushes data up on the buffer, if a line is ready it calls the ReadLine event
virtual void Csock::PushBuff (const char * data, size_t len, bool bStartAtZero = false) [virtual, inherited]
pushes data up on the buffer, if a line is ready it calls the ReadLine event
void CIRCSock::PutIRC (const CString & sLine)
void CIRCSock::PutIRCQuick (const CString & sLine)
Should be used for PONG only.
void CIRCSock::Quit (const CString & sQuitMsg = "")
void CIRCSock::ReachedMaxBuffer () [override, virtual]
This WARNING event is called when your buffer for readline exceeds the warning threshold and triggers this event.
Either Override it and do nothing, or SetMaxBufferThreshold() This event will only get called if m_bEnableReadLine is enabled
Reimplemented from Csock.
virtual cs_ssize_t Csock::Read (char * data, size_t len) [virtual, inherited]
Read from the socket Just pass in a pointer, big enough to hold len bytes.
Parameters:
data the buffer to read into
len the size of the buffer
Returns:
Returns READ_EOF for EOF Returns READ_ERR for ERROR Returns READ_EAGAIN for Try Again (EAGAIN) Returns READ_CONNREFUSED for connection refused Returns READ_TIMEDOUT for a connection that timed out at the TCP level Otherwise returns the bytes read into data
virtual cs_ssize_t Csock::Read (char * data, size_t len) [virtual, inherited]
Read from the socket Just pass in a pointer, big enough to hold len bytes.
Parameters:
data the buffer to read into
len the size of the buffer
Returns:
Returns READ_EOF for EOF Returns READ_ERR for ERROR Returns READ_EAGAIN for Try Again (EAGAIN) Returns READ_CONNREFUSED for connection refused Returns READ_TIMEDOUT for a connection that timed out at the TCP level Otherwise returns the bytes read into data
virtual void Csock::ReadData (const char * data, size_t len) [inline, virtual, inherited]
Ready to read data event.
Reimplemented in CPySocket, CPerlSocket, and CHTTPSock.
virtual void Csock::ReadData (const char * data, size_t len) [inline, virtual, inherited]
Ready to read data event.
Reimplemented in CPySocket, CPerlSocket, and CHTTPSock.
void CIRCSock::ReadLine (const CString & sData) [override]
virtual void Csock::ReadLine (const CS_STRING & sLine) [inline, virtual, inherited]
Ready to Read a full line event.
If encoding is provided, this is guaranteed to be UTF-8
virtual void Csock::ReadPaused () [inline, virtual, inherited]
This gets called every iteration of CSocketManager::Select() if the socket is ReadPaused.
virtual void Csock::ReadPaused () [inline, virtual, inherited]
This gets called every iteration of CSocketManager::Select() if the socket is ReadPaused.
void Csock::ResetBytesRead () [inherited]
void Csock::ResetBytesRead () [inherited]
void Csock::ResetBytesWritten () [inherited]
void Csock::ResetBytesWritten () [inherited]
void CIRCSock::ResetChans ()
void Csock::ResetStartTime () [inherited]
Resets the start time.
void Csock::ResetStartTime () [inherited]
Resets the start time.
virtual void Csock::ResetTimer () [virtual, inherited]
resets the time counter, this is virtual in the event you need an event on the timer being Reset
virtual void Csock::ResetTimer () [virtual, inherited]
resets the time counter, this is virtual in the event you need an event on the timer being Reset
void CIRCSock::ResumeCap ()
If you used PauseCap, call this when CAP negotiation and logging in should be resumed again.
void Csock::SetAFRequire (CSSockAddr::EAFRequire iAFRequire) [inline, inherited]
void Csock::SetAFRequire (CSSockAddr::EAFRequire iAFRequire) [inline, inherited]
void Csock::SetBindHost (const CS_STRING & sBindHost) [inline, inherited]
void Csock::SetBindHost (const CS_STRING & sBindHost) [inline, inherited]
void Csock::SetCertVerifyCB (FPCertVerifyCB pFP) [inline, inherited]
setting this to NULL will allow the default openssl verification process kick in
void Csock::SetCertVerifyCB (FPCertVerifyCB pFP) [inline, inherited]
setting this to NULL will allow the default openssl verification process kick in
void Csock::SetCipher (const CS_STRING & sCipher) [inherited]
Set the cipher type (openssl cipher [to see ciphers available])
void Csock::SetCipher (const CS_STRING & sCipher) [inherited]
Set the cipher type (openssl cipher [to see ciphers available])
void Csock::SetConState (ECONState eState) [inline, inherited]
sets the connection state to eState
void Csock::SetConState (ECONState eState) [inline, inherited]
sets the connection state to eState
void Csock::SetCTXObject (SSL_CTX * sslCtx, bool bDeleteExisting = false) [inherited]
void Csock::SetCTXObject (SSL_CTX * sslCtx, bool bDeleteExisting = false) [inherited]
void CZNCSock::SetEncoding (const CString &) [inline, inherited]
void Csock::SetHostName (const CS_STRING & sHostname) [inherited]
void Csock::SetHostName (const CS_STRING & sHostname) [inherited]
void CZNCSock::SetHostToVerifySSL (const CString & sHost) [inline, inherited]
void Csock::SetIPv6 (bool b) [inline, inherited]
void Csock::SetIPv6 (bool b) [inline, inherited]
virtual void Csock::SetIsConnected (bool b) [virtual, inherited]
Sets the sock, telling it its connected (internal use only)
virtual void Csock::SetIsConnected (bool b) [virtual, inherited]
Sets the sock, telling it its connected (internal use only)
void Csock::SetMaxBufferThreshold (uint32_t iThreshold) [inherited]
sets the max buffered threshold when EnableReadLine() is enabled
void Csock::SetMaxBufferThreshold (uint32_t iThreshold) [inherited]
sets the max buffered threshold when EnableReadLine() is enabled
virtual void Csock::SetParentSockName (const CS_STRING & sParentName) [virtual, inherited]
Set The INBOUND Parent sockname.
virtual void Csock::SetParentSockName (const CS_STRING & sParentName) [virtual, inherited]
Set The INBOUND Parent sockname.
void CIRCSock::SetPass (const CString & s) [inline]
References m_sPass.
void Csock::SetPemLocation (const CS_STRING & sPemFile) [inherited]
Set the pem file location.
void Csock::SetPemLocation (const CS_STRING & sPemFile) [inherited]
Set the pem file location.
void Csock::SetPemPass (const CS_STRING & sPassword) [inherited]
void Csock::SetPemPass (const CS_STRING & sPassword) [inherited]
void Csock::SetPort (uint16_t iPort) [inherited]
void Csock::SetPort (uint16_t iPort) [inherited]
virtual void Csock::SetRate (uint32_t iBytes, uint64_t iMilliseconds) [virtual, inherited]
sets the rate at which we can send data
Parameters:
iBytes the amount of bytes we can write
iMilliseconds the amount of time we have to rate to iBytes
virtual void Csock::SetRate (uint32_t iBytes, uint64_t iMilliseconds) [virtual, inherited]
sets the rate at which we can send data
Parameters:
iBytes the amount of bytes we can write
iMilliseconds the amount of time we have to rate to iBytes
void Csock::SetRequireClientCertFlags (uint32_t iRequireClientCertFlags) [inline, inherited]
bitwise flags, 0 means don't require cert, SSL_VERIFY_PEER verifies peers, SSL_VERIFY_FAIL_IF_NO_PEER_CERT will cause the connection to fail if no cert
void Csock::SetRequireClientCertFlags (uint32_t iRequireClientCertFlags) [inline, inherited]
bitwise flags, 0 means don't require cert, SSL_VERIFY_PEER verifies peers, SSL_VERIFY_FAIL_IF_NO_PEER_CERT will cause the connection to fail if no cert
void Csock::SetRequiresClientCert (bool bRequiresCert) [inherited]
legacy, deprecated
See also:
SetRequireClientCertFlags
void Csock::SetRequiresClientCert (bool bRequiresCert) [inherited]
legacy, deprecated
See also:
SetRequireClientCertFlags
void Csock::SetRSock (cs_sock_t iSock) [inherited]
void Csock::SetRSock (cs_sock_t iSock) [inherited]
Referenced by CExecSock::~CExecSock().
void Csock::SetSkipConnect (bool b) [inline, inherited]
void Csock::SetSkipConnect (bool b) [inline, inherited]
void Csock::SetSock (cs_sock_t iSock) [inherited]
void Csock::SetSock (cs_sock_t iSock) [inherited]
void Csock::SetSockName (const CS_STRING & sName) [inherited]
void Csock::SetSockName (const CS_STRING & sName) [inherited]
void Csock::SetSSL (bool b) [inherited]
void Csock::SetSSL (bool b) [inherited]
void Csock::SetSSLMethod (int iMethod) [inherited]
Set the SSL method type.
void Csock::SetSSLMethod (int iMethod) [inherited]
Set the SSL method type.
void Csock::SetSSLObject (SSL * ssl, bool bDeleteExisting = false) [inherited]
void Csock::SetSSLObject (SSL * ssl, bool bDeleteExisting = false) [inherited]
void CZNCSock::SetSSLTrustedPeerFingerprints (const SCString & ssFPs) [inline, inherited]
void Csock::SetTimeout (int iTimeout, uint32_t iTimeoutType = TMO_ALL) [inherited]
Currently this uses the same value for all timeouts, and iTimeoutType merely states which event will be checked for timeouts.
void Csock::SetTimeout (int iTimeout, uint32_t iTimeoutType = TMO_ALL) [inherited]
Currently this uses the same value for all timeouts, and iTimeoutType merely states which event will be checked for timeouts.
void Csock::SetTimeoutType (uint32_t iTimeoutType) [inherited]
void Csock::SetTimeoutType (uint32_t iTimeoutType) [inherited]
void Csock::SetType (int iType) [inherited]
void Csock::SetType (int iType) [inherited]
SSL_CTX* Csock::SetupServerCTX () [inherited]
creates a new SSL_CTX based on the setup of this sock
SSL_CTX* Csock::SetupServerCTX () [inherited]
creates a new SSL_CTX based on the setup of this sock
bool Csock::SetupVHost () [inherited]
this is only used on outbound connections, listeners bind in a different spot
bool Csock::SetupVHost () [inherited]
this is only used on outbound connections, listeners bind in a different spot
void Csock::SetWSock (cs_sock_t iSock) [inherited]
Referenced by CExecSock::~CExecSock().
void Csock::SetWSock (cs_sock_t iSock) [inherited]
virtual bool Csock::SNIConfigureClient (CS_STRING & sHostname) [inline, virtual, inherited]
called to configure the SNI client
Parameters:
sHostname,the hostname to configure SNI with, you can fill this with GetHostname() if its a valid hostname and not an OP
Returns:
returning true causes a call to configure SNI with the hostname returned
virtual bool Csock::SNIConfigureClient (CS_STRING & sHostname) [inline, virtual, inherited]
called to configure the SNI client
Parameters:
sHostname,the hostname to configure SNI with, you can fill this with GetHostname() if its a valid hostname and not an OP
Returns:
returning true causes a call to configure SNI with the hostname returned
virtual bool Csock::SNIConfigureServer (const CS_STRING & sHostname, CS_STRING & sPemFile, CS_STRING & sPemPass) [inline, virtual, inherited]
gets called when a SNI request is sent, and used to configure a SNI session
Parameters:
sHostname the hostname sent from the client
sPemFile fill this with the location to the pemfile
sPemPass fill this with the pemfile password if there is one
Returns:
return true to proceed with the SNI server configuration
virtual bool Csock::SNIConfigureServer (const CS_STRING & sHostname, CS_STRING & sPemFile, CS_STRING & sPemPass) [inline, virtual, inherited]
gets called when a SNI request is sent, and used to configure a SNI session
Parameters:
sHostname the hostname sent from the client
sPemFile fill this with the location to the pemfile
sPemPass fill this with the pemfile password if there is one
Returns:
return true to proceed with the SNI server configuration
void CIRCSock::SockError (int iErrno, const CString & sDescription) [override]
virtual void Csock::SockError (int iErrno, const CS_STRING & sDescription) [inline, virtual, inherited]
A sock error occured event.
virtual bool Csock::SSLClientSetup () [virtual, inherited]
This sets up the SSL Client, this is used internally.
virtual bool Csock::SSLClientSetup () [virtual, inherited]
This sets up the SSL Client, this is used internally.
virtual void Csock::SSLFinishSetup (SSL * pSSL) [inline, virtual, inherited]
Gets called immediatly after the m_ssl member is setup and initialized, useful if you need to assign anything to this ssl session via SSL_set_ex_data.
virtual void Csock::SSLFinishSetup (SSL * pSSL) [inline, virtual, inherited]
Gets called immediatly after the m_ssl member is setup and initialized, useful if you need to assign anything to this ssl session via SSL_set_ex_data.
void CZNCSock::SSLHandShakeFinished () [override, virtual, inherited]
called once the SSL handshake is complete, this is triggered via SSL_CB_HANDSHAKE_DONE in SSL_set_info_callback()
This is a spot where you can look at the finished peer certifificate ... IE
 X509 * pCert = GetX509();
 char szName[256];
 memset( szName, '\0', 256 );
 X509_NAME_get_text_by_NID ( X509_get_subject_name( pCert ), NID_commonName, szName, 255 );
 cerr << "Name! " << szName << endl;
 X509_free( pCert );
Reimplemented from Csock.
bool Csock::SslIsEstablished () const [inherited]
is SSL_accept finished ? is the ssl properly finished (from write no error)
bool Csock::SslIsEstablished () const [inherited]
is SSL_accept finished ? is the ssl properly finished (from write no error)
virtual bool Csock::SSLServerSetup () [virtual, inherited]
This sets up the SSL Server, this is used internally.
virtual bool Csock::SSLServerSetup () [virtual, inherited]
This sets up the SSL Server, this is used internally.
bool Csock::StartTLS () [inherited]
start a TLS connection on an existing plain connection
bool Csock::StartTLS () [inherited]
start a TLS connection on an existing plain connection
void CIRCSock::Timeout () [override, virtual]
Sock Timed out event.
Reimplemented from Csock.
void Csock::UnPauseRead () [inherited]
void Csock::UnPauseRead () [inherited]
int CZNCSock::VerifyPeerCertificate (int iPreVerify, X509_STORE_CTX * pStoreCTX) [override, virtual, inherited]
this is hooked in via SSL_set_verify, and be default it just returns 1 meaning success
Parameters:
iPreVerify the pre-verification status as determined by openssl internally
pStoreCTX the X509_STORE_CTX containing the certificate
Returns:
1 to continue, 0 to abort
This may get called multiple times, for example with a chain certificate which is fairly typical with certificates from godaddy, freessl, etc. Additionally, openssl does not do any host verification, they leave that up to the you. One easy way to deal with this is to wait for SSLHandShakeFinished() and examine the peer certificate
See also:
SSLHandShakeFinished
Reimplemented from Csock.
virtual bool Csock::Write (const char * data, size_t len) [virtual, inherited]
Write data to the socket.
If not all of the data is sent, it will be stored on an internal buffer, and tried again with next call to Write if the socket is blocking, it will send everything, its ok to check ernno after this (nothing else is processed)
Parameters:
data the data to send
len the length of data
virtual bool Csock::Write (const char * data, size_t len) [virtual, inherited]
Write data to the socket.
If not all of the data is sent, it will be stored on an internal buffer, and tried again with next call to Write if the socket is blocking, it will send everything, its ok to check ernno after this (nothing else is processed)
Parameters:
data the data to send
len the length of data
virtual bool Csock::Write (const CS_STRING & sData) [virtual, inherited]
Write a text string to the socket.
Encoding is used, if set
Parameters:
sData the string to send; if encoding is provided, sData should be UTF-8 and will be encoded
See also:
Write(const char *, int)
virtual bool Csock::Write (const CS_STRING & sData) [virtual, inherited]
Write a text string to the socket.
Encoding is used, if set
Parameters:
sData the string to send; if encoding is provided, sData should be UTF-8 and will be encoded
See also:
Write(const char *, int)
Friends And Related Function Documentation
friend class CIRCFloodTimer [friend]
Member Data Documentation
bool CIRCSock::m_bAccountNotify [protected]
Referenced by HasAccountNotify().
bool CIRCSock::m_bAuthed [protected]
Referenced by IsAuthed().
bool CIRCSock::m_bAwayNotify [protected]
Referenced by HasAwayNotify().
bool CIRCSock::m_bExtendedJoin [protected]
Referenced by HasExtendedJoin().
bool CIRCSock::m_bFloodProtection [protected]
bool CIRCSock::m_bNamesx [protected]
Referenced by HasNamesx().
bool CIRCSock::m_bServerTime [protected]
Referenced by HasServerTime().
bool CIRCSock::m_bUHNames [protected]
Referenced by HasUHNames().
double CIRCSock::m_fFloodRate [protected]
short int CIRCSock::m_iSendsAllowed [protected]
time_t CIRCSock::m_lastCTCP [protected]
MCString CIRCSock::m_mISupport [protected]
Referenced by GetISupport().
std::map<CString, CChan*> CIRCSock::m_msChans [protected]
std::map<unsigned char, EChanModeArgs> CIRCSock::m_mueChanModes [protected]
Referenced by GetChanModes().
CNick CIRCSock::m_Nick [protected]
Referenced by GetNick(), and GetNickMask().
CIRCNetwork* CIRCSock::m_pNetwork [protected]
Referenced by GetNetwork().
std::set<unsigned char> CIRCSock::m_scUserModes [protected]
Referenced by GetUserModes().
CString CIRCSock::m_sPass [protected]
Referenced by GetPass(), and SetPass().
CString CIRCSock::m_sPermModes [protected]
Referenced by GetPermModes().
CString CIRCSock::m_sPerms [protected]
Referenced by GetPerms().
SCString CIRCSock::m_ssAcceptedCaps [protected]
Referenced by GetAcceptedCaps(), and IsCapAccepted().
SCString CIRCSock::m_ssPendingCaps [protected]
unsigned int CIRCSock::m_uCapPaused [protected]
const unsigned int CIRCSock::m_uCTCPFloodCount [static, protected]
const time_t CIRCSock::m_uCTCPFloodTime [static, protected]
unsigned short int CIRCSock::m_uFloodBurst [protected]
unsigned int CIRCSock::m_uMaxNickLen [protected]
Referenced by GetMaxNickLen().
unsigned int CIRCSock::m_uNumCTCP [protected]
std::vector< CCron * > CSockCommon::m_vcCrons [protected, inherited]
std::vector< CSMonitorFD * > CSockCommon::m_vcMonitorFD [protected, inherited]
std::deque<CString> CIRCSock::m_vsSendQueue [protected]
The documentation for this class was generated from the following file:
IRCSock.h