ZNC: testing::internal::UnorderedElementsAreMatcherImpl< Container > Class Template Reference
testing::internal::UnorderedElementsAreMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef
internal::StlContainerView
< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef
StlContainer::const_iterator StlContainerConstIterator
typedef StlContainer::value_type Element
Public Member Functions
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
template<typename InputIter >
UnorderedElementsAreMatcherImpl (InputIter first, InputIter last)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
Protected Types
typedef ::std::vector< const
MatcherDescriberInterface * > MatcherDescriberVec
Protected Member Functions
void DescribeToImpl (::std::ostream *os) const
void DescribeNegationToImpl (::std::ostream *os) const
bool VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > &element_printouts, const MatchMatrix &matrix, MatchResultListener *listener) const
MatcherDescriberVec & matcher_describers ()
Static Protected Member Functions
static Message Elements (size_t n)
template<typename Container>
class testing::internal::UnorderedElementsAreMatcherImpl< Container >
Member Typedef Documentation
template<typename Container > typedef StlContainer::value_type testing::internal::UnorderedElementsAreMatcherImpl< Container >::Element
typedef ::std::vector<const MatcherDescriberInterface*> testing::internal::UnorderedElementsAreMatcherImplBase::MatcherDescriberVec [protected, inherited]
template<typename Container > typedef View::type testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainer
template<typename Container > typedef StlContainer::const_iterator testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainerConstIterator
template<typename Container > typedef View::const_reference testing::internal::UnorderedElementsAreMatcherImpl< Container >::StlContainerReference
template<typename Container > typedef internal::StlContainerView<RawContainer> testing::internal::UnorderedElementsAreMatcherImpl< Container >::View
Constructor & Destructor Documentation
template<typename Container > template<typename InputIter > testing::internal::UnorderedElementsAreMatcherImpl< Container >::UnorderedElementsAreMatcherImpl (InputIter first, InputIter last) [inline]
References testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers().
Member Function Documentation
template<typename Container > virtual void testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeNegationTo (::std::ostream * os) const [inline, virtual]
Reimplemented from testing::MatcherDescriberInterface.
References testing::internal::UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl().
void testing::internal::UnorderedElementsAreMatcherImplBase::DescribeNegationToImpl (::std::ostream * os) const [protected, inherited]
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeNegationTo().
template<typename Container > virtual void testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeTo (::std::ostream * os) const [inline, virtual]
Implements testing::MatcherDescriberInterface.
References testing::internal::UnorderedElementsAreMatcherImplBase::DescribeToImpl().
void testing::internal::UnorderedElementsAreMatcherImplBase::DescribeToImpl (::std::ostream * os) const [protected, inherited]
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::DescribeTo().
static Message testing::internal::UnorderedElementsAreMatcherImplBase::Elements (size_t n) [inline, static, protected, inherited]
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain().
template<typename Container > typedef testing::internal::UnorderedElementsAreMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container)
template<typename Container > virtual bool testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const [inline, virtual]
Implements testing::MatcherInterface< Container >.
References testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::UnorderedElementsAreMatcherImplBase::Elements(), testing::internal::FindPairing(), testing::MatchResultListener::IsInterested(), testing::internal::MatchMatrix::LhsSize(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
MatcherDescriberVec& testing::internal::UnorderedElementsAreMatcherImplBase::matcher_describers () [inline, protected, inherited]
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::UnorderedElementsAreMatcherImpl().
bool testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > & element_printouts, const MatchMatrix & matrix, MatchResultListener * listener) const [protected, inherited]
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain().
The documentation for this class was generated from the following file:
gmock-matchers.h