ZNC: CZNC Class Reference
CZNC Class Reference
#include <znc.h>
Public Types
enum ConfigState {
ECONFIG_NOTHING, ECONFIG_NEED_REHASH, ECONFIG_NEED_WRITE, ECONFIG_NEED_VERBOSE_WRITE,
ECONFIG_DELAYED_WRITE, ECONFIG_NEED_QUIT
}
typedef std::pair< unsigned long long, unsigned long long > TrafficStatsPair
typedef std::map< CString, TrafficStatsPair > TrafficStatsMap
Public Member Functions
CZNC ()
~CZNC ()
CZNC (const CZNC &)=delete
CZNC & operator= (const CZNC &)=delete
void DeleteUsers ()
void Loop ()
bool WritePidFile (int iPid)
bool DeletePidFile ()
bool WaitForChildLock ()
bool IsHostAllowed (const CString &sHostMask) const
bool AllowConnectionFrom (const CString &sIP) const
void InitDirs (const CString &sArgvPath, const CString &sDataDir)
bool OnBoot ()
CString ExpandConfigPath (const CString &sConfigFile, bool bAllowMkDir=true)
bool WriteNewConfig (const CString &sConfigFile)
bool WriteConfig ()
bool ParseConfig (const CString &sConfig, CString &sError)
bool RehashConfig (CString &sError)
void BackupConfigOnce (const CString &sSuffix)
CString GetUptime () const
void ClearBindHosts ()
bool AddBindHost (const CString &sHost)
bool RemBindHost (const CString &sHost)
void ClearTrustedProxies ()
bool AddTrustedProxy (const CString &sHost)
bool RemTrustedProxy (const CString &sHost)
void Broadcast (const CString &sMessage, bool bAdminOnly=false, CUser *pSkipUser=nullptr, CClient *pSkipClient=nullptr)
void AddBytesRead (unsigned long long u)
void AddBytesWritten (unsigned long long u)
unsigned long long BytesRead () const
unsigned long long BytesWritten () const
TrafficStatsMap GetTrafficStats (TrafficStatsPair &Users, TrafficStatsPair &ZNC, TrafficStatsPair &Total)
TrafficStatsMap GetNetworkTrafficStats (const CString &sUsername, TrafficStatsPair &Total)
void AuthUser (std::shared_ptr< CAuthBase > AuthClass)
void SetConfigState (enum ConfigState e)
void SetSkinName (const CString &s)
void SetStatusPrefix (const CString &s)
void SetMaxBufferSize (unsigned int i)
void SetAnonIPLimit (unsigned int i)
void SetServerThrottle (unsigned int i)
void SetProtectWebSessions (bool b)
void SetHideVersion (bool b)
void SetAuthOnlyViaModule (bool b)
void SetConnectDelay (unsigned int i)
void SetSSLCiphers (const CString &sCiphers)
bool SetSSLProtocols (const CString &sProtocols)
void SetSSLCertFile (const CString &sFile)
void SetConfigWriteDelay (unsigned int i)
enum ConfigState GetConfigState ()
CSockManager & GetManager ()
const CSockManager & GetManager () const
CModules & GetModules ()
CString GetSkinName () const
const CString & GetStatusPrefix () const
const CString & GetCurPath () const
const CString & GetHomePath () const
const CString & GetZNCPath () const
CString GetConfPath (bool bAllowMkDir=true) const
CString GetUserPath () const
CString GetModPath () const
CString GetPemLocation () const
CString GetKeyLocation () const
CString GetDHParamLocation () const
const CString & GetConfigFile () const
bool WritePemFile ()
const VCString & GetBindHosts () const
const VCString & GetTrustedProxies () const
const std::vector< CListener * > & GetListeners () const
time_t TimeStarted () const
unsigned int GetMaxBufferSize () const
unsigned int GetAnonIPLimit () const
unsigned int GetServerThrottle () const
unsigned int GetConnectDelay () const
bool GetProtectWebSessions () const
bool GetHideVersion () const
bool GetAuthOnlyViaModule () const
CString GetSSLCiphers () const
CString GetSSLProtocols () const
Csock::EDisableProtocol GetDisabledSSLProtocols () const
CString GetSSLCertFile () const
unsigned int GetConfigWriteDelay () const
CUser * FindUser (const CString &sUsername)
CModule * FindModule (const CString &sModName, const CString &sUsername)
CModule * FindModule (const CString &sModName, CUser *pUser)
bool UpdateModule (const CString &sModule)
Reload a module everywhere.
bool DeleteUser (const CString &sUsername)
bool AddUser (CUser *pUser, CString &sErrorRet, bool bStartup=false)
const std::map< CString, CUser * > & GetUserMap () const
CListener * FindListener (u_short uPort, const CString &BindHost, EAddrType eAddr)
bool AddListener (CListener *)
bool AddListener (unsigned short uPort, const CString &sBindHost, const CString &sURIPrefix, bool bSSL, EAddrType eAddr, CListener::EAcceptType eAccept, CString &sError)
bool DelListener (CListener *)
void SetMotd (const CString &sMessage)
void AddMotd (const CString &sMessage)
void ClearMotd ()
const VCString & GetMotd () const
void AddServerThrottle (CString sName)
bool GetServerThrottle (CString sName)
void AddNetworkToQueue (CIRCNetwork *pNetwork)
std::list< CIRCNetwork * > & GetConnectionQueue ()
void EnableConnectQueue ()
void DisableConnectQueue ()
void PauseConnectQueue ()
void ResumeConnectQueue ()
void ForceEncoding ()
void UnforceEncoding ()
bool IsForcingEncoding () const
CString FixupEncoding (const CString &sEncoding) const
void LeakConnectQueueTimer (CConnectQueueTimer *pTimer)
void DisableConfigTimer ()
Static Public Member Functions
static CString GetVersion ()
static CString GetTag (bool bIncludeVersion=true, bool bHTML=false)
static CString GetCompileOptionsString ()
static VCString GetAvailableSSLProtocols ()
static void CreateInstance ()
static CZNC & Get ()
static void DestroyInstance ()
static void DumpConfig (const CConfig *Config)
Protected Attributes
time_t m_TimeStarted
enum ConfigState m_eConfigState
std::mutex m_mutexConfigState
std::vector< CListener * > m_vpListeners
std::map< CString, CUser * > m_msUsers
std::map< CString, CUser * > m_msDelUsers
CSockManager m_Manager
CString m_sCurPath
CString m_sZNCPath
CString m_sConfigFile
CString m_sSkinName
CString m_sStatusPrefix
CString m_sPidFile
CString m_sSSLCertFile
CString m_sSSLKeyFile
CString m_sSSLDHParamFile
CString m_sSSLCiphers
CString m_sSSLProtocols
VCString m_vsBindHosts
VCString m_vsTrustedProxies
VCString m_vsMotd
CFile * m_pLockFile
unsigned int m_uiConnectDelay
unsigned int m_uiAnonIPLimit
unsigned int m_uiMaxBufferSize
unsigned int m_uDisabledSSLProtocols
CModules * m_pModules
unsigned long long m_uBytesRead
unsigned long long m_uBytesWritten
std::list< CIRCNetwork * > m_lpConnectQueue
CConnectQueueTimer * m_pConnectQueueTimer
unsigned int m_uiConnectPaused
unsigned int m_uiForceEncoding
TCacheMap< CString > m_sConnectThrottle
bool m_bProtectWebSessions
bool m_bHideVersion
bool m_bAuthOnlyViaModule
CTranslationDomainRefHolder m_Translation
unsigned int m_uiConfigWriteDelay
CConfigWriteTimer * m_pConfigTimer
Static Private Member Functions
static CString t_s (const CString &sEnglish, const CString &sContext="")
static CInlineFormatMessage t_f (const CString &sEnglish, const CString &sContext="")
static CInlineFormatMessage t_p (const CString &sEnglish, const CString &sEnglishes, int iNum, const CString &sContext="")
static CDelayedTranslation t_d (const CString &sEnglish, const CString &sContext="")
Member Typedef Documentation
TrafficStatsMap
typedef std::map<CString, TrafficStatsPair> CZNC::TrafficStatsMap
TrafficStatsPair
typedef std::pair<unsigned long long, unsigned long long> CZNC::TrafficStatsPair
Member Enumeration Documentation
ConfigState
enum CZNC::ConfigState
Enumerator
ECONFIG_NOTHING
ECONFIG_NEED_REHASH
ECONFIG_NEED_WRITE
ECONFIG_NEED_VERBOSE_WRITE
ECONFIG_DELAYED_WRITE
ECONFIG_NEED_QUIT
Constructor & Destructor Documentation
CZNC() [1/2]
CZNC::CZNC ()
~CZNC()
CZNC::~CZNC ()
CZNC() [2/2]
CZNC::CZNC (const CZNC &) delete
Member Function Documentation
AddBindHost()
bool CZNC::AddBindHost (const CString & sHost) inline
Deprecated:
Since 1.7.0.
List of allowed bind hosts was a flawed design.
AddBytesRead()
void CZNC::AddBytesRead (unsigned long long u) inline
References m_uBytesRead.
AddBytesWritten()
void CZNC::AddBytesWritten (unsigned long long u) inline
References m_uBytesWritten.
AddListener() [1/2]
bool CZNC::AddListener (CListener *)
Referenced by GetConnectionQueue(), and GetUserMap().
AddListener() [2/2]
bool CZNC::AddListener (unsigned short uPort, const CString & sBindHost, const CString & sURIPrefix, bool bSSL, EAddrType eAddr, CListener::EAcceptType eAccept, CString & sError)
AddMotd()
void CZNC::AddMotd (const CString & sMessage) inline
References m_vsMotd.
Referenced by SetMotd().
AddNetworkToQueue()
void CZNC::AddNetworkToQueue (CIRCNetwork * pNetwork)
Referenced by GetServerThrottle().
AddServerThrottle()
void CZNC::AddServerThrottle (CString sName) inline
References TCacheMap< K, V >::AddItem(), and m_sConnectThrottle.
AddTrustedProxy()
bool CZNC::AddTrustedProxy (const CString & sHost)
Referenced by RemBindHost().
AddUser()
bool CZNC::AddUser (CUser * pUser, CString & sErrorRet, bool bStartup = false)
Referenced by GetConfigWriteDelay().
AllowConnectionFrom()
bool CZNC::AllowConnectionFrom (const CString & sIP) const
AuthUser()
void CZNC::AuthUser (std::shared_ptr< CAuthBase > AuthClass)
BackupConfigOnce()
void CZNC::BackupConfigOnce (const CString & sSuffix)
Broadcast()
void CZNC::Broadcast (const CString & sMessage, bool bAdminOnly = false, CUser * pSkipUser = nullptr, CClient * pSkipClient = nullptr)
Referenced by RemBindHost().
BytesRead()
unsigned long long CZNC::BytesRead () const inline
References m_uBytesRead.
BytesWritten()
unsigned long long CZNC::BytesWritten () const inline
References m_uBytesWritten.
ClearBindHosts()
void CZNC::ClearBindHosts () inline
Deprecated:
Since 1.7.0.
List of allowed bind hosts was a flawed design.
ClearMotd()
void CZNC::ClearMotd () inline
References m_vsMotd.
Referenced by SetMotd().
ClearTrustedProxies()
void CZNC::ClearTrustedProxies ()
Referenced by RemBindHost().
CreateInstance()
static void CZNC::CreateInstance () static
Referenced by GetConfigWriteDelay().
DeletePidFile()
bool CZNC::DeletePidFile ()
DeleteUser()
bool CZNC::DeleteUser (const CString & sUsername)
Referenced by GetConfigWriteDelay().
DeleteUsers()
void CZNC::DeleteUsers ()
DelListener()
bool CZNC::DelListener (CListener *)
Referenced by GetUserMap().
DestroyInstance()
static void CZNC::DestroyInstance () static
Referenced by GetConfigWriteDelay().
DisableConfigTimer()
void CZNC::DisableConfigTimer ()
Referenced by GetConnectionQueue().
DisableConnectQueue()
void CZNC::DisableConnectQueue ()
Referenced by GetConnectionQueue().
DumpConfig()
static void CZNC::DumpConfig (const CConfig * Config) static
Referenced by GetConnectionQueue().
EnableConnectQueue()
void CZNC::EnableConnectQueue ()
Referenced by GetConnectionQueue().
ExpandConfigPath()
CString CZNC::ExpandConfigPath (const CString & sConfigFile, bool bAllowMkDir = true)
FindListener()
CListener* CZNC::FindListener (u_short uPort, const CString & BindHost, EAddrType eAddr)
Referenced by GetUserMap().
FindModule() [1/2]
CModule* CZNC::FindModule (const CString & sModName, const CString & sUsername)
Referenced by GetConfigWriteDelay().
FindModule() [2/2]
CModule* CZNC::FindModule (const CString & sModName, CUser * pUser)
FindUser()
CUser* CZNC::FindUser (const CString & sUsername)
Referenced by GetConfigWriteDelay().
FixupEncoding()
CString CZNC::FixupEncoding (const CString & sEncoding) const
Referenced by GetConnectionQueue().
ForceEncoding()
void CZNC::ForceEncoding ()
Referenced by GetConnectionQueue().
Get()
static CZNC& CZNC::Get () static
Referenced by GetConfigWriteDelay().
GetAnonIPLimit()
unsigned int CZNC::GetAnonIPLimit () const inline
References m_uiAnonIPLimit.
GetAuthOnlyViaModule()
bool CZNC::GetAuthOnlyViaModule () const inline
References m_bAuthOnlyViaModule.
GetAvailableSSLProtocols()
static VCString CZNC::GetAvailableSSLProtocols () static
Referenced by GetSSLCertFile().
GetBindHosts()
const VCString& CZNC::GetBindHosts () const inline
Deprecated:
Since 1.7.0.
List of allowed bind hosts was a flawed design.
References m_vsBindHosts.
GetCompileOptionsString()
static CString CZNC::GetCompileOptionsString () static
GetConfigFile()
const CString& CZNC::GetConfigFile () const inline
References m_sConfigFile, and WritePemFile().
GetConfigState()
enum ConfigState CZNC::GetConfigState () inline
References m_eConfigState, and m_mutexConfigState.
GetConfigWriteDelay()
unsigned int CZNC::GetConfigWriteDelay () const inline
References AddUser(), CreateInstance(), DeleteUser(), DestroyInstance(), FindModule(), FindUser(), Get(), m_uiConfigWriteDelay, and UpdateModule().
GetConfPath()
CString CZNC::GetConfPath (bool bAllowMkDir = true) const
Referenced by GetStatusPrefix().
GetConnectDelay()
unsigned int CZNC::GetConnectDelay () const inline
References m_uiConnectDelay.
GetConnectionQueue()
std::list<CIRCNetwork*>& CZNC::GetConnectionQueue () inline
References AddListener(), DisableConfigTimer(), DisableConnectQueue(), DumpConfig(), EnableConnectQueue(), FixupEncoding(), ForceEncoding(), IsForcingEncoding(), LeakConnectQueueTimer(), m_lpConnectQueue, PauseConnectQueue(), ResumeConnectQueue(), and UnforceEncoding().
GetCurPath()
const CString& CZNC::GetCurPath () const
Referenced by GetStatusPrefix().
GetDHParamLocation()
CString CZNC::GetDHParamLocation () const
Referenced by GetStatusPrefix().
GetDisabledSSLProtocols()
Csock::EDisableProtocol CZNC::GetDisabledSSLProtocols () const inline
References m_uDisabledSSLProtocols.
GetHideVersion()
bool CZNC::GetHideVersion () const inline
References m_bHideVersion.
GetHomePath()
const CString& CZNC::GetHomePath () const
Referenced by GetStatusPrefix().
GetKeyLocation()
CString CZNC::GetKeyLocation () const
Referenced by GetStatusPrefix().
GetListeners()
const std::vector<CListener*>& CZNC::GetListeners () const inline
References m_vpListeners.
GetManager() [1/2]
CSockManager& CZNC::GetManager () inline
References m_Manager.
GetManager() [2/2]
const CSockManager& CZNC::GetManager () const inline
References m_Manager.
GetMaxBufferSize()
unsigned int CZNC::GetMaxBufferSize () const inline
References m_uiMaxBufferSize.
GetModPath()
CString CZNC::GetModPath () const
Referenced by GetStatusPrefix().
GetModules()
CModules& CZNC::GetModules () inline
References m_pModules.
GetMotd()
const VCString& CZNC::GetMotd () const inline
References m_vsMotd.
GetNetworkTrafficStats()
TrafficStatsMap CZNC::GetNetworkTrafficStats (const CString & sUsername, TrafficStatsPair & Total)
GetPemLocation()
CString CZNC::GetPemLocation () const
Referenced by GetStatusPrefix().
GetProtectWebSessions()
bool CZNC::GetProtectWebSessions () const inline
References m_bProtectWebSessions.
GetServerThrottle() [1/2]
unsigned int CZNC::GetServerThrottle () const inline
References TCacheMap< K, V >::GetTTL(), and m_sConnectThrottle.
GetServerThrottle() [2/2]
bool CZNC::GetServerThrottle (CString sName) inline
References AddNetworkToQueue(), TCacheMap< K, V >::GetItem(), and m_sConnectThrottle.
GetSkinName()
CString CZNC::GetSkinName () const inline
References m_sSkinName.
GetSSLCertFile()
CString CZNC::GetSSLCertFile () const inline
References GetAvailableSSLProtocols(), and m_sSSLCertFile.
GetSSLCiphers()
CString CZNC::GetSSLCiphers () const inline
References m_sSSLCiphers.
GetSSLProtocols()
CString CZNC::GetSSLProtocols () const inline
References m_sSSLProtocols.
GetStatusPrefix()
const CString& CZNC::GetStatusPrefix () const inline
References GetConfPath(), GetCurPath(), GetDHParamLocation(), GetHomePath(), GetKeyLocation(), GetModPath(), GetPemLocation(), GetUserPath(), GetZNCPath(), and m_sStatusPrefix.
GetTag()
static CString CZNC::GetTag (bool bIncludeVersion = true, bool bHTML = false) static
GetTrafficStats()
TrafficStatsMap CZNC::GetTrafficStats (TrafficStatsPair & Users, TrafficStatsPair & ZNC, TrafficStatsPair & Total)
GetTrustedProxies()
const VCString& CZNC::GetTrustedProxies () const inline
References m_vsTrustedProxies.
GetUptime()
CString CZNC::GetUptime () const
GetUserMap()
const std::map<CString, CUser*>& CZNC::GetUserMap () const inline
References AddListener(), DelListener(), FindListener(), and m_msUsers.
GetUserPath()
CString CZNC::GetUserPath () const
Referenced by GetStatusPrefix().
GetVersion()
static CString CZNC::GetVersion () static
GetZNCPath()
const CString& CZNC::GetZNCPath () const
Referenced by GetStatusPrefix().
InitDirs()
void CZNC::InitDirs (const CString & sArgvPath, const CString & sDataDir)
IsForcingEncoding()
bool CZNC::IsForcingEncoding () const
Referenced by GetConnectionQueue().
IsHostAllowed()
bool CZNC::IsHostAllowed (const CString & sHostMask) const
LeakConnectQueueTimer()
void CZNC::LeakConnectQueueTimer (CConnectQueueTimer * pTimer)
Referenced by GetConnectionQueue().
Loop()
void CZNC::Loop ()
OnBoot()
bool CZNC::OnBoot ()
operator=()
CZNC& CZNC::operator= (const CZNC &) delete
ParseConfig()
bool CZNC::ParseConfig (const CString & sConfig, CString & sError)
PauseConnectQueue()
void CZNC::PauseConnectQueue ()
Referenced by GetConnectionQueue().
RehashConfig()
bool CZNC::RehashConfig (CString & sError)
RemBindHost()
bool CZNC::RemBindHost (const CString & sHost) inline
Deprecated:
Since 1.7.0.
List of allowed bind hosts was a flawed design.
References AddTrustedProxy(), Broadcast(), ClearTrustedProxies(), and RemTrustedProxy().
RemTrustedProxy()
bool CZNC::RemTrustedProxy (const CString & sHost)
Referenced by RemBindHost().
ResumeConnectQueue()
void CZNC::ResumeConnectQueue ()
Referenced by GetConnectionQueue().
SetAnonIPLimit()
void CZNC::SetAnonIPLimit (unsigned int i) inline
References m_uiAnonIPLimit.
SetAuthOnlyViaModule()
void CZNC::SetAuthOnlyViaModule (bool b) inline
References m_bAuthOnlyViaModule, and SetConnectDelay().
SetConfigState()
void CZNC::SetConfigState (enum ConfigState e) inline
References m_eConfigState, and m_mutexConfigState.
SetConfigWriteDelay()
void CZNC::SetConfigWriteDelay (unsigned int i) inline
References m_uiConfigWriteDelay.
SetConnectDelay()
void CZNC::SetConnectDelay (unsigned int i)
Referenced by SetAuthOnlyViaModule().
SetHideVersion()
void CZNC::SetHideVersion (bool b) inline
References m_bHideVersion.
SetMaxBufferSize()
void CZNC::SetMaxBufferSize (unsigned int i) inline
References m_uiMaxBufferSize.
SetMotd()
void CZNC::SetMotd (const CString & sMessage) inline
References AddMotd(), and ClearMotd().
SetProtectWebSessions()
void CZNC::SetProtectWebSessions (bool b) inline
References m_bProtectWebSessions.
SetServerThrottle()
void CZNC::SetServerThrottle (unsigned int i) inline
References m_sConnectThrottle, and TCacheMap< K, V >::SetTTL().
SetSkinName()
void CZNC::SetSkinName (const CString & s) inline
References m_sSkinName.
SetSSLCertFile()
void CZNC::SetSSLCertFile (const CString & sFile) inline
References m_sSSLCertFile.
SetSSLCiphers()
void CZNC::SetSSLCiphers (const CString & sCiphers) inline
References m_sSSLCiphers, and SetSSLProtocols().
SetSSLProtocols()
bool CZNC::SetSSLProtocols (const CString & sProtocols)
Referenced by SetSSLCiphers().
SetStatusPrefix()
void CZNC::SetStatusPrefix (const CString & s) inline
References m_sStatusPrefix.
TimeStarted()
time_t CZNC::TimeStarted () const inline
References m_TimeStarted.
UnforceEncoding()
void CZNC::UnforceEncoding ()
Referenced by GetConnectionQueue().
UpdateModule()
bool CZNC::UpdateModule (const CString & sModule)
Reload a module everywhere.
This method will unload a module globally, for a user and for each network. It will then reload them all again.
Parameters
sModule The name of the module to reload
Referenced by GetConfigWriteDelay().
WaitForChildLock()
bool CZNC::WaitForChildLock ()
WriteConfig()
bool CZNC::WriteConfig ()
WriteNewConfig()
bool CZNC::WriteNewConfig (const CString & sConfigFile)
WritePemFile()
bool CZNC::WritePemFile ()
Referenced by GetConfigFile().
WritePidFile()
bool CZNC::WritePidFile (int iPid)
Member Data Documentation
m_bAuthOnlyViaModule
bool CZNC::m_bAuthOnlyViaModule protected
Referenced by GetAuthOnlyViaModule(), and SetAuthOnlyViaModule().
m_bHideVersion
bool CZNC::m_bHideVersion protected
Referenced by GetHideVersion(), and SetHideVersion().
m_bProtectWebSessions
bool CZNC::m_bProtectWebSessions protected
Referenced by GetProtectWebSessions(), and SetProtectWebSessions().
m_eConfigState
enum ConfigState CZNC::m_eConfigState protected
Referenced by GetConfigState(), and SetConfigState().
m_lpConnectQueue
std::list<CIRCNetwork*> CZNC::m_lpConnectQueue protected
Referenced by GetConnectionQueue().
m_Manager
CSockManager CZNC::m_Manager protected
Referenced by GetManager().
m_msDelUsers
std::map<CString, CUser*> CZNC::m_msDelUsers protected
m_msUsers
std::map<CString, CUser*> CZNC::m_msUsers protected
Referenced by GetUserMap().
m_mutexConfigState
std::mutex CZNC::m_mutexConfigState protected
Referenced by GetConfigState(), and SetConfigState().
m_pConfigTimer
CConfigWriteTimer* CZNC::m_pConfigTimer protected
m_pConnectQueueTimer
CConnectQueueTimer* CZNC::m_pConnectQueueTimer protected
m_pLockFile
CFile* CZNC::m_pLockFile protected
m_pModules
CModules* CZNC::m_pModules protected
Referenced by GetModules().
m_sConfigFile
CString CZNC::m_sConfigFile protected
Referenced by GetConfigFile().
m_sConnectThrottle
TCacheMap<CString> CZNC::m_sConnectThrottle protected
Referenced by AddServerThrottle(), GetServerThrottle(), and SetServerThrottle().
m_sCurPath
CString CZNC::m_sCurPath protected
m_sPidFile
CString CZNC::m_sPidFile protected
m_sSkinName
CString CZNC::m_sSkinName protected
Referenced by GetSkinName(), and SetSkinName().
m_sSSLCertFile
CString CZNC::m_sSSLCertFile protected
Referenced by GetSSLCertFile(), and SetSSLCertFile().
m_sSSLCiphers
CString CZNC::m_sSSLCiphers protected
Referenced by GetSSLCiphers(), and SetSSLCiphers().
m_sSSLDHParamFile
CString CZNC::m_sSSLDHParamFile protected
m_sSSLKeyFile
CString CZNC::m_sSSLKeyFile protected
m_sSSLProtocols
CString CZNC::m_sSSLProtocols protected
Referenced by GetSSLProtocols().
m_sStatusPrefix
CString CZNC::m_sStatusPrefix protected
Referenced by GetStatusPrefix(), and SetStatusPrefix().
m_sZNCPath
CString CZNC::m_sZNCPath protected
m_TimeStarted
time_t CZNC::m_TimeStarted protected
Referenced by TimeStarted().
m_Translation
CTranslationDomainRefHolder CZNC::m_Translation protected
m_uBytesRead
unsigned long long CZNC::m_uBytesRead protected
Referenced by AddBytesRead(), and BytesRead().
m_uBytesWritten
unsigned long long CZNC::m_uBytesWritten protected
Referenced by AddBytesWritten(), and BytesWritten().
m_uDisabledSSLProtocols
unsigned int CZNC::m_uDisabledSSLProtocols protected
Referenced by GetDisabledSSLProtocols().
m_uiAnonIPLimit
unsigned int CZNC::m_uiAnonIPLimit protected
Referenced by GetAnonIPLimit(), and SetAnonIPLimit().
m_uiConfigWriteDelay
unsigned int CZNC::m_uiConfigWriteDelay protected
Referenced by GetConfigWriteDelay(), and SetConfigWriteDelay().
m_uiConnectDelay
unsigned int CZNC::m_uiConnectDelay protected
Referenced by GetConnectDelay().
m_uiConnectPaused
unsigned int CZNC::m_uiConnectPaused protected
m_uiForceEncoding
unsigned int CZNC::m_uiForceEncoding protected
m_uiMaxBufferSize
unsigned int CZNC::m_uiMaxBufferSize protected
Referenced by GetMaxBufferSize(), and SetMaxBufferSize().
m_vpListeners
std::vector<CListener*> CZNC::m_vpListeners protected
Referenced by GetListeners().
m_vsBindHosts
VCString CZNC::m_vsBindHosts protected
Referenced by GetBindHosts().
m_vsMotd
VCString CZNC::m_vsMotd protected
Referenced by AddMotd(), ClearMotd(), and GetMotd().
m_vsTrustedProxies
VCString CZNC::m_vsTrustedProxies protected
Referenced by GetTrustedProxies().
The documentation for this class was generated from the following file:
znc.h