ZNC: CTemplateLoopContext Class Reference
CTemplateLoopContext Class Reference
#include <Template.h>
Public Member Functions
CTemplateLoopContext (unsigned long uFilePos, const CString &sLoopName, bool bReverse, std::vector< CTemplate * > *pRows)
virtual ~CTemplateLoopContext ()
CTemplateLoopContext (const CTemplateLoopContext &)=default
CTemplateLoopContext & operator= (const CTemplateLoopContext &)=default
void SetHasData (bool b=true)
void SetName (const CString &s)
void SetRowIndex (unsigned int u)
unsigned int IncRowIndex ()
unsigned int DecRowIndex ()
void SetFilePosition (unsigned int u)
bool HasData () const
const CString & GetName () const
unsigned long GetFilePosition () const
unsigned int GetRowIndex () const
size_t GetRowCount ()
std::vector< CTemplate * > * GetRows ()
CTemplate * GetNextRow ()
CTemplate * GetCurRow ()
CTemplate * GetRow (unsigned int uIndex)
CString GetValue (const CString &sName, bool bFromIf=false)
Constructor & Destructor Documentation
CTemplateLoopContext() [1/2]
CTemplateLoopContext::CTemplateLoopContext (unsigned long uFilePos, const CString & sLoopName, bool bReverse, std::vector< CTemplate * > * pRows) inline
~CTemplateLoopContext()
virtual CTemplateLoopContext::~CTemplateLoopContext () inline virtual
CTemplateLoopContext() [2/2]
CTemplateLoopContext::CTemplateLoopContext (const CTemplateLoopContext &) default
Member Function Documentation
DecRowIndex()
unsigned int CTemplateLoopContext::DecRowIndex () inline
GetCurRow()
CTemplate * CTemplateLoopContext::GetCurRow () inline
References GetRow().
GetFilePosition()
unsigned long CTemplateLoopContext::GetFilePosition () const inline
GetName()
const CString & CTemplateLoopContext::GetName () const inline
GetNextRow()
CTemplate * CTemplateLoopContext::GetNextRow () inline
References GetRow(), and IncRowIndex().
GetRow()
CTemplate * CTemplateLoopContext::GetRow (unsigned int uIndex)
Referenced by GetCurRow(), and GetNextRow().
GetRowCount()
size_t CTemplateLoopContext::GetRowCount () inline
GetRowIndex()
unsigned int CTemplateLoopContext::GetRowIndex () const inline
GetRows()
std::vector< CTemplate * > * CTemplateLoopContext::GetRows () inline
GetValue()
CString CTemplateLoopContext::GetValue (const CString & sName, bool bFromIf = false)
HasData()
bool CTemplateLoopContext::HasData () const inline
IncRowIndex()
unsigned int CTemplateLoopContext::IncRowIndex () inline
Referenced by GetNextRow().
operator=()
CTemplateLoopContext & CTemplateLoopContext::operator= (const CTemplateLoopContext &) default
SetFilePosition()
void CTemplateLoopContext::SetFilePosition (unsigned int u) inline
SetHasData()
void CTemplateLoopContext::SetHasData (bool b = true) inline
SetName()
void CTemplateLoopContext::SetName (const CString & s) inline
SetRowIndex()
void CTemplateLoopContext::SetRowIndex (unsigned int u) inline
The documentation for this class was generated from the following file:
Template.h