ZNC: CModuleJob Class Reference
CModuleJob Class Reference abstract
A CJob version which can be safely used in modules.
#include <Modules.h>
Public Types
enum EJobState { READY, RUNNING, DONE, CANCELLED }
Public Member Functions
CModuleJob (CModule *pModule, const CString &sName, const CString &sDesc)
virtual ~CModuleJob ()
CModuleJob (const CModuleJob &)=delete
CModuleJob & operator= (const CModuleJob &)=delete
CModule * GetModule () const
const CString & GetName () const
const CString & GetDescription () const
virtual void runThread ()=0
This function is called in a separate thread and can do heavy, blocking work.
virtual void runMain ()=0
This function is called from the main thread after runThread() finishes.
bool wasCancelled () const
This can be used to check if the job was cancelled.
Protected Attributes
CModule * m_pModule
const CString m_sName
const CString m_sDescription
Detailed Description
A CJob version which can be safely used in modules.
The job will be cancelled when the module is unloaded.
Member Enumeration Documentation
EJobState
enum CJob::EJobState inherited
Enumerator
READY
RUNNING
DONE
CANCELLED
Constructor & Destructor Documentation
CModuleJob() [1/2]
CModuleJob::CModuleJob (CModule * pModule, const CString & sName, const CString & sDesc) inline
~CModuleJob()
virtual CModuleJob::~CModuleJob () virtual
CModuleJob() [2/2]
CModuleJob::CModuleJob (const CModuleJob &) delete
Member Function Documentation
GetDescription()
const CString& CModuleJob::GetDescription () const inline
GetModule()
CModule* CModuleJob::GetModule () const inline
GetName()
const CString& CModuleJob::GetName () const inline
operator=()
CModuleJob& CModuleJob::operator= (const CModuleJob &) delete
runMain()
virtual void CJob::runMain () pure virtual inherited
This function is called from the main thread after runThread() finishes.
It can be used to handle the results from runThread() without needing synchronization primitives.
Referenced by CJob::~CJob().
runThread()
virtual void CJob::runThread () pure virtual inherited
This function is called in a separate thread and can do heavy, blocking work.
Referenced by CJob::~CJob().
wasCancelled()
bool CJob::wasCancelled () const inherited
This can be used to check if the job was cancelled.
For example, runThread() can return early if this returns true.
Referenced by CJob::~CJob().
Member Data Documentation
m_pModule
CModule* CModuleJob::m_pModule protected
m_sDescription
const CString CModuleJob::m_sDescription protected
m_sName
const CString CModuleJob::m_sName protected
The documentation for this class was generated from the following file:
Modules.h