ZNC: CJob Class Reference
CJob Class Reference abstract
A job is a task which should run without blocking the main thread.
#include <Threads.h>
Public Types
enum EJobState { READY, RUNNING, DONE, CANCELLED }
Public Member Functions
CJob ()
virtual ~CJob ()
Destructor, always called from the main thread.
virtual void runThread ()=0
This function is called in a separate thread and can do heavy, blocking work.
virtual void runMain ()=0
This function is called from the main thread after runThread() finishes.
bool wasCancelled () const
This can be used to check if the job was cancelled.
Friends
class CThreadPool
Detailed Description
A job is a task which should run without blocking the main thread.
You do this by inheriting from this class and implementing the pure virtual methods runThread(), which gets executed in a separate thread and does not block the main thread, and runMain() which gets automatically called from the main thread after runThread() finishes.
After you create a new instance of your class, you can pass it to CThreadPool()::Get().addJob(job) to start it. The thread pool automatically deletes your class after it finished.
For modules you should use CModuleJob instead.
Member Enumeration Documentation
enum CJob::EJobState
Enumerator
READY
RUNNING
DONE
CANCELLED
Constructor & Destructor Documentation
CJob::CJob () inline
Referenced by ~CJob().
virtual CJob::~CJob () inline virtual
Destructor, always called from the main thread.
References CJob(), runMain(), runThread(), and wasCancelled().
Member Function Documentation
virtual void CJob::runMain () pure virtual
This function is called from the main thread after runThread() finishes.
It can be used to handle the results from runThread() without needing synchronization primitives.
Referenced by ~CJob().
virtual void CJob::runThread () pure virtual
This function is called in a separate thread and can do heavy, blocking work.
Referenced by ~CJob().
bool CJob::wasCancelled () const
This can be used to check if the job was cancelled.
For example, runThread() can return early if this returns true.
Referenced by ~CJob().
Friends And Related Function Documentation
friend class CThreadPool friend
The documentation for this class was generated from the following file:
Threads.h