ZNC: CMessage Class Reference
CMessage Class Reference
Here is a small explanation of how messages on IRC work, and how you can use this class to get useful information from the parsed message.
#include <Message.h>
Public Types
enum Type {
Type::Unknown, Type::Account, Type::Action, Type::Away,
Type::Capability, Type::CTCP, Type::Error, Type::Invite,
Type::Join, Type::Kick, Type::Mode, Type::Nick,
Type::Notice, Type::Numeric, Type::Part, Type::Ping,
Type::Pong, Type::Quit, Type::Text, Type::Topic,
Type::Wallops
}
enum FormatFlags { IncludeAll = 0x0, ExcludePrefix = 0x1, ExcludeTags = 0x2 }
Public Member Functions
CMessage (const CString &sMessage="")
CMessage (const CNick &Nick, const CString &sCommand, const VCString &vsParams=VCString(), const MCString &mssTags=MCString::EmptyMap)
Type GetType () const
bool Equals (const CMessage &Other) const
void Clone (const CMessage &Other)
CIRCNetwork * GetNetwork () const
void SetNetwork (CIRCNetwork *pNetwork)
CClient * GetClient () const
void SetClient (CClient *pClient)
CChan * GetChan () const
void SetChan (CChan *pChan)
CNick & GetNick ()
const CNick & GetNick () const
void SetNick (const CNick &Nick)
const CString & GetCommand () const
void SetCommand (const CString &sCommand)
const VCString & GetParams () const
void SetParams (const VCString &vsParams)
CString GetParams (unsigned int uIdx, unsigned int uLen=-1) const ZNC_MSG_DEPRECATED("Use GetParamsColon() instead")
CString GetParamsColon (unsigned int uIdx, unsigned int uLen=-1) const
CString GetParam (unsigned int uIdx) const
void SetParam (unsigned int uIdx, const CString &sParam)
const timeval & GetTime () const
void SetTime (const timeval &ts)
const MCString & GetTags () const
void SetTags (const MCString &mssTags)
CString GetTag (const CString &sKey) const
void SetTag (const CString &sKey, const CString &sValue)
CString ToString (unsigned int uFlags=IncludeAll) const
void Parse (CString sMessage)
template<typename M >
M & As () ZNC_LVREFQUAL
template<typename M >
const M & As () const ZNC_LVREFQUAL
template<typename M , typename = typename std::enable_if< std::is_base_of<CMessage, M>{}>::type>
operator M & () ZNC_LVREFQUAL
template<typename M , typename = typename std::enable_if< std::is_base_of<CMessage, M>{}>::type>
operator const M & () const ZNC_LVREFQUAL
Detailed Description
Here is a small explanation of how messages on IRC work, and how you can use this class to get useful information from the parsed message.
The output varies greatly and this advice may not apply to every message type, but this will hopefully help you understand how it works more accurately.
=some-tag :server.network.net 366 something #channel :End of /NAMES list. tags nick cmd 0 1 2
tags is the IRCv3 tags associated with the message, obtained with GetTag("t"). the tag can also be obtained with GetTime(), some messages have other tags with them. Tags may not always be present. Refer to IRCv3 for documentation on tags.
nick is the sender, which can be obtained with GetNick()
cmd is command, which is obtained via GetCommand()
0, 1, ... are parameters, available via GetParam(n), which removes the leading colon (:). If you don't want to remove the colon, use GetParamsColon().
For certain events, like a PRIVMSG, convienience commands like GetChan() and GetNick() are available, this is not true for all CMessage extensions.
Member Enumeration Documentation
enum CMessage::FormatFlags
Enumerator
IncludeAll
ExcludePrefix
ExcludeTags
enum CMessage::Type strong
Enumerator
Unknown
Account
Action
Away
Capability
CTCP
Error
Invite
Join
Kick
Mode
Nick
Notice
Numeric
Part
Ping
Pong
Quit
Text
Topic
Wallops
Constructor & Destructor Documentation
CMessage::CMessage (const CString & sMessage = "") explicit
CMessage::CMessage (const CNick & Nick, const CString & sCommand, const VCString & vsParams = VCString(), const MCString & mssTags = MCString::EmptyMap)
Member Function Documentation
template<typename M > M& CMessage::As () inline
template<typename M > const M& CMessage::As () const inline
void CMessage::Clone (const CMessage & Other)
Referenced by GetType().
bool CMessage::Equals (const CMessage & Other) const
Referenced by CBufLine::Equals(), and GetType().
CChan* CMessage::GetChan () const inline
CClient* CMessage::GetClient () const inline
const CString& CMessage::GetCommand () const inline
References SetCommand().
Referenced by CNumericMessage::GetCode(), CBufLine::GetCommand(), and CCTCPMessage::IsReply().
CIRCNetwork* CMessage::GetNetwork () const inline
CNick& CMessage::GetNick () inline
Referenced by CNickMessage::GetOldNick().
const CNick& CMessage::GetNick () const inline
CString CMessage::GetParam (unsigned int uIdx) const
Referenced by CJoinMessage::GetKey(), CKickMessage::GetKickedNick(), CNickMessage::GetNewNick(), GetParams(), CKickMessage::GetReason(), CPartMessage::GetReason(), CQuitMessage::GetReason(), CTargetMessage::GetTarget(), CActionMessage::GetText(), CCTCPMessage::GetText(), CNoticeMessage::GetText(), CTextMessage::GetText(), and CTopicMessage::GetTopic().
const VCString& CMessage::GetParams () const inline
References SetParams().
CString CMessage::GetParams (unsigned int uIdx, unsigned int uLen = -1) const inline
Deprecated:
use GetParamsColon() instead.
References GetParam(), GetParamsColon(), and SetParam().
CString CMessage::GetParamsColon (unsigned int uIdx, unsigned int uLen = -1) const
Referenced by CModeMessage::GetModes(), and GetParams().
CString CMessage::GetTag (const CString & sKey) const
Referenced by SetTags().
const MCString& CMessage::GetTags () const inline
Referenced by CBufLine::GetTags().
const timeval& CMessage::GetTime () const inline
Referenced by CBufLine::GetTime().
Type CMessage::GetType () const inline
References Clone(), and Equals().
template<typename M , typename = typename std::enable_if< std::is_base_of<CMessage, M>{}>::type> CMessage::operator const M & () const inline
template<typename M , typename = typename std::enable_if< std::is_base_of<CMessage, M>{}>::type> CMessage::operator M & () inline
void CMessage::Parse (CString sMessage)
Referenced by CBufLine::SetFormat().
void CMessage::SetChan (CChan * pChan) inline
void CMessage::SetClient (CClient * pClient) inline
void CMessage::SetCommand (const CString & sCommand)
Referenced by GetCommand().
void CMessage::SetNetwork (CIRCNetwork * pNetwork) inline
void CMessage::SetNick (const CNick & Nick) inline
References Nick.
void CMessage::SetParam (unsigned int uIdx, const CString & sParam)
Referenced by GetParams(), CJoinMessage::SetKey(), CKickMessage::SetKickedNick(), CNickMessage::SetNewNick(), CKickMessage::SetReason(), CPartMessage::SetReason(), CQuitMessage::SetReason(), CTargetMessage::SetTarget(), CActionMessage::SetText(), CCTCPMessage::SetText(), CNoticeMessage::SetText(), CTextMessage::SetText(), and CTopicMessage::SetTopic().
void CMessage::SetParams (const VCString & vsParams)
Referenced by GetParams().
void CMessage::SetTag (const CString & sKey, const CString & sValue)
Referenced by SetTags().
void CMessage::SetTags (const MCString & mssTags) inline
References GetTag(), and SetTag().
Referenced by CBufLine::SetTags().
void CMessage::SetTime (const timeval & ts) inline
Referenced by CBufLine::SetTime().
CString CMessage::ToString (unsigned int uFlags = IncludeAll) const
Referenced by CBufLine::GetFormat().
The documentation for this class was generated from the following file:
Message.h