ZNC: CIRCNetwork Class Reference
CIRCNetwork Class Reference
#include <IRCNetwork.h>
Public Member Functions
CIRCNetwork (CUser *pUser, const CString &sName)
CIRCNetwork (CUser *pUser, const CIRCNetwork &Network)
~CIRCNetwork ()
CIRCNetwork (const CIRCNetwork &)=delete
CIRCNetwork & operator= (const CIRCNetwork &)=delete
void Clone (const CIRCNetwork &Network, bool bCloneName=true)
CString GetNetworkPath () const
void DelServers ()
bool ParseConfig (CConfig *pConfig, CString &sError, bool bUpgrade=false)
CConfig ToConfig () const
void BounceAllClients ()
bool IsUserAttached () const
bool IsUserOnline () const
void ClientConnected (CClient *pClient)
void ClientDisconnected (CClient *pClient)
CUser * GetUser () const
const CString & GetName () const
bool IsNetworkAttached () const
const std::vector< CClient * > & GetClients () const
std::vector< CClient * > FindClients (const CString &sIdentifier) const
void SetUser (CUser *pUser)
bool SetName (const CString &sName)
CModules & GetModules ()
const CModules & GetModules () const
bool PutUser (const CString &sLine, CClient *pClient=nullptr, CClient *pSkipClient=nullptr)
bool PutUser (const CMessage &Message, CClient *pClient=nullptr, CClient *pSkipClient=nullptr)
bool PutStatus (const CString &sLine, CClient *pClient=nullptr, CClient *pSkipClient=nullptr)
bool PutModule (const CString &sModule, const CString &sLine, CClient *pClient=nullptr, CClient *pSkipClient=nullptr)
const std::vector< CChan * > & GetChans () const
CChan * FindChan (CString sName) const
std::vector< CChan * > FindChans (const CString &sWild) const
bool AddChan (CChan *pChan)
bool AddChan (const CString &sName, bool bInConfig)
bool DelChan (const CString &sName)
void JoinChans ()
void JoinChans (std::set< CChan *> &sChans)
const std::vector< CQuery * > & GetQueries () const
CQuery * FindQuery (const CString &sName) const
std::vector< CQuery * > FindQueries (const CString &sWild) const
CQuery * AddQuery (const CString &sName)
bool DelQuery (const CString &sName)
const CString & GetChanPrefixes () const
void SetChanPrefixes (const CString &s)
bool IsChan (const CString &sChan) const
const std::vector< CServer * > & GetServers () const
bool HasServers () const
CServer * FindServer (const CString &sName) const
bool DelServer (const CString &sName, unsigned short uPort, const CString &sPass)
bool AddServer (const CString &sName)
bool AddServer (const CString &sName, unsigned short uPort, const CString &sPass="", bool bSSL=false)
CServer * GetNextServer (bool bAdvance=true)
CServer * GetCurrentServer () const
void SetIRCServer (const CString &s)
bool SetNextServer (const CServer *pServer)
bool IsLastServer () const
const SCString & GetTrustedFingerprints () const
void AddTrustedFingerprint (const CString &sFP)
void DelTrustedFingerprint (const CString &sFP)
void ClearTrustedFingerprints ()
void SetIRCConnectEnabled (bool b)
bool GetIRCConnectEnabled () const
CIRCSock * GetIRCSock ()
const CIRCSock * GetIRCSock () const
const CString & GetIRCServer () const
const CNick & GetIRCNick () const
void SetIRCNick (const CNick &n)
CString GetCurNick () const
bool IsIRCAway () const
void SetIRCAway (bool b)
bool Connect ()
bool IsIRCConnected () const
This method will return whether the user is connected and authenticated to an IRC server.
void SetIRCSocket (CIRCSock *pIRCSock)
void IRCConnected ()
void IRCDisconnected ()
void CheckIRCConnect ()
bool PutIRC (const CString &sLine)
bool PutIRC (const CMessage &Message)
void AddRawBuffer (const CMessage &Format, const CString &sText="")
void UpdateRawBuffer (const CString &sCommand, const CMessage &Format, const CString &sText="")
void UpdateExactRawBuffer (const CMessage &Format, const CString &sText="")
void ClearRawBuffer ()
void AddRawBuffer (const CString &sFormat, const CString &sText="")
void UpdateRawBuffer (const CString &sMatch, const CString &sFormat, const CString &sText="")
void UpdateExactRawBuffer (const CString &sFormat, const CString &sText="")
void AddMotdBuffer (const CMessage &Format, const CString &sText="")
void UpdateMotdBuffer (const CString &sCommand, const CMessage &Format, const CString &sText="")
void ClearMotdBuffer ()
void AddMotdBuffer (const CString &sFormat, const CString &sText="")
void UpdateMotdBuffer (const CString &sMatch, const CString &sFormat, const CString &sText="")
void AddNoticeBuffer (const CMessage &Format, const CString &sText="")
void UpdateNoticeBuffer (const CString &sCommand, const CMessage &Format, const CString &sText="")
void ClearNoticeBuffer ()
void AddNoticeBuffer (const CString &sFormat, const CString &sText="")
void UpdateNoticeBuffer (const CString &sMatch, const CString &sFormat, const CString &sText="")
void ClearQueryBuffer ()
const CString & GetNick (const bool bAllowDefault=true) const
const CString & GetAltNick (const bool bAllowDefault=true) const
const CString & GetIdent (const bool bAllowDefault=true) const
CString GetRealName () const
const CString & GetBindHost () const
const CString & GetEncoding () const
CString GetQuitMsg () const
void SetNick (const CString &s)
void SetAltNick (const CString &s)
void SetIdent (const CString &s)
void SetRealName (const CString &s)
void SetBindHost (const CString &s)
void SetEncoding (const CString &s)
void SetQuitMsg (const CString &s)
double GetFloodRate () const
unsigned short int GetFloodBurst () const
void SetFloodRate (double fFloodRate)
void SetFloodBurst (unsigned short int uFloodBurst)
unsigned short int GetJoinDelay () const
void SetJoinDelay (unsigned short int uJoinDelay)
void SetTrustAllCerts (const bool bTrustAll=false)
bool GetTrustAllCerts () const
void SetTrustPKI (const bool bTrustPKI=true)
bool GetTrustPKI () const
unsigned long long BytesRead () const
unsigned long long BytesWritten () const
void AddBytesRead (unsigned long long u)
void AddBytesWritten (unsigned long long u)
CString ExpandString (const CString &sStr) const
CString & ExpandString (const CString &sStr, CString &sRet) const
Static Public Member Functions
static bool IsValidNetwork (const CString &sNetwork)
Protected Attributes
CString m_sName
CUser * m_pUser
CString m_sNick
CString m_sAltNick
CString m_sIdent
CString m_sRealName
CString m_sBindHost
CString m_sEncoding
CString m_sQuitMsg
SCString m_ssTrustedFingerprints
CModules * m_pModules
std::vector< CClient * > m_vClients
CIRCSock * m_pIRCSock
std::vector< CChan * > m_vChans
std::vector< CQuery * > m_vQueries
CString m_sChanPrefixes
bool m_bIRCConnectEnabled
bool m_bTrustAllCerts
bool m_bTrustPKI
CString m_sIRCServer
std::vector< CServer * > m_vServers
size_t m_uServerIdx
Index in m_vServers of our current server + 1.
CNick m_IRCNick
bool m_bIRCAway
double m_fFloodRate
Set to -1 to disable protection.
unsigned short int m_uFloodBurst
CBuffer m_RawBuffer
CBuffer m_MotdBuffer
CBuffer m_NoticeBuffer
CIRCNetworkPingTimer * m_pPingTimer
CIRCNetworkJoinTimer * m_pJoinTimer
unsigned short int m_uJoinDelay
unsigned long long m_uBytesRead
unsigned long long m_uBytesWritten
Static Private Member Functions
static CString t_s (const CString &sEnglish, const CString &sContext="")
static CInlineFormatMessage t_f (const CString &sEnglish, const CString &sContext="")
static CInlineFormatMessage t_p (const CString &sEnglish, const CString &sEnglishes, int iNum, const CString &sContext="")
static CDelayedTranslation t_d (const CString &sEnglish, const CString &sContext="")
Constructor & Destructor Documentation
CIRCNetwork() [1/3]
CIRCNetwork::CIRCNetwork (CUser * pUser, const CString & sName)
CIRCNetwork() [2/3]
CIRCNetwork::CIRCNetwork (CUser * pUser, const CIRCNetwork & Network)
~CIRCNetwork()
CIRCNetwork::~CIRCNetwork ()
CIRCNetwork() [3/3]
CIRCNetwork::CIRCNetwork (const CIRCNetwork &) delete
Member Function Documentation
AddBytesRead()
void CIRCNetwork::AddBytesRead (unsigned long long u) inline
References m_uBytesRead.
AddBytesWritten()
void CIRCNetwork::AddBytesWritten (unsigned long long u) inline
References ExpandString(), and m_uBytesWritten.
AddChan() [1/2]
bool CIRCNetwork::AddChan (CChan * pChan)
Referenced by GetModules().
AddChan() [2/2]
bool CIRCNetwork::AddChan (const CString & sName, bool bInConfig)
AddMotdBuffer() [1/2]
void CIRCNetwork::AddMotdBuffer (const CMessage & Format, const CString & sText = "") inline
References CBuffer::AddLine(), and m_MotdBuffer.
AddMotdBuffer() [2/2]
void CIRCNetwork::AddMotdBuffer (const CString & sFormat, const CString & sText = "") inline
Deprecated:
References CBuffer::AddLine(), and m_MotdBuffer.
AddNoticeBuffer() [1/2]
void CIRCNetwork::AddNoticeBuffer (const CMessage & Format, const CString & sText = "") inline
References CBuffer::AddLine(), and m_NoticeBuffer.
AddNoticeBuffer() [2/2]
void CIRCNetwork::AddNoticeBuffer (const CString & sFormat, const CString & sText = "") inline
Deprecated:
References CBuffer::AddLine(), and m_NoticeBuffer.
AddQuery()
CQuery* CIRCNetwork::AddQuery (const CString & sName)
Referenced by GetModules().
AddRawBuffer() [1/2]
void CIRCNetwork::AddRawBuffer (const CMessage & Format, const CString & sText = "") inline
References CBuffer::AddLine(), and m_RawBuffer.
AddRawBuffer() [2/2]
void CIRCNetwork::AddRawBuffer (const CString & sFormat, const CString & sText = "") inline
Deprecated:
References CBuffer::AddLine(), and m_RawBuffer.
AddServer() [1/2]
bool CIRCNetwork::AddServer (const CString & sName)
Referenced by HasServers().
AddServer() [2/2]
bool CIRCNetwork::AddServer (const CString & sName, unsigned short uPort, const CString & sPass = "", bool bSSL = false)
AddTrustedFingerprint()
void CIRCNetwork::AddTrustedFingerprint (const CString & sFP) inline
References CString::EHEXCOLON, CString::Escape_n(), and m_ssTrustedFingerprints.
BounceAllClients()
void CIRCNetwork::BounceAllClients ()
BytesRead()
unsigned long long CIRCNetwork::BytesRead () const inline
References m_uBytesRead.
BytesWritten()
unsigned long long CIRCNetwork::BytesWritten () const inline
References m_uBytesWritten.
CheckIRCConnect()
void CIRCNetwork::CheckIRCConnect ()
Referenced by SetIRCAway().
ClearMotdBuffer()
void CIRCNetwork::ClearMotdBuffer () inline
References CBuffer::Clear(), and m_MotdBuffer.
ClearNoticeBuffer()
void CIRCNetwork::ClearNoticeBuffer () inline
References CBuffer::Clear(), and m_NoticeBuffer.
ClearQueryBuffer()
void CIRCNetwork::ClearQueryBuffer ()
Referenced by UpdateNoticeBuffer().
ClearRawBuffer()
void CIRCNetwork::ClearRawBuffer () inline
References CBuffer::Clear(), and m_RawBuffer.
ClearTrustedFingerprints()
void CIRCNetwork::ClearTrustedFingerprints () inline
References m_ssTrustedFingerprints, and SetIRCConnectEnabled().
ClientConnected()
void CIRCNetwork::ClientConnected (CClient * pClient)
Referenced by IsUserAttached().
ClientDisconnected()
void CIRCNetwork::ClientDisconnected (CClient * pClient)
Referenced by IsUserAttached().
Clone()
void CIRCNetwork::Clone (const CIRCNetwork & Network, bool bCloneName = true)
Connect()
bool CIRCNetwork::Connect ()
Referenced by SetIRCAway().
DelChan()
bool CIRCNetwork::DelChan (const CString & sName)
Referenced by GetModules().
DelQuery()
bool CIRCNetwork::DelQuery (const CString & sName)
Referenced by GetModules().
DelServer()
bool CIRCNetwork::DelServer (const CString & sName, unsigned short uPort, const CString & sPass)
Referenced by HasServers().
DelServers()
void CIRCNetwork::DelServers ()
DelTrustedFingerprint()
void CIRCNetwork::DelTrustedFingerprint (const CString & sFP) inline
References m_ssTrustedFingerprints.
ExpandString() [1/2]
CString CIRCNetwork::ExpandString (const CString & sStr) const
Referenced by AddBytesWritten().
ExpandString() [2/2]
CString& CIRCNetwork::ExpandString (const CString & sStr, CString & sRet) const
FindChan()
CChan* CIRCNetwork::FindChan (CString sName) const
Referenced by GetModules().
FindChans()
std::vector<CChan*> CIRCNetwork::FindChans (const CString & sWild) const
Referenced by GetModules().
FindClients()
std::vector<CClient*> CIRCNetwork::FindClients (const CString & sIdentifier) const
Referenced by GetClients().
FindQueries()
std::vector<CQuery*> CIRCNetwork::FindQueries (const CString & sWild) const
Referenced by GetModules().
FindQuery()
CQuery* CIRCNetwork::FindQuery (const CString & sName) const
Referenced by GetModules().
FindServer()
CServer* CIRCNetwork::FindServer (const CString & sName) const
Referenced by HasServers().
GetAltNick()
const CString& CIRCNetwork::GetAltNick (const bool bAllowDefault = true) const
Referenced by UpdateNoticeBuffer().
GetBindHost()
const CString& CIRCNetwork::GetBindHost () const
Referenced by UpdateNoticeBuffer().
GetChanPrefixes()
const CString& CIRCNetwork::GetChanPrefixes () const inline
References m_sChanPrefixes.
GetChans()
const std::vector<CChan*>& CIRCNetwork::GetChans () const
Referenced by GetModules().
GetClients()
const std::vector<CClient*>& CIRCNetwork::GetClients () const inline
References FindClients(), m_vClients, SetName(), and SetUser().
GetCurNick()
CString CIRCNetwork::GetCurNick () const
Referenced by GetIRCSock().
GetCurrentServer()
CServer* CIRCNetwork::GetCurrentServer () const
Referenced by HasServers().
GetEncoding()
const CString& CIRCNetwork::GetEncoding () const
Referenced by UpdateNoticeBuffer().
GetFloodBurst()
unsigned short int CIRCNetwork::GetFloodBurst () const inline
References m_uFloodBurst.
GetFloodRate()
double CIRCNetwork::GetFloodRate () const inline
References m_fFloodRate.
GetIdent()
const CString& CIRCNetwork::GetIdent (const bool bAllowDefault = true) const
Referenced by UpdateNoticeBuffer().
GetIRCConnectEnabled()
bool CIRCNetwork::GetIRCConnectEnabled () const inline
References m_bIRCConnectEnabled.
GetIRCNick()
const CNick& CIRCNetwork::GetIRCNick () const
Referenced by GetIRCSock().
GetIRCServer()
const CString& CIRCNetwork::GetIRCServer () const
Referenced by GetIRCSock().
GetIRCSock() [1/2]
CIRCSock* CIRCNetwork::GetIRCSock () inline
References m_pIRCSock.
GetIRCSock() [2/2]
const CIRCSock* CIRCNetwork::GetIRCSock () const inline
References GetCurNick(), GetIRCNick(), GetIRCServer(), m_pIRCSock, and SetIRCNick().
GetJoinDelay()
unsigned short int CIRCNetwork::GetJoinDelay () const inline
References m_uJoinDelay.
GetModules() [1/2]
CModules& CIRCNetwork::GetModules () inline
References m_pModules.
GetModules() [2/2]
const CModules& CIRCNetwork::GetModules () const inline
References AddChan(), AddQuery(), DelChan(), DelQuery(), FindChan(), FindChans(), FindQueries(), FindQuery(), GetChans(), GetQueries(), JoinChans(), m_pModules, PutModule(), PutStatus(), and PutUser().
GetName()
const CString& CIRCNetwork::GetName () const
Referenced by IsUserAttached().
GetNetworkPath()
CString CIRCNetwork::GetNetworkPath () const
GetNextServer()
CServer* CIRCNetwork::GetNextServer (bool bAdvance = true)
Referenced by HasServers().
GetNick()
const CString& CIRCNetwork::GetNick (const bool bAllowDefault = true) const
Referenced by UpdateNoticeBuffer().
GetQueries()
const std::vector<CQuery*>& CIRCNetwork::GetQueries () const
Referenced by GetModules().
GetQuitMsg()
CString CIRCNetwork::GetQuitMsg () const
Referenced by UpdateNoticeBuffer().
GetRealName()
CString CIRCNetwork::GetRealName () const
Referenced by UpdateNoticeBuffer().
GetServers()
const std::vector<CServer*>& CIRCNetwork::GetServers () const
Referenced by SetChanPrefixes().
GetTrustAllCerts()
bool CIRCNetwork::GetTrustAllCerts () const inline
References m_bTrustAllCerts.
GetTrustedFingerprints()
const SCString& CIRCNetwork::GetTrustedFingerprints () const inline
References m_ssTrustedFingerprints.
GetTrustPKI()
bool CIRCNetwork::GetTrustPKI () const inline
References m_bTrustPKI.
GetUser()
CUser* CIRCNetwork::GetUser () const
Referenced by IsUserAttached().
HasServers()
bool CIRCNetwork::HasServers () const inline
References AddServer(), DelServer(), FindServer(), GetCurrentServer(), GetNextServer(), IsLastServer(), m_vServers, SetIRCServer(), and SetNextServer().
IRCConnected()
void CIRCNetwork::IRCConnected ()
Referenced by SetIRCAway().
IRCDisconnected()
void CIRCNetwork::IRCDisconnected ()
Referenced by SetIRCAway().
IsChan()
bool CIRCNetwork::IsChan (const CString & sChan) const
Referenced by SetChanPrefixes().
IsIRCAway()
bool CIRCNetwork::IsIRCAway () const inline
References m_bIRCAway.
IsIRCConnected()
bool CIRCNetwork::IsIRCConnected () const
This method will return whether the user is connected and authenticated to an IRC server.
Referenced by SetIRCAway().
IsLastServer()
bool CIRCNetwork::IsLastServer () const
Referenced by HasServers().
IsNetworkAttached()
bool CIRCNetwork::IsNetworkAttached () const inline
References m_vClients.
IsUserAttached()
bool CIRCNetwork::IsUserAttached () const inline
References ClientConnected(), ClientDisconnected(), GetName(), GetUser(), IsUserOnline(), and m_vClients.
IsUserOnline()
bool CIRCNetwork::IsUserOnline () const
Referenced by IsUserAttached().
IsValidNetwork()
static bool CIRCNetwork::IsValidNetwork (const CString & sNetwork) static
JoinChans() [1/2]
void CIRCNetwork::JoinChans ()
Referenced by GetModules().
JoinChans() [2/2]
void CIRCNetwork::JoinChans (std::set< CChan *> & sChans)
operator=()
CIRCNetwork& CIRCNetwork::operator= (const CIRCNetwork &) delete
ParseConfig()
bool CIRCNetwork::ParseConfig (CConfig * pConfig, CString & sError, bool bUpgrade = false)
PutIRC() [1/2]
bool CIRCNetwork::PutIRC (const CString & sLine)
Referenced by SetIRCAway().
PutIRC() [2/2]
bool CIRCNetwork::PutIRC (const CMessage & Message)
PutModule()
bool CIRCNetwork::PutModule (const CString & sModule, const CString & sLine, CClient * pClient = nullptr, CClient * pSkipClient = nullptr)
Referenced by GetModules().
PutStatus()
bool CIRCNetwork::PutStatus (const CString & sLine, CClient * pClient = nullptr, CClient * pSkipClient = nullptr)
Referenced by GetModules().
PutUser() [1/2]
bool CIRCNetwork::PutUser (const CString & sLine, CClient * pClient = nullptr, CClient * pSkipClient = nullptr)
Referenced by GetModules().
PutUser() [2/2]
bool CIRCNetwork::PutUser (const CMessage & Message, CClient * pClient = nullptr, CClient * pSkipClient = nullptr)
SetAltNick()
void CIRCNetwork::SetAltNick (const CString & s)
Referenced by UpdateNoticeBuffer().
SetBindHost()
void CIRCNetwork::SetBindHost (const CString & s)
Referenced by UpdateNoticeBuffer().
SetChanPrefixes()
void CIRCNetwork::SetChanPrefixes (const CString & s) inline
References GetServers(), IsChan(), and m_sChanPrefixes.
SetEncoding()
void CIRCNetwork::SetEncoding (const CString & s)
Referenced by UpdateNoticeBuffer().
SetFloodBurst()
void CIRCNetwork::SetFloodBurst (unsigned short int uFloodBurst) inline
References m_uFloodBurst.
SetFloodRate()
void CIRCNetwork::SetFloodRate (double fFloodRate) inline
References m_fFloodRate.
SetIdent()
void CIRCNetwork::SetIdent (const CString & s)
Referenced by UpdateNoticeBuffer().
SetIRCAway()
void CIRCNetwork::SetIRCAway (bool b) inline
References CheckIRCConnect(), Connect(), IRCConnected(), IRCDisconnected(), IsIRCConnected(), m_bIRCAway, PutIRC(), and SetIRCSocket().
SetIRCConnectEnabled()
void CIRCNetwork::SetIRCConnectEnabled (bool b)
Referenced by ClearTrustedFingerprints().
SetIRCNick()
void CIRCNetwork::SetIRCNick (const CNick & n)
Referenced by GetIRCSock().
SetIRCServer()
void CIRCNetwork::SetIRCServer (const CString & s)
Referenced by HasServers().
SetIRCSocket()
void CIRCNetwork::SetIRCSocket (CIRCSock * pIRCSock)
Referenced by SetIRCAway().
SetJoinDelay()
void CIRCNetwork::SetJoinDelay (unsigned short int uJoinDelay) inline
References m_uJoinDelay.
SetName()
bool CIRCNetwork::SetName (const CString & sName)
Referenced by GetClients().
SetNextServer()
bool CIRCNetwork::SetNextServer (const CServer * pServer)
Referenced by HasServers().
SetNick()
void CIRCNetwork::SetNick (const CString & s)
Referenced by UpdateNoticeBuffer().
SetQuitMsg()
void CIRCNetwork::SetQuitMsg (const CString & s)
Referenced by UpdateNoticeBuffer().
SetRealName()
void CIRCNetwork::SetRealName (const CString & s)
Referenced by UpdateNoticeBuffer().
SetTrustAllCerts()
void CIRCNetwork::SetTrustAllCerts (const bool bTrustAll = false) inline
References m_bTrustAllCerts.
SetTrustPKI()
void CIRCNetwork::SetTrustPKI (const bool bTrustPKI = true) inline
References m_bTrustPKI.
SetUser()
void CIRCNetwork::SetUser (CUser * pUser)
Referenced by GetClients().
ToConfig()
CConfig CIRCNetwork::ToConfig () const
UpdateExactRawBuffer() [1/2]
void CIRCNetwork::UpdateExactRawBuffer (const CMessage & Format, const CString & sText = "") inline
References m_RawBuffer, and CBuffer::UpdateExactLine().
UpdateExactRawBuffer() [2/2]
void CIRCNetwork::UpdateExactRawBuffer (const CString & sFormat, const CString & sText = "") inline
Deprecated:
References m_RawBuffer, and CBuffer::UpdateExactLine().
UpdateMotdBuffer() [1/2]
void CIRCNetwork::UpdateMotdBuffer (const CString & sCommand, const CMessage & Format, const CString & sText = "") inline
References m_MotdBuffer, and CBuffer::UpdateLine().
UpdateMotdBuffer() [2/2]
void CIRCNetwork::UpdateMotdBuffer (const CString & sMatch, const CString & sFormat, const CString & sText = "") inline
Deprecated:
References m_MotdBuffer, and CBuffer::UpdateLine().
UpdateNoticeBuffer() [1/2]
void CIRCNetwork::UpdateNoticeBuffer (const CString & sCommand, const CMessage & Format, const CString & sText = "") inline
References m_NoticeBuffer, and CBuffer::UpdateLine().
UpdateNoticeBuffer() [2/2]
void CIRCNetwork::UpdateNoticeBuffer (const CString & sMatch, const CString & sFormat, const CString & sText = "") inline
Deprecated:
References ClearQueryBuffer(), GetAltNick(), GetBindHost(), GetEncoding(), GetIdent(), GetNick(), GetQuitMsg(), GetRealName(), m_NoticeBuffer, SetAltNick(), SetBindHost(), SetEncoding(), SetIdent(), SetNick(), SetQuitMsg(), SetRealName(), and CBuffer::UpdateLine().
UpdateRawBuffer() [1/2]
void CIRCNetwork::UpdateRawBuffer (const CString & sCommand, const CMessage & Format, const CString & sText = "") inline
References m_RawBuffer, and CBuffer::UpdateLine().
UpdateRawBuffer() [2/2]
void CIRCNetwork::UpdateRawBuffer (const CString & sMatch, const CString & sFormat, const CString & sText = "") inline
Deprecated:
References m_RawBuffer, and CBuffer::UpdateLine().
Member Data Documentation
m_bIRCAway
bool CIRCNetwork::m_bIRCAway protected
Referenced by IsIRCAway(), and SetIRCAway().
m_bIRCConnectEnabled
bool CIRCNetwork::m_bIRCConnectEnabled protected
Referenced by GetIRCConnectEnabled().
m_bTrustAllCerts
bool CIRCNetwork::m_bTrustAllCerts protected
Referenced by GetTrustAllCerts(), and SetTrustAllCerts().
m_bTrustPKI
bool CIRCNetwork::m_bTrustPKI protected
Referenced by GetTrustPKI(), and SetTrustPKI().
m_fFloodRate
double CIRCNetwork::m_fFloodRate protected
Set to -1 to disable protection.
Referenced by GetFloodRate(), and SetFloodRate().
m_IRCNick
CNick CIRCNetwork::m_IRCNick protected
m_MotdBuffer
CBuffer CIRCNetwork::m_MotdBuffer protected
Referenced by AddMotdBuffer(), ClearMotdBuffer(), and UpdateMotdBuffer().
m_NoticeBuffer
CBuffer CIRCNetwork::m_NoticeBuffer protected
Referenced by AddNoticeBuffer(), ClearNoticeBuffer(), and UpdateNoticeBuffer().
m_pIRCSock
CIRCSock* CIRCNetwork::m_pIRCSock protected
Referenced by GetIRCSock().
m_pJoinTimer
CIRCNetworkJoinTimer* CIRCNetwork::m_pJoinTimer protected
m_pModules
CModules* CIRCNetwork::m_pModules protected
Referenced by GetModules().
m_pPingTimer
CIRCNetworkPingTimer* CIRCNetwork::m_pPingTimer protected
m_pUser
CUser* CIRCNetwork::m_pUser protected
m_RawBuffer
CBuffer CIRCNetwork::m_RawBuffer protected
Referenced by AddRawBuffer(), ClearRawBuffer(), UpdateExactRawBuffer(), and UpdateRawBuffer().
m_sAltNick
CString CIRCNetwork::m_sAltNick protected
m_sBindHost
CString CIRCNetwork::m_sBindHost protected
m_sChanPrefixes
CString CIRCNetwork::m_sChanPrefixes protected
Referenced by GetChanPrefixes(), and SetChanPrefixes().
m_sEncoding
CString CIRCNetwork::m_sEncoding protected
m_sIdent
CString CIRCNetwork::m_sIdent protected
m_sIRCServer
CString CIRCNetwork::m_sIRCServer protected
m_sName
CString CIRCNetwork::m_sName protected
m_sNick
CString CIRCNetwork::m_sNick protected
m_sQuitMsg
CString CIRCNetwork::m_sQuitMsg protected
m_sRealName
CString CIRCNetwork::m_sRealName protected
m_ssTrustedFingerprints
SCString CIRCNetwork::m_ssTrustedFingerprints protected
Referenced by AddTrustedFingerprint(), ClearTrustedFingerprints(), DelTrustedFingerprint(), and GetTrustedFingerprints().
m_uBytesRead
unsigned long long CIRCNetwork::m_uBytesRead protected
Referenced by AddBytesRead(), and BytesRead().
m_uBytesWritten
unsigned long long CIRCNetwork::m_uBytesWritten protected
Referenced by AddBytesWritten(), and BytesWritten().
m_uFloodBurst
unsigned short int CIRCNetwork::m_uFloodBurst protected
Referenced by GetFloodBurst(), and SetFloodBurst().
m_uJoinDelay
unsigned short int CIRCNetwork::m_uJoinDelay protected
Referenced by GetJoinDelay(), and SetJoinDelay().
m_uServerIdx
size_t CIRCNetwork::m_uServerIdx protected
Index in m_vServers of our current server + 1.
m_vChans
std::vector<CChan*> CIRCNetwork::m_vChans protected
m_vClients
std::vector<CClient*> CIRCNetwork::m_vClients protected
Referenced by GetClients(), IsNetworkAttached(), and IsUserAttached().
m_vQueries
std::vector<CQuery*> CIRCNetwork::m_vQueries protected
m_vServers
std::vector<CServer*> CIRCNetwork::m_vServers protected
Referenced by HasServers().
The documentation for this class was generated from the following file:
IRCNetwork.h