ZNC: CTargetMessage Class Reference
CTargetMessage Class Reference
#include <Message.h>
Public Types
enum Type {
Unknown, Account, Action, Away,
Capability, CTCP, Error, Invite,
Join, Kick, Mode, Nick,
Notice, Numeric, Part, Ping,
Pong, Quit, Text, Topic,
Wallops
}
enum FormatFlags { IncludeAll = 0x0, ExcludePrefix = 0x1, ExcludeTags = 0x2 }
Public Member Functions
CString GetTarget () const
void SetTarget (const CString &sTarget)
Type GetType () const
void Clone (const CMessage &Other)
CIRCNetwork * GetNetwork () const
void SetNetwork (CIRCNetwork *pNetwork)
CClient * GetClient () const
void SetClient (CClient *pClient)
CChan * GetChan () const
void SetChan (CChan *pChan)
CNick & GetNick ()
const CNick & GetNick () const
void SetNick (const CNick &Nick)
const CString & GetCommand () const
void SetCommand (const CString &sCommand)
const VCString & GetParams () const
CString GetParams (unsigned int uIdx, unsigned int uLen=-1) const
void SetParams (const VCString &vsParams)
CString GetParam (unsigned int uIdx) const
void SetParam (unsigned int uIdx, const CString &sParam)
const timeval & GetTime () const
void SetTime (const timeval &ts)
const MCString & GetTags () const
void SetTags (const MCString &mssTags)
CString GetTag (const CString &sKey) const
void SetTag (const CString &sKey, const CString &sValue)
CString ToString (unsigned int uFlags=IncludeAll) const
void Parse (CString sMessage)
Member Enumeration Documentation
enum CMessage::FormatFlags [inherited]
Enumerator:
IncludeAll
ExcludePrefix
ExcludeTags
enum CMessage::Type [inherited]
Enumerator:
Unknown
Account
Action
Away
Capability
CTCP
Error
Invite
Join
Kick
Mode
Nick
Notice
Numeric
Part
Ping
Pong
Quit
Text
Topic
Wallops
Member Function Documentation
void CMessage::Clone (const CMessage & Other) [inherited]
CChan* CMessage::GetChan () const [inline, inherited]
CClient* CMessage::GetClient () const [inline, inherited]
const CString& CMessage::GetCommand () const [inline, inherited]
Referenced by CNumericMessage::GetCode(), and CCTCPMessage::IsReply().
CIRCNetwork* CMessage::GetNetwork () const [inline, inherited]
CNick& CMessage::GetNick () [inline, inherited]
Referenced by CNickMessage::GetOldNick().
const CNick& CMessage::GetNick () const [inline, inherited]
CString CMessage::GetParam (unsigned int uIdx) const [inherited]
Referenced by CJoinMessage::GetKey(), CKickMessage::GetKickedNick(), CNickMessage::GetNewNick(), CKickMessage::GetReason(), CPartMessage::GetReason(), CQuitMessage::GetReason(), GetTarget(), CActionMessage::GetText(), CCTCPMessage::GetText(), CNoticeMessage::GetText(), CTextMessage::GetText(), and CTopicMessage::GetTopic().
const VCString& CMessage::GetParams () const [inline, inherited]
Referenced by CModeMessage::GetModes().
CString CMessage::GetParams (unsigned int uIdx, unsigned int uLen = -1) const [inherited]
CString CMessage::GetTag (const CString & sKey) const [inherited]
const MCString& CMessage::GetTags () const [inline, inherited]
Referenced by CBufLine::GetTags().
CString CTargetMessage::GetTarget () const [inline]
References CMessage::GetParam().
const timeval& CMessage::GetTime () const [inline, inherited]
Referenced by CBufLine::GetTime().
Type CMessage::GetType () const [inline, inherited]
void CMessage::Parse (CString sMessage) [inherited]
Referenced by CBufLine::SetFormat().
void CMessage::SetChan (CChan * pChan) [inline, inherited]
void CMessage::SetClient (CClient * pClient) [inline, inherited]
void CMessage::SetCommand (const CString & sCommand) [inherited]
void CMessage::SetNetwork (CIRCNetwork * pNetwork) [inline, inherited]
void CMessage::SetNick (const CNick & Nick) [inline, inherited]
References CMessage::Nick.
void CMessage::SetParam (unsigned int uIdx, const CString & sParam) [inherited]
Referenced by CJoinMessage::SetKey(), CKickMessage::SetKickedNick(), CNickMessage::SetNewNick(), CKickMessage::SetReason(), CPartMessage::SetReason(), CQuitMessage::SetReason(), SetTarget(), CActionMessage::SetText(), CCTCPMessage::SetText(), CNoticeMessage::SetText(), CTextMessage::SetText(), and CTopicMessage::SetTopic().
void CMessage::SetParams (const VCString & vsParams) [inherited]
void CMessage::SetTag (const CString & sKey, const CString & sValue) [inherited]
void CMessage::SetTags (const MCString & mssTags) [inline, inherited]
Referenced by CBufLine::SetTags().
void CTargetMessage::SetTarget (const CString & sTarget) [inline]
References CMessage::SetParam().
void CMessage::SetTime (const timeval & ts) [inline, inherited]
Referenced by CBufLine::SetTime().
CString CMessage::ToString (unsigned int uFlags = IncludeAll) const [inherited]
Referenced by CBufLine::GetFormat().
The documentation for this class was generated from the following file:
Message.h