ZNC: CKickMessage Class Reference
CKickMessage Class Reference
#include <Message.h>
Public Types
enum class Type {
Unknown , Account , Action , Away ,
Capability , CTCP , Error , Invite ,
Join , Kick , Mode , Nick ,
Notice , Numeric , Part , Ping ,
Pong , Quit , Text , Topic ,
Wallops
}
enum FormatFlags { IncludeAll = 0x0 , ExcludePrefix = 0x1 , ExcludeTags = 0x2 }
Public Member Functions
CString GetKickedNick () const
void SetKickedNick (const CString &sNick)
CString GetReason () const
void SetReason (const CString &sReason)
CString GetText () const
void SetText (const CString &sText)
CString GetTarget () const
void SetTarget (const CString &sTarget)
Type GetType () const
bool Equals (const CMessage &Other) const
void Clone (const CMessage &Other)
CIRCNetwork * GetNetwork () const
void SetNetwork (CIRCNetwork *pNetwork)
CClient * GetClient () const
void SetClient (CClient *pClient)
CChan * GetChan () const
void SetChan (CChan *pChan)
CNick & GetNick ()
const CNick & GetNick () const
void SetNick (const CNick &Nick)
const CString & GetCommand () const
void SetCommand (const CString &sCommand)
const VCString & GetParams () const
CString GetParams (unsigned int uIdx, unsigned int uLen=-1) const ZNC_MSG_DEPRECATED("Use GetParamsColon() instead")
VCString GetParamsSplit (unsigned int uIdx, unsigned int uLen=-1) const
Get a subset of the message parameters.
void SetParams (const VCString &vsParams)
CString GetParamsColon (unsigned int uIdx, unsigned int uLen=-1) const
CString GetParam (unsigned int uIdx) const
void SetParam (unsigned int uIdx, const CString &sParam)
const timeval & GetTime () const
void SetTime (const timeval &ts)
const MCString & GetTags () const
void SetTags (const MCString &mssTags)
CString GetTag (const CString &sKey) const
void SetTag (const CString &sKey, const CString &sValue)
CString ToString (unsigned int uFlags=IncludeAll) const
void Parse (const CString &sMessage)
template<typename M >
M & As () ZNC_LVREFQUAL
template<typename M >
const M & As () const ZNC_LVREFQUAL
template<typename M , typename = typename std::enable_if< std::is_base_of<CMessage, M>{}>::type>
operator M& () ZNC_LVREFQUAL
template<typename M , typename = typename std::enable_if< std::is_base_of<CMessage, M>{}>::type>
operator const M & () const ZNC_LVREFQUAL
Member Enumeration Documentation
FormatFlags
enum CMessage::FormatFlags inherited
Enumerator
IncludeAll
ExcludePrefix
ExcludeTags
Type
enum CMessage::Type strong inherited
Enumerator
Unknown
Account
Action
Away
Capability
CTCP
Error
Invite
Join
Kick
Mode
Nick
Notice
Numeric
Part
Ping
Pong
Quit
Text
Topic
Wallops
Member Function Documentation
As() [1/2]
template<typename M > const M& CMessage::As () const inline inherited
As() [2/2]
template<typename M > M& CMessage::As () inline inherited
Clone()
void CMessage::Clone (const CMessage & Other) inherited
Equals()
bool CMessage::Equals (const CMessage & Other) const inherited
Referenced by CBufLine::Equals().
GetChan()
CChan* CMessage::GetChan () const inline inherited
GetClient()
CClient* CMessage::GetClient () const inline inherited
GetCommand()
const CString& CMessage::GetCommand () const inline inherited
Referenced by CNumericMessage::GetCode(), CBufLine::GetCommand(), and CCTCPMessage::IsReply().
GetKickedNick()
CString CKickMessage::GetKickedNick () const inline
References CMessage::GetParam().
GetNetwork()
CIRCNetwork* CMessage::GetNetwork () const inline inherited
GetNick() [1/2]
CNick& CMessage::GetNick () inline inherited
Referenced by CNickMessage::GetOldNick().
GetNick() [2/2]
const CNick& CMessage::GetNick () const inline inherited
GetParam()
CString CMessage::GetParam (unsigned int uIdx) const inherited
Referenced by CJoinMessage::GetKey(), GetKickedNick(), CModeMessage::GetModeList(), CNickMessage::GetNewNick(), GetReason(), CPartMessage::GetReason(), CQuitMessage::GetReason(), CTargetMessage::GetTarget(), CActionMessage::GetText(), CCTCPMessage::GetText(), CNoticeMessage::GetText(), CTextMessage::GetText(), and CTopicMessage::GetTopic().
GetParams() [1/2]
const VCString& CMessage::GetParams () const inline inherited
GetParams() [2/2]
CString CMessage::GetParams (unsigned int uIdx, unsigned int uLen = -1) const inline inherited
Deprecated:
use GetParamsColon() instead.
References CMessage::GetParamsColon().
GetParamsColon()
CString CMessage::GetParamsColon (unsigned int uIdx, unsigned int uLen = -1) const inherited
Referenced by CModeMessage::GetModes(), and CMessage::GetParams().
GetParamsSplit()
VCString CMessage::GetParamsSplit (unsigned int uIdx, unsigned int uLen = -1) const inherited
Get a subset of the message parameters.
This allows accessing a vector of a specific range of parameters, allowing easy inline use, such as pChan->SetModes(Message.GetParam(2), Message.GetParamsSplit(3));
Parameters
uIdx The index of the first parameter to retrieve
uLen How many parameters to retrieve
Returns
A VCString containing the retrieved parameters
Referenced by CModeMessage::GetModeParams().
GetReason()
CString CKickMessage::GetReason () const inline
References CMessage::GetParam().
Referenced by GetText().
GetTag()
CString CMessage::GetTag (const CString & sKey) const inherited
GetTags()
const MCString& CMessage::GetTags () const inline inherited
Referenced by CBufLine::GetTags().
GetTarget()
CString CTargetMessage::GetTarget () const inline inherited
References CMessage::GetParam().
GetText()
CString CKickMessage::GetText () const inline
References GetReason().
GetTime()
const timeval& CMessage::GetTime () const inline inherited
Referenced by CBufLine::GetTime().
GetType()
Type CMessage::GetType () const inline inherited
operator const M &()
template<typename M , typename = typename std::enable_if< std::is_base_of<CMessage, M>{}>::type> CMessage::operator const M & () const inline inherited
operator M&()
template<typename M , typename = typename std::enable_if< std::is_base_of<CMessage, M>{}>::type> CMessage::operator M& () inline inherited
Parse()
void CMessage::Parse (const CString & sMessage) inherited
Referenced by CBufLine::SetFormat().
SetChan()
void CMessage::SetChan (CChan * pChan) inline inherited
SetClient()
void CMessage::SetClient (CClient * pClient) inline inherited
SetCommand()
void CMessage::SetCommand (const CString & sCommand) inherited
SetKickedNick()
void CKickMessage::SetKickedNick (const CString & sNick) inline
References CMessage::SetParam().
SetNetwork()
void CMessage::SetNetwork (CIRCNetwork * pNetwork) inline inherited
SetNick()
void CMessage::SetNick (const CNick & Nick) inline inherited
SetParam()
void CMessage::SetParam (unsigned int uIdx, const CString & sParam) inherited
Referenced by CJoinMessage::SetKey(), SetKickedNick(), CNickMessage::SetNewNick(), SetReason(), CPartMessage::SetReason(), CQuitMessage::SetReason(), CTargetMessage::SetTarget(), CActionMessage::SetText(), CCTCPMessage::SetText(), CNoticeMessage::SetText(), CTextMessage::SetText(), and CTopicMessage::SetTopic().
SetParams()
void CMessage::SetParams (const VCString & vsParams) inherited
SetReason()
void CKickMessage::SetReason (const CString & sReason) inline
References CMessage::SetParam().
Referenced by SetText().
SetTag()
void CMessage::SetTag (const CString & sKey, const CString & sValue) inherited
SetTags()
void CMessage::SetTags (const MCString & mssTags) inline inherited
Referenced by CBufLine::SetTags().
SetTarget()
void CTargetMessage::SetTarget (const CString & sTarget) inline inherited
References CMessage::SetParam().
SetText()
void CKickMessage::SetText (const CString & sText) inline
References SetReason().
SetTime()
void CMessage::SetTime (const timeval & ts) inline inherited
Referenced by CBufLine::SetTime().
ToString()
CString CMessage::ToString (unsigned int uFlags = IncludeAll) const inherited
Referenced by CBufLine::GetFormat().
The documentation for this class was generated from the following file:
Message.h