ZNC: testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container > Class Template Reference
testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef
internal::StlContainerView
< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> ContainerView
typedef
ContainerView::type::size_type SizeType
Public Member Functions
Impl (const SizeMatcher &size_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
template<typename SizeMatcher>
template<typename Container>
class testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >
Member Typedef Documentation
template<typename SizeMatcher > template<typename Container > typedef internal::StlContainerView< GTEST_REMOVE_REFERENCE_AND_CONST_(Container)> testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::ContainerView
template<typename SizeMatcher > template<typename Container > typedef ContainerView::type::size_type testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::SizeType
Constructor & Destructor Documentation
template<typename SizeMatcher > template<typename Container > testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::Impl (const SizeMatcher & size_matcher) [inline, explicit]
Member Function Documentation
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeNegationTo (::std::ostream * os) const [inline, virtual]
Reimplemented from testing::MatcherDescriberInterface.
References testing::internal::MatcherBase< T >::DescribeNegationTo().
template<typename SizeMatcher > template<typename Container > virtual void testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::DescribeTo (::std::ostream * os) const [inline, virtual]
Implements testing::MatcherDescriberInterface.
References testing::internal::MatcherBase< T >::DescribeTo().
template<typename SizeMatcher > template<typename Container > virtual bool testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const [inline, virtual]
Implements testing::MatcherInterface< Container >.
References testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
The documentation for this class was generated from the following file:
gmock-matchers.h