ZNC: testing::internal::ContainsMatcherImpl< Container > Class Template Reference
testing::internal::ContainsMatcherImpl< Container > Class Template Reference
#include <gmock-matchers.h>
Public Types
typedef StlContainerView
< RawContainer > View
typedef View::type StlContainer
typedef View::const_reference StlContainerReference
typedef StlContainer::value_type Element
Public Member Functions
template<typename InnerMatcher >
ContainsMatcherImpl (InnerMatcher inner_matcher)
virtual void DescribeTo (::std::ostream *os) const
virtual void DescribeNegationTo (::std::ostream *os) const
virtual bool MatchAndExplain (Container container, MatchResultListener *listener) const
typedef GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) RawContainer
bool MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener *listener) const
Protected Member Functions
GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl)
Protected Attributes
const Matcher< const Element & > inner_matcher_
template<typename Container>
class testing::internal::ContainsMatcherImpl< Container >
Member Typedef Documentation
template<typename Container > typedef StlContainer::value_type testing::internal::QuantifierMatcherImpl< Container >::Element [inherited]
template<typename Container > typedef View::type testing::internal::QuantifierMatcherImpl< Container >::StlContainer [inherited]
template<typename Container > typedef View::const_reference testing::internal::QuantifierMatcherImpl< Container >::StlContainerReference [inherited]
template<typename Container > typedef StlContainerView<RawContainer> testing::internal::QuantifierMatcherImpl< Container >::View [inherited]
Constructor & Destructor Documentation
template<typename Container > template<typename InnerMatcher > testing::internal::ContainsMatcherImpl< Container >::ContainsMatcherImpl (InnerMatcher inner_matcher) [inline, explicit]
Member Function Documentation
template<typename Container > virtual void testing::internal::ContainsMatcherImpl< Container >::DescribeNegationTo (::std::ostream * os) const [inline, virtual]
Reimplemented from testing::MatcherDescriberInterface.
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_.
template<typename Container > virtual void testing::internal::ContainsMatcherImpl< Container >::DescribeTo (::std::ostream * os) const [inline, virtual]
Implements testing::MatcherDescriberInterface.
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_.
template<typename Container > testing::internal::QuantifierMatcherImpl< Container >::GTEST_DISALLOW_ASSIGN_ (QuantifierMatcherImpl< Container >) [protected, inherited]
template<typename Container > typedef testing::internal::QuantifierMatcherImpl< Container >::GTEST_REMOVE_REFERENCE_AND_CONST_ (Container) [inherited]
template<typename Container > virtual bool testing::internal::ContainsMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const [inline, virtual]
Implements testing::MatcherInterface< Container >.
References testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl().
template<typename Container > bool testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener * listener) const [inline, inherited]
References testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_, testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
Referenced by testing::internal::ContainsMatcherImpl< Container >::MatchAndExplain(), and testing::internal::EachMatcherImpl< Container >::MatchAndExplain().
Member Data Documentation
template<typename Container > const Matcher<const Element&> testing::internal::QuantifierMatcherImpl< Container >::inner_matcher_ [protected, inherited]
Referenced by testing::internal::ContainsMatcherImpl< Container >::DescribeNegationTo(), testing::internal::EachMatcherImpl< Container >::DescribeNegationTo(), testing::internal::ContainsMatcherImpl< Container >::DescribeTo(), testing::internal::EachMatcherImpl< Container >::DescribeTo(), and testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl().
The documentation for this class was generated from the following file:
gmock-matchers.h