ZNC: testing::internal::WhenDynamicCastToMatcher< To & > Class Template Reference
testing::internal::WhenDynamicCastToMatcher< To & > Class Template Reference
#include <gmock-matchers.h>
Public Member Functions
WhenDynamicCastToMatcher (const Matcher< To & > &matcher)
template<typename From >
bool MatchAndExplain (From &from, MatchResultListener *listener) const
void DescribeTo (::std::ostream *os) const
void DescribeNegationTo (::std::ostream *os) const
Static Protected Member Functions
static string GetToName ()
Protected Attributes
const Matcher< To & > matcher_
template<typename To>
class testing::internal::WhenDynamicCastToMatcher< To & >
Constructor & Destructor Documentation
template<typename To > testing::internal::WhenDynamicCastToMatcher< To & >::WhenDynamicCastToMatcher (const Matcher< To & > & matcher) [inline, explicit]
Member Function Documentation
void testing::internal::WhenDynamicCastToMatcherBase< To & >::DescribeNegationTo (::std::ostream * os) const [inline, inherited]
References testing::internal::MatcherBase< T >::DescribeNegationTo(), and testing::internal::WhenDynamicCastToMatcherBase< To >::matcher_.
void testing::internal::WhenDynamicCastToMatcherBase< To & >::DescribeTo (::std::ostream * os) const [inline, inherited]
References testing::internal::MatcherBase< T >::DescribeTo(), and testing::internal::WhenDynamicCastToMatcherBase< To >::matcher_.
static string testing::internal::WhenDynamicCastToMatcherBase< To & >::GetToName () [inline, static, protected, inherited]
template<typename To > template<typename From > bool testing::internal::WhenDynamicCastToMatcher< To & >::MatchAndExplain (From & from, MatchResultListener * listener) const [inline]
References testing::internal::MatchPrintAndExplain().
Member Data Documentation
const Matcher<To & > testing::internal::WhenDynamicCastToMatcherBase< To & >::matcher_ [protected, inherited]
The documentation for this class was generated from the following file:
gmock-matchers.h