ZNC: CWebSock Class Reference
CWebSock Class Reference
#include <WebModules.h>
Public Types
enum EPageReqResult { PAGE_NOTFOUND , PAGE_PRINT , PAGE_DEFERRED , PAGE_DONE }
enum ETConn { OUTBOUND = 0 , LISTENER = 1 , INBOUND = 2 }
enum EFRead {
READ_EOF = 0 , READ_ERR = -1 , READ_EAGAIN = -2 , READ_CONNREFUSED = -3 ,
READ_TIMEDOUT = -4
}
enum EFSelect { SEL_OK = 0 , SEL_TIMEOUT = -1 , SEL_EAGAIN = -2 , SEL_ERR = -3 }
enum ESSLMethod {
TLS = 0 , SSL23 = TLS , SSL2 = 2 , SSL3 = 3 ,
TLS1 = 4 , TLS11 = 5 , TLS12 = 6
}
enum EDisableProtocol {
EDP_None = 0 , EDP_SSLv2 = 1 , EDP_SSLv3 = 2 , EDP_TLSv1 = 4 ,
EDP_TLSv1_1 = 8 , EDP_TLSv1_2 = 16 , EDP_SSL = (EDP_SSLv2|EDP_SSLv3)
}
enum ECONState {
CST_START = 0 , CST_DNS = CST_START , CST_BINDVHOST = 1 , CST_DESTDNS = 2 ,
CST_CONNECT = 3 , CST_CONNECTSSL = 4 , CST_OK = 5
}
enum ECloseType { CLT_DONT = 0 , CLT_NOW = 1 , CLT_AFTERWRITE = 2 , CLT_DEREFERENCE = 3 }
enum { TMO_READ = 1 , TMO_WRITE = 2 , TMO_ACCEPT = 4 , TMO_ALL = TMO_READ|TMO_WRITE|TMO_ACCEPT }
this timeout isn't just connection timeout, but also timeout on NOT recieving data, to disable this set it to 0 then the normal TCP timeout will apply (basically TCP will kill a dead connection) Set the timeout, set to 0 to never timeout
enum EDNSLType { DNS_VHOST , DNS_DEST }
Public Member Functions
CWebSock (const CString &sURIPrefix)
virtual ~CWebSock ()
bool ForceLogin () override
bool OnLogin (const CString &sUser, const CString &sPass, bool bBasic) override
void OnPageRequest (const CString &sURI) override
EPageReqResult PrintTemplate (const CString &sPageName, CString &sPageRet, CModule *pModule=nullptr)
EPageReqResult PrintStaticFile (const CString &sPath, CString &sPageRet, CModule *pModule=nullptr)
CString FindTmpl (CModule *pModule, const CString &sName)
void PrintErrorPage (const CString &sMessage)
std::shared_ptr< CWebSession > GetSession ()
Csock * GetSockObj (const CString &sHost, unsigned short uPort) override
void GetAvailSkins (VCString &vRet) const
CString GetSkinName ()
CString GetRequestCookie (const CString &sKey)
bool SendCookie (const CString &sKey, const CString &sValue)
CString GetCSRFCheck ()
bool ValidateCSRFCheck (const CString &sURI)
void ReadData (const char *data, size_t len) override
Ready to read data event.
void ReadLine (const CString &sData) override
virtual void ReadLine (const CS_STRING &sLine)
Ready to Read a full line event.
void Connected () override
Connected event.
virtual Csock * GetSockObj (const CS_STRING &sHostname, uint16_t iPort)
override this for accept sockets
virtual bool PrintFile (const CString &sFileName, CString sContentType="")
void CheckPost ()
bool SentHeader () const
bool PrintHeader (off_t uContentLength, const CString &sContentType="", unsigned int uStatusId=200, const CString &sStatusMsg="OK")
void AddHeader (const CString &sName, const CString &sValue)
void SetContentType (const CString &sContentType)
bool PrintNotFound ()
bool Redirect (const CString &sURL)
void ParseURI ()
void GetPage ()
CString GetRemoteIP () const override
CString GetRequestCookie (const CString &sKey) const
void SetDocRoot (const CString &s)
void SetLoggedIn (bool b)
CString GetPath () const
bool IsLoggedIn () const
const CString & GetDocRoot () const
const CString & GetUser () const
const CString & GetPass () const
const CString & GetParamString () const
const CString & GetContentType () const
const CString & GetURI () const
const CString & GetURIPrefix () const
bool IsPost () const
CString GetParam (const CString &sName, bool bPost=true, const CString &sFilter="\r\n") const
CString GetRawParam (const CString &sName, bool bPost=true) const
bool HasParam (const CString &sName, bool bPost=true) const
const std::map< CString, VCString > & GetParams (bool bPost=true) const
size_t GetParamValues (const CString &sName, VCString &vsRet, bool bPost=true, const CString &sFilter="\r\n") const
size_t GetParamValues (const CString &sName, std::set< CString > &ssRet, bool bPost=true, const CString &sFilter="\r\n") const
void ReachedMaxBuffer () override
This defaults to closing the socket, feel free to override.
void SockError (int iErrno, const CString &sDescription) override
virtual void SockError (int iErrno, const CS_STRING &sDescription)
A sock error occured event.
bool ConnectionFrom (const CString &sHost, unsigned short uPort) override
This limits the global connections from this IP to defeat DoS attacks, feel free to override. The ACL used is provided by the main interface.
virtual bool ConnectionFrom (const CS_STRING &sHost, uint16_t iPort)
Incoming Connection Event return false and the connection will fail default returns true.
bool Connect (const CString &sHostname, unsigned short uPort, bool bSSL=false, unsigned int uTimeout=60)
Ease of use Connect, assigns to the manager and is subsequently tracked.
virtual bool Connect ()
Create the connection, this is used by the socket manager, and shouldn't be called directly by the user.
bool Listen (unsigned short uPort, bool bSSL, unsigned int uTimeout=0)
Ease of use Listen, assigned to the manager and is subsequently tracked.
virtual bool Listen (uint16_t iPort, int iMaxConns=SOMAXCONN, const CS_STRING &sBindHost="", uint32_t iTimeout=0, bool bDetach=false)
Listens for connections.
CModule * GetModule () const
CString t_s (const CString &sEnglish, const CString &sContext="") const
CInlineFormatMessage t_f (const CString &sEnglish, const CString &sContext="") const
CInlineFormatMessage t_p (const CString &sEnglish, const CString &sEnglishes, int iNum, const CString &sContext) const
CDelayedTranslation t_d (const CString &sEnglish, const CString &sContext="") const
int ConvertAddress (const struct sockaddr_storage *pAddr, socklen_t iAddrLen, CString &sIP, u_short *piPort) const override
virtual int ConvertAddress (const struct sockaddr_storage *pAddr, socklen_t iAddrLen, CS_STRING &sIP, uint16_t *piPort) const
retrieve name info (numeric only) for a given sockaddr_storage
int VerifyPeerCertificate (int iPreVerify, X509_STORE_CTX *pStoreCTX) override
this is hooked in via SSL_set_verify, and be default it just returns 1 meaning success
void SSLHandShakeFinished () override
called once the SSL handshake is complete, this is triggered via SSL_CB_HANDSHAKE_DONE in SSL_set_info_callback()
bool CheckSSLCert (X509 *pCert)
virtual void SSLCertError (X509 *pCert)
bool SNIConfigureClient (CString &sHostname) override
virtual bool SNIConfigureClient (CS_STRING &sHostname)
called to configure the SNI client
CString GetSSLPeerFingerprint (X509 *pCert=nullptr) const
void SetHostToVerifySSL (const CString &sHost)
void SetSSLTrustedPeerFingerprints (const SCString &ssFPs)
void SetTrustAllCerts (bool bTrustAll)
bool GetTrustAllCerts () const
void SetTrustPKI (bool bTrustPKI)
bool GetTrustPKI () const
void SetEncoding (const CString &)
void SetEncoding (const CS_STRING &sEncoding)
virtual void Dereference ()
in the event you pass this class to Copy(), you MUST call this function or on the original Csock other wise bad side effects will happen (double deletes, weird sock closures, etc) if you call this function and have not handled the internal pointers, other bad things can happend (memory leaks, fd leaks, etc) the whole point of this function is to allow this class to go away without shutting down
virtual void Copy (const Csock &cCopy)
use this to copy a sock from one to the other, override it if you have special needs in the event of a copy
Csock & operator<< (const CS_STRING &s)
Csock & operator<< (std::ostream &(*io)(std::ostream &))
Csock & operator<< (int32_t i)
Csock & operator<< (uint32_t i)
Csock & operator<< (int64_t i)
Csock & operator<< (uint64_t i)
Csock & operator<< (float i)
Csock & operator<< (double i)
virtual bool ConnectUnix (const CS_STRING &sPath)
Connect to a UNIX socket.
virtual bool ListenUnix (const CS_STRING &sBindFile, int iMaxConns=SOMAXCONN, uint32_t iTimeout=0)
Listens for connections on an UNIX socket.
virtual cs_sock_t Accept (CS_STRING &sHost, uint16_t &iRPort)
Accept an inbound connection, this is used internally.
virtual bool AcceptSSL ()
Accept an inbound SSL connection, this is used internally and called after Accept.
virtual bool SSLClientSetup ()
This sets up the SSL Client, this is used internally.
virtual bool SSLServerSetup ()
This sets up the SSL Server, this is used internally.
virtual bool ConnectSSL ()
Create the SSL connection.
bool StartTLS ()
start a TLS connection on an existing plain connection
virtual bool Write (const char *data, size_t len)
Write data to the socket.
virtual bool Write (const CS_STRING &sData)
Write a text string to the socket.
virtual cs_ssize_t Read (char *data, size_t len)
Read from the socket Just pass in a pointer, big enough to hold len bytes.
CS_STRING GetLocalIP () const
virtual bool IsConnected () const
Tells you if the socket is connected.
virtual void SetIsConnected (bool b)
Sets the sock, telling it its connected (internal use only)
cs_sock_t & GetRSock ()
returns a reference to the sock
const cs_sock_t & GetRSock () const
void SetRSock (cs_sock_t iSock)
cs_sock_t & GetWSock ()
const cs_sock_t & GetWSock () const
void SetWSock (cs_sock_t iSock)
void SetSock (cs_sock_t iSock)
cs_sock_t & GetSock ()
const cs_sock_t & GetSock () const
void CallSockError (int iErrno, const CS_STRING &sDescription="")
calls SockError, if sDescription is not set, then strerror is used to pull out a default description
virtual void ResetTimer ()
resets the time counter, this is virtual in the event you need an event on the timer being Reset
void PauseRead ()
will pause/unpause reading on this socket
void UnPauseRead ()
bool IsReadPaused () const
void SetTimeout (int iTimeout, uint32_t iTimeoutType=TMO_ALL)
Currently this uses the same value for all timeouts, and iTimeoutType merely states which event will be checked for timeouts.
void SetTimeoutType (uint32_t iTimeoutType)
int GetTimeout () const
uint32_t GetTimeoutType () const
virtual bool CheckTimeout (time_t iNow)
returns true if the socket has timed out
virtual void PushBuff (const char *data, size_t len, bool bStartAtZero=false)
pushes data up on the buffer, if a line is ready it calls the ReadLine event
CS_STRING & GetInternalReadBuffer ()
This gives access to the internal read buffer, if your not going to use ReadLine(), then you may want to clear this out (if its binary data and not many '\n')
CS_STRING & GetInternalWriteBuffer ()
This gives access to the internal write buffer.
void SetMaxBufferThreshold (uint32_t iThreshold)
sets the max buffered threshold when EnableReadLine() is enabled
uint32_t GetMaxBufferThreshold () const
int GetType () const
Returns the connection type from enum eConnType.
void SetType (int iType)
const CS_STRING & GetSockName () const
Returns a reference to the socket name.
void SetSockName (const CS_STRING &sName)
const CS_STRING & GetHostName () const
Returns a reference to the host name.
void SetHostName (const CS_STRING &sHostname)
uint64_t GetStartTime () const
Gets the starting time of this socket.
void ResetStartTime ()
Resets the start time.
uint64_t GetBytesRead () const
Gets the amount of data read during the existence of the socket.
void ResetBytesRead ()
uint64_t GetBytesWritten () const
Gets the amount of data written during the existence of the socket.
void ResetBytesWritten ()
double GetAvgRead (uint64_t iSample=1000) const
Get Avg Read Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
double GetAvgWrite (uint64_t iSample=1000) const
Get Avg Write Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
uint16_t GetRemotePort () const
Returns the remote port.
uint16_t GetLocalPort () const
Returns the local port.
uint16_t GetPort () const
Returns the port.
void SetPort (uint16_t iPort)
void Close (ECloseType eCloseType=CLT_NOW)
just mark us as closed, the parent can pick it up
ECloseType GetCloseType () const
returns int of type to close
bool IsClosed () const
void NonBlockingIO ()
Use this to change your fd's to blocking or none blocking.
bool GetSSL () const
Return true if this socket is using ssl. Note this does not mean the SSL state is finished, but simply that its configured to use ssl.
void SetSSL (bool b)
void DisableSSLProtocols (u_int uDisableOpts)
bitwise setter,
void DisableSSLCompression ()
allow disabling compression
void FollowSSLCipherServerPreference ()
select the ciphers in server-preferred order
void SetCipher (const CS_STRING &sCipher)
Set the cipher type (openssl cipher [to see ciphers available])
const CS_STRING & GetCipher () const
void SetDHParamLocation (const CS_STRING &sDHParamFile)
Set the pem file location.
const CS_STRING & GetDHParamLocation () const
void SetKeyLocation (const CS_STRING &sKeyFile)
const CS_STRING & GetKeyLocation () const
void SetPemLocation (const CS_STRING &sPemFile)
const CS_STRING & GetPemLocation () const
void SetPemPass (const CS_STRING &sPassword)
const CS_STRING & GetPemPass () const
void SetSSLMethod (int iMethod)
Set the SSL method type.
int GetSSLMethod () const
void SetSSLObject (SSL *ssl, bool bDeleteExisting=false)
SSL * GetSSLObject () const
void SetCTXObject (SSL_CTX *sslCtx, bool bDeleteExisting=false)
SSL_SESSION * GetSSLSession () const
void SetCertVerifyCB (FPCertVerifyCB pFP)
setting this to NULL will allow the default openssl verification process kick in
bool HasWriteBuffer () const
Get the send buffer.
void ClearWriteBuffer ()
bool SslIsEstablished () const
is SSL_accept finished ? is the ssl properly finished (from write no error)
bool ConnectInetd (bool bIsSSL=false, const CS_STRING &sHostname="")
Use this to bind this socket to inetd.
bool ConnectFD (int iReadFD, int iWriteFD, const CS_STRING &sName, bool bIsSSL=false, ETConn eDirection=INBOUND)
Tie this guy to an existing real file descriptor.
X509 * GetX509 () const
Get the peer's X509 cert.
CS_STRING GetPeerPubKey () const
Returns the peer's public key.
long GetPeerFingerprint (CS_STRING &sFP) const
Returns the peer's certificate finger print.
uint32_t GetRequireClientCertFlags () const
void SetRequiresClientCert (bool bRequiresCert)
legacy, deprecated
void SetRequireClientCertFlags (uint32_t iRequireClientCertFlags)
bitwise flags, 0 means don't require cert, SSL_VERIFY_PEER verifies peers, SSL_VERIFY_FAIL_IF_NO_PEER_CERT will cause the connection to fail if no cert
virtual void SetParentSockName (const CS_STRING &sParentName)
Set The INBOUND Parent sockname.
const CS_STRING & GetParentSockName () const
virtual void SetRate (uint32_t iBytes, uint64_t iMilliseconds)
sets the rate at which we can send data
uint32_t GetRateBytes () const
uint64_t GetRateTime () const
virtual void Disconnected ()
Disconnected event.
virtual void Timeout ()
Sock Timed out event.
void EnableReadLine ()
set the value of m_bEnableReadLine to true, we don't want to store a buffer for ReadLine, unless we want it
void DisableReadLine ()
bool HasReadLine () const
returns the value of m_bEnableReadLine, if ReadLine is enabled
virtual void Listening (const CS_STRING &sBindIP, uint16_t uPort)
called when type is LISTENER and the listening port is up and running
virtual void ConnectionRefused ()
Connection Refused Event.
virtual void ReadPaused ()
This gets called every iteration of CSocketManager::Select() if the socket is ReadPaused.
virtual void SSLFinishSetup (SSL *pSSL)
Gets called immediatly after the m_ssl member is setup and initialized, useful if you need to assign anything to this ssl session via SSL_set_ex_data.
virtual bool SNIConfigureServer (const CS_STRING &sHostname, CS_STRING &sPemFile, CS_STRING &sPemPass)
gets called when a SNI request is sent, and used to configure a SNI session
SSL_CTX * SetupServerCTX ()
creates a new SSL_CTX based on the setup of this sock
time_t GetTimeSinceLastDataTransaction (time_t iNow=0) const
return how long it has been (in seconds) since the last read or successful write
time_t GetLastCheckTimeout () const
time_t GetNextCheckTimeout (time_t iNow=0) const
Returns the time when CheckTimeout() should be called next.
virtual int GetPending () const
return the data imediatly ready for read
ECONState GetConState () const
returns the current connection state
void SetConState (ECONState eState)
sets the connection state to eState
bool CreateSocksFD ()
grabs fd's for the sockets
void CloseSocksFD ()
puts the socks back to the state they were prior to calling CreateSocksFD
const CS_STRING & GetBindHost () const
void SetBindHost (const CS_STRING &sBindHost)
int DNSLookup (EDNSLType eDNSLType)
dns lookup
bool SetupVHost ()
this is only used on outbound connections, listeners bind in a different spot
bool GetIPv6 () const
void SetIPv6 (bool b)
void SetAFRequire (CSSockAddr::EAFRequire iAFRequire)
bool AllowWrite (uint64_t &iNOW) const
returns true if this socket can write its data, primarily used with rate shaping, initialize iNOW to 0 and it sets it on the first call
void SetSkipConnect (bool b)
virtual int GetAddrInfo (const CS_STRING &sHostname, CSSockAddr &csSockAddr)
override this call with your own DNS lookup method if you have one.
int GetMaxConns () const
returns the number of max pending connections when type is LISTENER
CS_STRING GetEncoding () const
virtual void IcuExtToUCallback (UConverterToUnicodeArgs *toArgs, const char *codeUnits, int32_t length, UConverterCallbackReason reason, UErrorCode *err)
virtual void IcuExtFromUCallback (UConverterFromUnicodeArgs *fromArgs, const UChar *codeUnits, int32_t length, UChar32 codePoint, UConverterCallbackReason reason, UErrorCode *err)
void CleanupCrons ()
void CleanupFDMonitors ()
const std::vector< CCron * > & GetCrons () const
returns a const reference to the crons associated to this socket
virtual void Cron ()
This has a garbage collecter, and is used internall to call the jobs.
virtual void AddCron (CCron *pcCron)
insert a newly created cron
virtual void DelCron (const CS_STRING &sName, bool bDeleteAll=true, bool bCaseSensitive=true)
deletes a cron by name
virtual void DelCron (uint32_t iPos)
delete cron by idx
virtual void DelCronByAddr (CCron *pcCron)
delete cron by address
void CheckFDs (const std::map< cs_sock_t, short > &miiReadyFds)
void AssignFDs (std::map< cs_sock_t, short > &miiReadyFds, struct timeval *tvtimeout)
void MonitorFD (CSMonitorFD *pMonitorFD)
add an FD set to monitor
Static Public Member Functions
static CString GetSkinPath (const CString &sSkinName)
static void FinishUserSessions (const CUser &User)
static void ParseParams (const CString &sParams, std::map< CString, VCString > &msvsParams)
static CString GetDate (time_t tm=0)
Protected Types
enum { errnoBadSSLCert = 12569 }
Protected Member Functions
bool AddModLoop (const CString &sLoopName, CModule &Module, CTemplate *pTemplate=nullptr)
VCString GetDirs (CModule *pModule, bool bIsTemplate)
void SetPaths (CModule *pModule, bool bIsTemplate=false)
void SetVars ()
bool PrintErrorPage (unsigned int uStatusId, const CString &sStatusMsg, const CString &sMessage)
void PrintPage (const CString &sPage)
void Init ()
Static Protected Member Functions
static CString t_s (const CString &sEnglish, const CString &sContext="")
static CInlineFormatMessage t_f (const CString &sEnglish, const CString &sContext="")
static CInlineFormatMessage t_p (const CString &sEnglish, const CString &sEnglishes, int iNum, const CString &sContext="")
static CDelayedTranslation t_d (const CString &sEnglish, const CString &sContext="")
Protected Attributes
bool m_bSentHeader
bool m_bGotHeader
bool m_bLoggedIn
bool m_bPost
bool m_bDone
bool m_bBasicAuth
unsigned long m_uPostLen
CString m_sPostData
CString m_sURI
CString m_sUser
CString m_sPass
CString m_sContentType
CString m_sDocRoot
CString m_sForwardedIP
std::map< CString, VCString > m_msvsPOSTParams
std::map< CString, VCString > m_msvsGETParams
MCString m_msHeaders
bool m_bHTTP10Client
CString m_sIfNoneMatch
bool m_bAcceptGzip
MCString m_msRequestCookies
MCString m_msResponseCookies
CString m_sURIPrefix
CModule * m_pModule
pointer to the module that this sock instance belongs to
std::vector< CCron * > m_vcCrons
std::vector< CSMonitorFD * > m_vcMonitorFD
Member Enumeration Documentation
anonymous enum
anonymous enum protected inherited
Enumerator
errnoBadSSLCert
anonymous enum
anonymous enum inherited
this timeout isn't just connection timeout, but also timeout on NOT recieving data, to disable this set it to 0 then the normal TCP timeout will apply (basically TCP will kill a dead connection) Set the timeout, set to 0 to never timeout
Enumerator
TMO_READ
TMO_WRITE
TMO_ACCEPT
TMO_ALL
ECloseType
enum Csock::ECloseType inherited
Enumerator
CLT_DONT
don't close DER
CLT_NOW
close immediatly
CLT_AFTERWRITE
close after finishing writing the buffer
CLT_DEREFERENCE
used after copy in Csock::Dereference() to cleanup a sock thats being shutdown
ECONState
enum Csock::ECONState inherited
Enumerator
CST_START
CST_DNS
CST_BINDVHOST
CST_DESTDNS
CST_CONNECT
CST_CONNECTSSL
CST_OK
EDisableProtocol
enum Csock::EDisableProtocol inherited
Enumerator
EDP_None
disable nothing
EDP_SSLv2
disable SSL version 2
EDP_SSLv3
disable SSL version 3
EDP_TLSv1
disable TLS version 1
EDP_TLSv1_1
disable TLS version 1.1
EDP_TLSv1_2
disable TLS version 1.2
EDP_SSL
EDNSLType
enum Csock::EDNSLType inherited
Enumerator
DNS_VHOST
this lookup is for the vhost bind
DNS_DEST
this lookup is for the destination address
EFRead
enum Csock::EFRead inherited
Enumerator
READ_EOF
End Of File, done reading.
READ_ERR
Error on the socket, socket closed, done reading.
READ_EAGAIN
Try to get data again.
READ_CONNREFUSED
Connection Refused.
READ_TIMEDOUT
Connection timed out.
EFSelect
enum Csock::EFSelect inherited
Enumerator
SEL_OK
Select passed ok.
SEL_TIMEOUT
Select timed out.
SEL_EAGAIN
Select wants you to try again.
SEL_ERR
Select recieved an error.
EPageReqResult
enum CWebSock::EPageReqResult
Enumerator
PAGE_NOTFOUND
PAGE_PRINT
PAGE_DEFERRED
PAGE_DONE
ESSLMethod
enum Csock::ESSLMethod inherited
Enumerator
TLS
SSL23
SSL2
SSL3
TLS1
TLS11
TLS12
ETConn
enum Csock::ETConn inherited
Enumerator
OUTBOUND
outbound connection
LISTENER
a socket accepting connections
INBOUND
an inbound connection, passed from LISTENER
Constructor & Destructor Documentation
CWebSock()
CWebSock::CWebSock (const CString & sURIPrefix)
~CWebSock()
virtual CWebSock::~CWebSock () virtual
Member Function Documentation
Accept()
virtual cs_sock_t Csock::Accept (CS_STRING & sHost, uint16_t & iRPort) virtual inherited
Accept an inbound connection, this is used internally.
AcceptSSL()
virtual bool Csock::AcceptSSL () virtual inherited
Accept an inbound SSL connection, this is used internally and called after Accept.
AddCron()
virtual void CSockCommon::AddCron (CCron * pcCron) virtual inherited
insert a newly created cron
AddHeader()
void CHTTPSock::AddHeader (const CString & sName, const CString & sValue) inherited
AddModLoop()
bool CWebSock::AddModLoop (const CString & sLoopName, CModule & Module, CTemplate * pTemplate = nullptr) protected
AllowWrite()
bool Csock::AllowWrite (uint64_t & iNOW) const inherited
returns true if this socket can write its data, primarily used with rate shaping, initialize iNOW to 0 and it sets it on the first call
AssignFDs()
void CSockCommon::AssignFDs (std::map< cs_sock_t, short > & miiReadyFds, struct timeval * tvtimeout) inherited
CallSockError()
void Csock::CallSockError (int iErrno, const CS_STRING & sDescription = "") inherited
calls SockError, if sDescription is not set, then strerror is used to pull out a default description
Parameters
iErrno the errno to send
sDescription the description of the error that occurred
CheckFDs()
void CSockCommon::CheckFDs (const std::map< cs_sock_t, short > & miiReadyFds) inherited
CheckPost()
void CHTTPSock::CheckPost () inherited
CheckSSLCert()
bool CZNCSock::CheckSSLCert (X509 * pCert) inherited
CheckTimeout()
virtual bool Csock::CheckTimeout (time_t iNow) virtual inherited
returns true if the socket has timed out
CleanupCrons()
void CSockCommon::CleanupCrons () inherited
CleanupFDMonitors()
void CSockCommon::CleanupFDMonitors () inherited
ClearWriteBuffer()
void Csock::ClearWriteBuffer () inherited
Close()
void Csock::Close (ECloseType eCloseType = CLT_NOW) inherited
just mark us as closed, the parent can pick it up
Referenced by CExecSock::Kill().
CloseSocksFD()
void Csock::CloseSocksFD () inherited
puts the socks back to the state they were prior to calling CreateSocksFD
Connect() [1/2]
virtual bool Csock::Connect () virtual inherited
Create the connection, this is used by the socket manager, and shouldn't be called directly by the user.
Returns
true on success
Reimplemented from Csock.
Connect() [2/2]
bool CSocket::Connect (const CString & sHostname, unsigned short uPort, bool bSSL = false, unsigned int uTimeout = 60) inherited
Ease of use Connect, assigns to the manager and is subsequently tracked.
Connected()
void CHTTPSock::Connected () override virtual inherited
Connected event.
Reimplemented from Csock.
ConnectFD()
bool Csock::ConnectFD (int iReadFD, int iWriteFD, const CS_STRING & sName, bool bIsSSL = false, ETConn eDirection = INBOUND) inherited
Tie this guy to an existing real file descriptor.
Referenced by CExecSock::Execute().
ConnectInetd()
bool Csock::ConnectInetd (bool bIsSSL = false, const CS_STRING & sHostname = "") inherited
Use this to bind this socket to inetd.
ConnectionFrom() [1/2]
virtual bool Csock::ConnectionFrom (const CS_STRING & sHost, uint16_t iPort) inline virtual inherited
Incoming Connection Event return false and the connection will fail default returns true.
ConnectionFrom() [2/2]
bool CSocket::ConnectionFrom (const CString & sHost, unsigned short uPort) override inherited
This limits the global connections from this IP to defeat DoS attacks, feel free to override. The ACL used is provided by the main interface.
See also
CZNC::AllowConnectionFrom
ConnectionRefused()
virtual void Csock::ConnectionRefused () inline virtual inherited
Connection Refused Event.
Reimplemented in CClient, and CIRCSock.
ConnectSSL()
virtual bool Csock::ConnectSSL () virtual inherited
Create the SSL connection.
Returns
true on success
This is used by the socket manager, and shouldn't be called directly by the user.
ConnectUnix()
virtual bool Csock::ConnectUnix (const CS_STRING & sPath) virtual inherited
Connect to a UNIX socket.
Parameters
sPath the path to the UNIX socket.
ConvertAddress() [1/2]
virtual int Csock::ConvertAddress (const struct sockaddr_storage * pAddr, socklen_t iAddrLen, CS_STRING & sIP, uint16_t * piPort) const virtual inherited
retrieve name info (numeric only) for a given sockaddr_storage
Parameters
pAddr the sockaddr_storage
iAddrLen the length
sIP filled with the IP from getnameinfo
piPort if not null, filled with the port
Returns
0 on success.
In the event you want to do additional work before or after getnameinfo is called, you can override this and do just that. One example is in the event that an ipv6 ip is a mapped ipv4 mapped, you can check like so.
if(pAddr->ss_family == AF_INET6 && IN6_IS_ADDR_V4MAPPED(&(((const struct sockaddr_in6 *)pAddr)->sin6_addr))
ConvertAddress() [2/2]
int CZNCSock::ConvertAddress (const struct sockaddr_storage * pAddr, socklen_t iAddrLen, CString & sIP, u_short * piPort) const override inherited
Copy()
virtual void Csock::Copy (const Csock & cCopy) virtual inherited
use this to copy a sock from one to the other, override it if you have special needs in the event of a copy
CreateSocksFD()
bool Csock::CreateSocksFD () inherited
grabs fd's for the sockets
Cron()
virtual void CSockCommon::Cron () virtual inherited
This has a garbage collecter, and is used internall to call the jobs.
DelCron() [1/2]
virtual void CSockCommon::DelCron (const CS_STRING & sName, bool bDeleteAll = true, bool bCaseSensitive = true) virtual inherited
deletes a cron by name
Parameters
sName the name of the cron
bDeleteAll delete all crons that match sName
bCaseSensitive use strcmp or strcasecmp
DelCron() [2/2]
virtual void CSockCommon::DelCron (uint32_t iPos) virtual inherited
delete cron by idx
DelCronByAddr()
virtual void CSockCommon::DelCronByAddr (CCron * pcCron) virtual inherited
delete cron by address
Dereference()
virtual void Csock::Dereference () virtual inherited
in the event you pass this class to Copy(), you MUST call this function or on the original Csock other wise bad side effects will happen (double deletes, weird sock closures, etc) if you call this function and have not handled the internal pointers, other bad things can happend (memory leaks, fd leaks, etc) the whole point of this function is to allow this class to go away without shutting down
DisableReadLine()
void Csock::DisableReadLine () inherited
DisableSSLCompression()
void Csock::DisableSSLCompression () inline inherited
allow disabling compression
DisableSSLProtocols()
void Csock::DisableSSLProtocols (u_int uDisableOpts) inline inherited
bitwise setter,
See also
EDisableProtocol
Disconnected()
virtual void Csock::Disconnected () inline virtual inherited
Disconnected event.
Reimplemented in CClient, and CIRCSock.
DNSLookup()
int Csock::DNSLookup (EDNSLType eDNSLType) inherited
dns lookup
See also
EDNSLType
Returns
0 for success, EAGAIN to check back again (same arguments as before), ETIMEDOUT on failure
EnableReadLine()
void Csock::EnableReadLine () inherited
set the value of m_bEnableReadLine to true, we don't want to store a buffer for ReadLine, unless we want it
FindTmpl()
CString CWebSock::FindTmpl (CModule * pModule, const CString & sName)
FinishUserSessions()
static void CWebSock::FinishUserSessions (const CUser & User) static
FollowSSLCipherServerPreference()
void Csock::FollowSSLCipherServerPreference () inline inherited
select the ciphers in server-preferred order
ForceLogin()
bool CWebSock::ForceLogin () override virtual
Reimplemented from CHTTPSock.
GetAddrInfo()
virtual int Csock::GetAddrInfo (const CS_STRING & sHostname, CSSockAddr & csSockAddr) virtual inherited
override this call with your own DNS lookup method if you have one.
By default this function is blocking
Parameters
sHostname the hostname to resolve
csSockAddr the destination sock address info
See also
CSSockAddr
Returns
0 on success, ETIMEDOUT if no lookup was found, EAGAIN if you should check again later for an answer
GetAvailSkins()
void CWebSock::GetAvailSkins (VCString & vRet) const
GetAvgRead()
double Csock::GetAvgRead (uint64_t iSample = 1000) const inherited
Get Avg Read Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
GetAvgWrite()
double Csock::GetAvgWrite (uint64_t iSample = 1000) const inherited
Get Avg Write Speed in sample milliseconds (default is 1000 milliseconds or 1 second)
GetBindHost()
const CS_STRING & Csock::GetBindHost () const inline inherited
GetBytesRead()
uint64_t Csock::GetBytesRead () const inherited
Gets the amount of data read during the existence of the socket.
GetBytesWritten()
uint64_t Csock::GetBytesWritten () const inherited
Gets the amount of data written during the existence of the socket.
GetCipher()
const CS_STRING & Csock::GetCipher () const inherited
GetCloseType()
ECloseType Csock::GetCloseType () const inline inherited
returns int of type to close
See also
ECloseType
GetConState()
ECONState Csock::GetConState () const inline inherited
returns the current connection state
GetContentType()
const CString & CHTTPSock::GetContentType () const inherited
GetCrons()
const std::vector< CCron * > & CSockCommon::GetCrons () const inline inherited
returns a const reference to the crons associated to this socket
GetCSRFCheck()
CString CWebSock::GetCSRFCheck ()
GetDate()
static CString CHTTPSock::GetDate (time_t tm = 0) static inherited
GetDHParamLocation()
const CS_STRING & Csock::GetDHParamLocation () const inherited
GetDirs()
VCString CWebSock::GetDirs (CModule * pModule, bool bIsTemplate) protected
GetDocRoot()
const CString & CHTTPSock::GetDocRoot () const inherited
GetEncoding()
CS_STRING Csock::GetEncoding () const inline inherited
GetHostName()
const CS_STRING & Csock::GetHostName () const inherited
Returns a reference to the host name.
GetInternalReadBuffer()
CS_STRING & Csock::GetInternalReadBuffer () inherited
This gives access to the internal read buffer, if your not going to use ReadLine(), then you may want to clear this out (if its binary data and not many '\n')
GetInternalWriteBuffer()
CS_STRING & Csock::GetInternalWriteBuffer () inherited
This gives access to the internal write buffer.
If you want to check if the send queue fills up, check here.
GetIPv6()
bool Csock::GetIPv6 () const inline inherited
GetKeyLocation()
const CS_STRING & Csock::GetKeyLocation () const inherited
GetLastCheckTimeout()
time_t Csock::GetLastCheckTimeout () const inline inherited
GetLocalIP()
CS_STRING Csock::GetLocalIP () const inherited
GetLocalPort()
uint16_t Csock::GetLocalPort () const inherited
Returns the local port.
GetMaxBufferThreshold()
uint32_t Csock::GetMaxBufferThreshold () const inherited
GetMaxConns()
int Csock::GetMaxConns () const inline inherited
returns the number of max pending connections when type is LISTENER
GetModule()
CModule * CSocket::GetModule () const inherited
GetNextCheckTimeout()
time_t Csock::GetNextCheckTimeout (time_t iNow = 0) const inherited
Returns the time when CheckTimeout() should be called next.
GetPage()
void CHTTPSock::GetPage () inherited
GetParam()
CString CHTTPSock::GetParam (const CString & sName, bool bPost = true, const CString & sFilter = "\r\n") const inherited
GetParams()
const std::map< CString, VCString > & CHTTPSock::GetParams (bool bPost = true) const inherited
GetParamString()
const CString & CHTTPSock::GetParamString () const inherited
GetParamValues() [1/2]
size_t CHTTPSock::GetParamValues (const CString & sName, std::set< CString > & ssRet, bool bPost = true, const CString & sFilter = "\r\n") const inherited
GetParamValues() [2/2]
size_t CHTTPSock::GetParamValues (const CString & sName, VCString & vsRet, bool bPost = true, const CString & sFilter = "\r\n") const inherited
GetParentSockName()
const CS_STRING & Csock::GetParentSockName () const inherited
GetPass()
const CString & CHTTPSock::GetPass () const inherited
GetPath()
CString CHTTPSock::GetPath () const inherited
GetPeerFingerprint()
long Csock::GetPeerFingerprint (CS_STRING & sFP) const inherited
Returns the peer's certificate finger print.
GetPeerPubKey()
CS_STRING Csock::GetPeerPubKey () const inherited
Returns the peer's public key.
GetPemLocation()
const CS_STRING & Csock::GetPemLocation () const inherited
GetPemPass()
const CS_STRING & Csock::GetPemPass () const inherited
GetPending()
virtual int Csock::GetPending () const virtual inherited
return the data imediatly ready for read
GetPort()
uint16_t Csock::GetPort () const inherited
Returns the port.
GetRateBytes()
uint32_t Csock::GetRateBytes () const inherited
GetRateTime()
uint64_t Csock::GetRateTime () const inherited
GetRawParam()
CString CHTTPSock::GetRawParam (const CString & sName, bool bPost = true) const inherited
GetRemoteIP()
CString CHTTPSock::GetRemoteIP () const override virtual inherited
Reimplemented from CZNCSock.
GetRemotePort()
uint16_t Csock::GetRemotePort () const inherited
Returns the remote port.
GetRequestCookie() [1/2]
CString CWebSock::GetRequestCookie (const CString & sKey)
GetRequestCookie() [2/2]
CString CHTTPSock::GetRequestCookie (const CString & sKey) const inherited
GetRequireClientCertFlags()
uint32_t Csock::GetRequireClientCertFlags () const inherited
GetRSock() [1/2]
cs_sock_t & Csock::GetRSock () inherited
returns a reference to the sock
Referenced by CExecSock::~CExecSock().
GetRSock() [2/2]
const cs_sock_t & Csock::GetRSock () const inherited
GetSession()
std::shared_ptr< CWebSession > CWebSock::GetSession ()
GetSkinName()
CString CWebSock::GetSkinName ()
GetSkinPath()
static CString CWebSock::GetSkinPath (const CString & sSkinName) static
GetSock() [1/2]
cs_sock_t & Csock::GetSock () inherited
GetSock() [2/2]
const cs_sock_t & Csock::GetSock () const inherited
GetSockName()
const CS_STRING & Csock::GetSockName () const inherited
Returns a reference to the socket name.
GetSockObj() [1/2]
virtual Csock * Csock::GetSockObj (const CS_STRING & sHostname, uint16_t iPort) virtual inherited
override this for accept sockets
GetSockObj() [2/2]
Csock * CWebSock::GetSockObj (const CString & sHost, unsigned short uPort) override virtual
Implements CHTTPSock.
GetSSL()
bool Csock::GetSSL () const inherited
Return true if this socket is using ssl. Note this does not mean the SSL state is finished, but simply that its configured to use ssl.
GetSSLMethod()
int Csock::GetSSLMethod () const inherited
GetSSLObject()
SSL * Csock::GetSSLObject () const inherited
GetSSLPeerFingerprint()
CString CZNCSock::GetSSLPeerFingerprint (X509 * pCert = nullptr) const inherited
GetSSLSession()
SSL_SESSION * Csock::GetSSLSession () const inherited
GetStartTime()
uint64_t Csock::GetStartTime () const inherited
Gets the starting time of this socket.
GetTimeout()
int Csock::GetTimeout () const inherited
GetTimeoutType()
uint32_t Csock::GetTimeoutType () const inherited
GetTimeSinceLastDataTransaction()
time_t Csock::GetTimeSinceLastDataTransaction (time_t iNow = 0) const inherited
return how long it has been (in seconds) since the last read or successful write
GetTrustAllCerts()
bool CZNCSock::GetTrustAllCerts () const inline inherited
GetTrustPKI()
bool CZNCSock::GetTrustPKI () const inline inherited
GetType()
int Csock::GetType () const inherited
Returns the connection type from enum eConnType.
GetURI()
const CString & CHTTPSock::GetURI () const inherited
GetURIPrefix()
const CString & CHTTPSock::GetURIPrefix () const inherited
GetUser()
const CString & CHTTPSock::GetUser () const inherited
GetWSock() [1/2]
cs_sock_t & Csock::GetWSock () inherited
Referenced by CExecSock::~CExecSock().
GetWSock() [2/2]
const cs_sock_t & Csock::GetWSock () const inherited
GetX509()
X509 * Csock::GetX509 () const inherited
Get the peer's X509 cert.
it is up to you, the caller to call X509_free() on this object
HasParam()
bool CHTTPSock::HasParam (const CString & sName, bool bPost = true) const inherited
HasReadLine()
bool Csock::HasReadLine () const inline inherited
returns the value of m_bEnableReadLine, if ReadLine is enabled
HasWriteBuffer()
bool Csock::HasWriteBuffer () const inherited
Get the send buffer.
IcuExtFromUCallback()
virtual void Csock::IcuExtFromUCallback (UConverterFromUnicodeArgs * fromArgs, const UChar * codeUnits, int32_t length, UChar32 codePoint, UConverterCallbackReason reason, UErrorCode * err) virtual inherited
Reimplemented in CIRCSocket.
IcuExtToUCallback()
virtual void Csock::IcuExtToUCallback (UConverterToUnicodeArgs * toArgs, const char * codeUnits, int32_t length, UConverterCallbackReason reason, UErrorCode * err) virtual inherited
Reimplemented in CIRCSocket.
Init()
void CHTTPSock::Init () protected inherited
IsClosed()
bool Csock::IsClosed () const inline inherited
IsConnected()
virtual bool Csock::IsConnected () const virtual inherited
Tells you if the socket is connected.
IsLoggedIn()
bool CHTTPSock::IsLoggedIn () const inline inherited
References CHTTPSock::m_bLoggedIn.
IsPost()
bool CHTTPSock::IsPost () const inherited
IsReadPaused()
bool Csock::IsReadPaused () const inherited
Listen() [1/2]
virtual bool Csock::Listen (uint16_t iPort, int iMaxConns = SOMAXCONN, const CS_STRING & sBindHost = "", uint32_t iTimeout = 0, bool bDetach = false) virtual inherited
Listens for connections.
Parameters
iPort the port to listen on
iMaxConns the maximum amount of pending connections to allow
sBindHost the vhost on which to listen
iTimeout if no connections come in by this timeout, the listener is closed
bDetach don't block waiting for port to come up, instead detach and return immediately
Reimplemented from Csock.
Listen() [2/2]
bool CSocket::Listen (unsigned short uPort, bool bSSL, unsigned int uTimeout = 0) inherited
Ease of use Listen, assigned to the manager and is subsequently tracked.
Listening()
virtual void Csock::Listening (const CS_STRING & sBindIP, uint16_t uPort) inline virtual inherited
called when type is LISTENER and the listening port is up and running
Parameters
sBindIP the IP that is being bound to. Empty if no bind restriction
uPort the listening port
ListenUnix()
virtual bool Csock::ListenUnix (const CS_STRING & sBindFile, int iMaxConns = SOMAXCONN, uint32_t iTimeout = 0) virtual inherited
Listens for connections on an UNIX socket.
Parameters
sBindFile the socket on which to listen
iMaxConns the maximum amount of pending connections to allow
iTimeout if no connections come in by this timeout, the listener is closed
MonitorFD()
void CSockCommon::MonitorFD (CSMonitorFD * pMonitorFD) inline inherited
add an FD set to monitor
NonBlockingIO()
void Csock::NonBlockingIO () inherited
Use this to change your fd's to blocking or none blocking.
OnLogin()
bool CWebSock::OnLogin (const CString & sUser, const CString & sPass, bool bBasic) override virtual
Reimplemented from CHTTPSock.
OnPageRequest()
void CWebSock::OnPageRequest (const CString & sURI) override virtual
Implements CHTTPSock.
operator<<() [1/8]
Csock & Csock::operator<< (const CS_STRING & s) inherited
operator<<() [2/8]
Csock & Csock::operator<< (double i) inherited
operator<<() [3/8]
Csock & Csock::operator<< (float i) inherited
operator<<() [4/8]
Csock & Csock::operator<< (int32_t i) inherited
operator<<() [5/8]
Csock & Csock::operator<< (int64_t i) inherited
operator<<() [6/8]
Csock & Csock::operator<< (std::ostream &(*)(std::ostream &) io) inherited
operator<<() [7/8]
Csock & Csock::operator<< (uint32_t i) inherited
operator<<() [8/8]
Csock & Csock::operator<< (uint64_t i) inherited
ParseParams()
static void CHTTPSock::ParseParams (const CString & sParams, std::map< CString, VCString > & msvsParams) static inherited
ParseURI()
void CHTTPSock::ParseURI () inherited
PauseRead()
void Csock::PauseRead () inherited
will pause/unpause reading on this socket
PrintErrorPage() [1/2]
void CWebSock::PrintErrorPage (const CString & sMessage)
PrintErrorPage() [2/2]
bool CHTTPSock::PrintErrorPage (unsigned int uStatusId, const CString & sStatusMsg, const CString & sMessage) protected
PrintFile()
virtual bool CHTTPSock::PrintFile (const CString & sFileName, CString sContentType = "") virtual inherited
PrintHeader()
bool CHTTPSock::PrintHeader (off_t uContentLength, const CString & sContentType = "", unsigned int uStatusId = 200, const CString & sStatusMsg = "OK") inherited
PrintNotFound()
bool CHTTPSock::PrintNotFound () inherited
PrintPage()
void CHTTPSock::PrintPage (const CString & sPage) protected inherited
PrintStaticFile()
EPageReqResult CWebSock::PrintStaticFile (const CString & sPath, CString & sPageRet, CModule * pModule = nullptr)
PrintTemplate()
EPageReqResult CWebSock::PrintTemplate (const CString & sPageName, CString & sPageRet, CModule * pModule = nullptr)
PushBuff()
virtual void Csock::PushBuff (const char * data, size_t len, bool bStartAtZero = false) virtual inherited
pushes data up on the buffer, if a line is ready it calls the ReadLine event
ReachedMaxBuffer()
void CSocket::ReachedMaxBuffer () override virtual inherited
This defaults to closing the socket, feel free to override.
Reimplemented from Csock.
Read()
virtual cs_ssize_t Csock::Read (char * data, size_t len) virtual inherited
Read from the socket Just pass in a pointer, big enough to hold len bytes.
Parameters
data the buffer to read into
len the size of the buffer
Returns
Returns READ_EOF for EOF Returns READ_ERR for ERROR Returns READ_EAGAIN for Try Again (EAGAIN) Returns READ_CONNREFUSED for connection refused Returns READ_TIMEDOUT for a connection that timed out at the TCP level Otherwise returns the bytes read into data
ReadData()
void CHTTPSock::ReadData (const char * data, size_t len) override virtual inherited
Ready to read data event.
Reimplemented from Csock.
ReadLine() [1/2]
virtual void Csock::ReadLine (const CS_STRING & sLine) inline virtual inherited
Ready to Read a full line event.
If encoding is provided, this is guaranteed to be UTF-8
ReadLine() [2/2]
void CHTTPSock::ReadLine (const CString & sData) override inherited
ReadPaused()
virtual void Csock::ReadPaused () inline virtual inherited
This gets called every iteration of CSocketManager::Select() if the socket is ReadPaused.
Redirect()
bool CHTTPSock::Redirect (const CString & sURL) inherited
ResetBytesRead()
void Csock::ResetBytesRead () inherited
ResetBytesWritten()
void Csock::ResetBytesWritten () inherited
ResetStartTime()
void Csock::ResetStartTime () inherited
Resets the start time.
ResetTimer()
virtual void Csock::ResetTimer () virtual inherited
resets the time counter, this is virtual in the event you need an event on the timer being Reset
SendCookie()
bool CWebSock::SendCookie (const CString & sKey, const CString & sValue)
SentHeader()
bool CHTTPSock::SentHeader () const inherited
SetAFRequire()
void Csock::SetAFRequire (CSSockAddr::EAFRequire iAFRequire) inline inherited
SetBindHost()
void Csock::SetBindHost (const CS_STRING & sBindHost) inline inherited
SetCertVerifyCB()
void Csock::SetCertVerifyCB (FPCertVerifyCB pFP) inline inherited
setting this to NULL will allow the default openssl verification process kick in
SetCipher()
void Csock::SetCipher (const CS_STRING & sCipher) inherited
Set the cipher type (openssl cipher [to see ciphers available])
SetConState()
void Csock::SetConState (ECONState eState) inline inherited
sets the connection state to eState
SetContentType()
void CHTTPSock::SetContentType (const CString & sContentType) inherited
SetCTXObject()
void Csock::SetCTXObject (SSL_CTX * sslCtx, bool bDeleteExisting = false) inherited
SetDHParamLocation()
void Csock::SetDHParamLocation (const CS_STRING & sDHParamFile) inherited
Set the pem file location.
SetDocRoot()
void CHTTPSock::SetDocRoot (const CString & s) inherited
SetEncoding() [1/2]
void Csock::SetEncoding (const CS_STRING & sEncoding) inherited
SetEncoding() [2/2]
void CZNCSock::SetEncoding (const CString &) inherited
SetHostName()
void Csock::SetHostName (const CS_STRING & sHostname) inherited
SetHostToVerifySSL()
void CZNCSock::SetHostToVerifySSL (const CString & sHost) inline inherited
SetIPv6()
void Csock::SetIPv6 (bool b) inline inherited
SetIsConnected()
virtual void Csock::SetIsConnected (bool b) virtual inherited
Sets the sock, telling it its connected (internal use only)
SetKeyLocation()
void Csock::SetKeyLocation (const CS_STRING & sKeyFile) inherited
SetLoggedIn()
void CHTTPSock::SetLoggedIn (bool b) inline inherited
References CHTTPSock::m_bLoggedIn.
SetMaxBufferThreshold()
void Csock::SetMaxBufferThreshold (uint32_t iThreshold) inherited
sets the max buffered threshold when EnableReadLine() is enabled
SetParentSockName()
virtual void Csock::SetParentSockName (const CS_STRING & sParentName) virtual inherited
Set The INBOUND Parent sockname.
SetPaths()
void CWebSock::SetPaths (CModule * pModule, bool bIsTemplate = false) protected
SetPemLocation()
void Csock::SetPemLocation (const CS_STRING & sPemFile) inherited
SetPemPass()
void Csock::SetPemPass (const CS_STRING & sPassword) inherited
SetPort()
void Csock::SetPort (uint16_t iPort) inherited
SetRate()
virtual void Csock::SetRate (uint32_t iBytes, uint64_t iMilliseconds) virtual inherited
sets the rate at which we can send data
Parameters
iBytes the amount of bytes we can write
iMilliseconds the amount of time we have to rate to iBytes
SetRequireClientCertFlags()
void Csock::SetRequireClientCertFlags (uint32_t iRequireClientCertFlags) inline inherited
bitwise flags, 0 means don't require cert, SSL_VERIFY_PEER verifies peers, SSL_VERIFY_FAIL_IF_NO_PEER_CERT will cause the connection to fail if no cert
SetRequiresClientCert()
void Csock::SetRequiresClientCert (bool bRequiresCert) inherited
legacy, deprecated
See also
SetRequireClientCertFlags
SetRSock()
void Csock::SetRSock (cs_sock_t iSock) inherited
Referenced by CExecSock::~CExecSock().
SetSkipConnect()
void Csock::SetSkipConnect (bool b) inline inherited
SetSock()
void Csock::SetSock (cs_sock_t iSock) inherited
SetSockName()
void Csock::SetSockName (const CS_STRING & sName) inherited
SetSSL()
void Csock::SetSSL (bool b) inherited
SetSSLMethod()
void Csock::SetSSLMethod (int iMethod) inherited
Set the SSL method type.
SetSSLObject()
void Csock::SetSSLObject (SSL * ssl, bool bDeleteExisting = false) inherited
SetSSLTrustedPeerFingerprints()
void CZNCSock::SetSSLTrustedPeerFingerprints (const SCString & ssFPs) inline inherited
SetTimeout()
void Csock::SetTimeout (int iTimeout, uint32_t iTimeoutType = TMO_ALL) inherited
Currently this uses the same value for all timeouts, and iTimeoutType merely states which event will be checked for timeouts.
SetTimeoutType()
void Csock::SetTimeoutType (uint32_t iTimeoutType) inherited
SetTrustAllCerts()
void CZNCSock::SetTrustAllCerts (bool bTrustAll) inline inherited
SetTrustPKI()
void CZNCSock::SetTrustPKI (bool bTrustPKI) inline inherited
SetType()
void Csock::SetType (int iType) inherited
SetupServerCTX()
SSL_CTX * Csock::SetupServerCTX () inherited
creates a new SSL_CTX based on the setup of this sock
SetupVHost()
bool Csock::SetupVHost () inherited
this is only used on outbound connections, listeners bind in a different spot
SetVars()
void CWebSock::SetVars () protected
SetWSock()
void Csock::SetWSock (cs_sock_t iSock) inherited
Referenced by CExecSock::~CExecSock().
SNIConfigureClient() [1/2]
virtual bool Csock::SNIConfigureClient (CS_STRING & sHostname) virtual inherited
called to configure the SNI client
Parameters
sHostname,the hostname to configure SNI with, you can fill this with GetHostname() if its a valid hostname and not an OP
Returns
returning true causes a call to configure SNI with the hostname returned
SNIConfigureClient() [2/2]
bool CZNCSock::SNIConfigureClient (CString & sHostname) override inherited
SNIConfigureServer()
virtual bool Csock::SNIConfigureServer (const CS_STRING & sHostname, CS_STRING & sPemFile, CS_STRING & sPemPass) inline virtual inherited
gets called when a SNI request is sent, and used to configure a SNI session
Parameters
sHostname the hostname sent from the client
sPemFile fill this with the location to the pemfile
sPemPass fill this with the pemfile password if there is one
Returns
return true to proceed with the SNI server configuration
SockError() [1/2]
virtual void Csock::SockError (int iErrno, const CS_STRING & sDescription) inline virtual inherited
A sock error occured event.
SockError() [2/2]
void CSocket::SockError (int iErrno, const CString & sDescription) override inherited
SSLCertError()
virtual void CZNCSock::SSLCertError (X509 * pCert) inline virtual inherited
Reimplemented in CIRCSock.
SSLClientSetup()
virtual bool Csock::SSLClientSetup () virtual inherited
This sets up the SSL Client, this is used internally.
SSLFinishSetup()
virtual void Csock::SSLFinishSetup (SSL * pSSL) inline virtual inherited
Gets called immediatly after the m_ssl member is setup and initialized, useful if you need to assign anything to this ssl session via SSL_set_ex_data.
SSLHandShakeFinished()
void CZNCSock::SSLHandShakeFinished () override virtual inherited
called once the SSL handshake is complete, this is triggered via SSL_CB_HANDSHAKE_DONE in SSL_set_info_callback()
This is a spot where you can look at the finished peer certifificate ... IE
X509 * pCert = GetX509();
char szName[256];
memset(szName, '\0', 256);
X509_NAME_get_text_by_NID (X509_get_subject_name(pCert), NID_commonName, szName, 255);
cerr << "Name! " << szName << endl;
X509_free(pCert);
Reimplemented from Csock.
SslIsEstablished()
bool Csock::SslIsEstablished () const inherited
is SSL_accept finished ? is the ssl properly finished (from write no error)
SSLServerSetup()
virtual bool Csock::SSLServerSetup () virtual inherited
This sets up the SSL Server, this is used internally.
StartTLS()
bool Csock::StartTLS () inherited
start a TLS connection on an existing plain connection
t_d() [1/2]
static CDelayedTranslation CCoreTranslationMixin::t_d (const CString & sEnglish, const CString & sContext = "") static protected inherited
t_d() [2/2]
CDelayedTranslation CSocket::t_d (const CString & sEnglish, const CString & sContext = "") const inherited
t_f() [1/2]
static CInlineFormatMessage CCoreTranslationMixin::t_f (const CString & sEnglish, const CString & sContext = "") static protected inherited
t_f() [2/2]
CInlineFormatMessage CSocket::t_f (const CString & sEnglish, const CString & sContext = "") const inherited
t_p() [1/2]
CInlineFormatMessage CSocket::t_p (const CString & sEnglish, const CString & sEnglishes, int iNum, const CString & sContext) const inherited
t_p() [2/2]
static CInlineFormatMessage CCoreTranslationMixin::t_p (const CString & sEnglish, const CString & sEnglishes, int iNum, const CString & sContext = "") static protected inherited
t_s() [1/2]
static CString CCoreTranslationMixin::t_s (const CString & sEnglish, const CString & sContext = "") static protected inherited
t_s() [2/2]
CString CSocket::t_s (const CString & sEnglish, const CString & sContext = "") const inherited
Timeout()
virtual void Csock::Timeout () inline virtual inherited
Sock Timed out event.
Reimplemented in CClient, and CIRCSock.
UnPauseRead()
void Csock::UnPauseRead () inherited
ValidateCSRFCheck()
bool CWebSock::ValidateCSRFCheck (const CString & sURI)
VerifyPeerCertificate()
int CZNCSock::VerifyPeerCertificate (int iPreVerify, X509_STORE_CTX * pStoreCTX) override virtual inherited
this is hooked in via SSL_set_verify, and be default it just returns 1 meaning success
Parameters
iPreVerify the pre-verification status as determined by openssl internally
pStoreCTX the X509_STORE_CTX containing the certificate
Returns
1 to continue, 0 to abort
This may get called multiple times, for example with a chain certificate which is fairly typical with certificates from godaddy, freessl, etc. Additionally, openssl does not do any host verification, they leave that up to the you. One easy way to deal with this is to wait for SSLHandShakeFinished() and examine the peer certificate
See also
SSLHandShakeFinished
Reimplemented from Csock.
Write() [1/2]
virtual bool Csock::Write (const char * data, size_t len) virtual inherited
Write data to the socket.
If not all of the data is sent, it will be stored on an internal buffer, and tried again with next call to Write if the socket is blocking, it will send everything, its ok to check ernno after this (nothing else is processed)
Parameters
data the data to send
len the length of data
Write() [2/2]
virtual bool Csock::Write (const CS_STRING & sData) virtual inherited
Write a text string to the socket.
Encoding is used, if set
Parameters
sData the string to send; if encoding is provided, sData should be UTF-8 and will be encoded
See also
Write(const char *, int)
Member Data Documentation
m_bAcceptGzip
bool CHTTPSock::m_bAcceptGzip protected inherited
m_bBasicAuth
bool CHTTPSock::m_bBasicAuth protected inherited
m_bDone
bool CHTTPSock::m_bDone protected inherited
m_bGotHeader
bool CHTTPSock::m_bGotHeader protected inherited
m_bHTTP10Client
bool CHTTPSock::m_bHTTP10Client protected inherited
m_bLoggedIn
bool CHTTPSock::m_bLoggedIn protected inherited
Referenced by CHTTPSock::IsLoggedIn(), and CHTTPSock::SetLoggedIn().
m_bPost
bool CHTTPSock::m_bPost protected inherited
m_bSentHeader
bool CHTTPSock::m_bSentHeader protected inherited
m_msHeaders
MCString CHTTPSock::m_msHeaders protected inherited
m_msRequestCookies
MCString CHTTPSock::m_msRequestCookies protected inherited
m_msResponseCookies
MCString CHTTPSock::m_msResponseCookies protected inherited
m_msvsGETParams
std::map<CString, VCString> CHTTPSock::m_msvsGETParams protected inherited
m_msvsPOSTParams
std::map<CString, VCString> CHTTPSock::m_msvsPOSTParams protected inherited
m_pModule
CModule* CSocket::m_pModule protected inherited
pointer to the module that this sock instance belongs to
m_sContentType
CString CHTTPSock::m_sContentType protected inherited
m_sDocRoot
CString CHTTPSock::m_sDocRoot protected inherited
m_sForwardedIP
CString CHTTPSock::m_sForwardedIP protected inherited
m_sIfNoneMatch
CString CHTTPSock::m_sIfNoneMatch protected inherited
m_sPass
CString CHTTPSock::m_sPass protected inherited
m_sPostData
CString CHTTPSock::m_sPostData protected inherited
m_sURI
CString CHTTPSock::m_sURI protected inherited
m_sURIPrefix
CString CHTTPSock::m_sURIPrefix protected inherited
m_sUser
CString CHTTPSock::m_sUser protected inherited
m_uPostLen
unsigned long CHTTPSock::m_uPostLen protected inherited
m_vcCrons
std::vector<CCron *> CSockCommon::m_vcCrons protected inherited
m_vcMonitorFD
std::vector<CSMonitorFD *> CSockCommon::m_vcMonitorFD protected inherited
The documentation for this class was generated from the following file:
WebModules.h