ZNC: CNick Class Reference
CNick Class Reference
#include <Nick.h>
Public Member Functions
CNick ()
CNick (const CString &sNick)
~CNick ()
CNick (const CNick &)=default
CNick & operator= (const CNick &)=default
void Reset ()
void Parse (const CString &sNickMask)
CString GetHostMask () const
size_t GetCommonChans (std::vector< CChan * > &vChans, CIRCNetwork *pNetwork) const
bool NickEquals (const CString &nickname) const
void SetNetwork (CIRCNetwork *pNetwork)
void SetNick (const CString &s)
void SetIdent (const CString &s)
void SetHost (const CString &s)
bool AddPerm (char cPerm)
e.g. '@' for chanop.
bool RemPerm (char cPerm)
e.g. '@' for chanop.
CString GetPermStr () const
e.g. '@' for chanop.
char GetPermChar () const
e.g. '@' for chanop.
bool HasPerm (char cPerm) const
e.g. '@' for chanop.
const CString & GetNick () const
const CString & GetIdent () const
const CString & GetHost () const
CString GetNickMask () const
void Clone (const CNick &SourceNick)
Protected Attributes
CString m_sChanPerms
CIRCNetwork * m_pNetwork
CString m_sNick
CString m_sIdent
CString m_sHost
Constructor & Destructor Documentation
CNick() [1/3]
CNick::CNick ()
CNick() [2/3]
CNick::CNick (const CString & sNick)
~CNick()
CNick::~CNick ()
CNick() [3/3]
CNick::CNick (const CNick &) default
Member Function Documentation
AddPerm()
bool CNick::AddPerm (char cPerm)
e.g. '@' for chanop.
Referenced by CChan::AddPerm().
Clone()
void CNick::Clone (const CNick & SourceNick)
GetCommonChans()
size_t CNick::GetCommonChans (std::vector< CChan * > & vChans, CIRCNetwork * pNetwork) const
GetHost()
const CString & CNick::GetHost () const
GetHostMask()
CString CNick::GetHostMask () const
GetIdent()
const CString & CNick::GetIdent () const
GetNick()
const CString & CNick::GetNick () const
Referenced by CIRCSock::GetNick(), and CNickMessage::GetOldNick().
GetNickMask()
CString CNick::GetNickMask () const
Referenced by CIRCSock::GetNickMask().
GetPermChar()
char CNick::GetPermChar () const
e.g. '@' for chanop.
GetPermStr()
CString CNick::GetPermStr () const
e.g. '@' for chanop.
Referenced by CChan::GetPermStr().
HasPerm()
bool CNick::HasPerm (char cPerm) const
e.g. '@' for chanop.
Referenced by CChan::HasPerm().
NickEquals()
bool CNick::NickEquals (const CString & nickname) const
operator=()
CNick & CNick::operator= (const CNick &) default
Parse()
void CNick::Parse (const CString & sNickMask)
RemPerm()
bool CNick::RemPerm (char cPerm)
e.g. '@' for chanop.
Referenced by CChan::RemPerm().
Reset()
void CNick::Reset ()
SetHost()
void CNick::SetHost (const CString & s)
SetIdent()
void CNick::SetIdent (const CString & s)
SetNetwork()
void CNick::SetNetwork (CIRCNetwork * pNetwork)
SetNick()
void CNick::SetNick (const CString & s)
Member Data Documentation
m_pNetwork
CIRCNetwork* CNick::m_pNetwork protected
m_sChanPerms
CString CNick::m_sChanPerms protected
m_sHost
CString CNick::m_sHost protected
m_sIdent
CString CNick::m_sIdent protected
m_sNick
CString CNick::m_sNick protected
The documentation for this class was generated from the following file:
Nick.h