ZNC: CQuery Class Reference
CQuery Class Reference
#include <Query.h>
Public Member Functions
CQuery (const CString &sName, CIRCNetwork *pNetwork)
~CQuery ()
CQuery (const CQuery &)=delete
CQuery & operator= (const CQuery &)=delete
const CBuffer & GetBuffer () const
unsigned int GetBufferCount () const
bool SetBufferCount (unsigned int u, bool bForce=false)
size_t AddBuffer (const CMessage &Format, const CString &sText="")
size_t AddBuffer (const CString &sFormat, const CString &sText="", const timeval *ts=nullptr, const MCString &mssTags=MCString::EmptyMap)
void ClearBuffer ()
void SendBuffer (CClient *pClient)
void SendBuffer (CClient *pClient, const CBuffer &Buffer)
const CString & GetName () const
Constructor & Destructor Documentation
CQuery() [1/2]
CQuery::CQuery (const CString & sName, CIRCNetwork * pNetwork)
~CQuery()
CQuery::~CQuery ()
CQuery() [2/2]
CQuery::CQuery (const CQuery &) delete
Member Function Documentation
AddBuffer() [1/2]
size_t CQuery::AddBuffer (const CMessage & Format, const CString & sText = "") inline
References CBuffer::AddLine().
AddBuffer() [2/2]
size_t CQuery::AddBuffer (const CString & sFormat, const CString & sText = "", const timeval * ts = nullptr, const MCString & mssTags = MCString::EmptyMap) inline
Deprecated:
References CBuffer::AddLine().
ClearBuffer()
void CQuery::ClearBuffer () inline
References CBuffer::Clear(), and SendBuffer().
GetBuffer()
const CBuffer& CQuery::GetBuffer () const inline
GetBufferCount()
unsigned int CQuery::GetBufferCount () const inline
References CBuffer::GetLineCount().
GetName()
const CString& CQuery::GetName () const inline
operator=()
CQuery& CQuery::operator= (const CQuery &) delete
SendBuffer() [1/2]
void CQuery::SendBuffer (CClient * pClient)
Referenced by ClearBuffer().
SendBuffer() [2/2]
void CQuery::SendBuffer (CClient * pClient, const CBuffer & Buffer)
SetBufferCount()
bool CQuery::SetBufferCount (unsigned int u, bool bForce = false) inline
References CBuffer::SetLineCount().
The documentation for this class was generated from the following file:
Query.h