ZNC: std::tr1 Namespace Reference
std::tr1 Namespace Reference
Namespaces
namespace gtest_internal
Classes
class tuple<>
class tuple
struct tuple_size< GTEST_0_TUPLE_(T) >
struct tuple_size< GTEST_1_TUPLE_(T) >
struct tuple_size< GTEST_2_TUPLE_(T) >
struct tuple_size< GTEST_3_TUPLE_(T) >
struct tuple_size< GTEST_4_TUPLE_(T) >
struct tuple_size< GTEST_5_TUPLE_(T) >
struct tuple_size< GTEST_6_TUPLE_(T) >
struct tuple_size< GTEST_7_TUPLE_(T) >
struct tuple_size< GTEST_8_TUPLE_(T) >
struct tuple_size< GTEST_9_TUPLE_(T) >
struct tuple_size< GTEST_10_TUPLE_(T) >
struct tuple_element
Functions
template<GTEST_1_TYPENAMES_(T) >
class GTEST_1_TUPLE_ (T)
template<GTEST_2_TYPENAMES_(T) >
class GTEST_2_TUPLE_ (T)
template<GTEST_3_TYPENAMES_(T) >
class GTEST_3_TUPLE_ (T)
template<GTEST_4_TYPENAMES_(T) >
class GTEST_4_TUPLE_ (T)
template<GTEST_5_TYPENAMES_(T) >
class GTEST_5_TUPLE_ (T)
template<GTEST_6_TYPENAMES_(T) >
class GTEST_6_TUPLE_ (T)
template<GTEST_7_TYPENAMES_(T) >
class GTEST_7_TUPLE_ (T)
template<GTEST_8_TYPENAMES_(T) >
class GTEST_8_TUPLE_ (T)
template<GTEST_9_TYPENAMES_(T) >
class GTEST_9_TUPLE_ (T)
tuple make_tuple ()
template<int k, GTEST_10_TYPENAMES_(T) >
GTEST_ADD_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T))) get(GTEST_10_TUPLE_(T)&t)
template<int k, GTEST_10_TYPENAMES_(T) >
GTEST_BY_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T))) get(const GTEST_10_TUPLE_(T)&t)
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) >
bool operator== (const GTEST_10_TUPLE_(T)&t, const GTEST_10_TUPLE_(U)&u)
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) >
bool operator!= (const GTEST_10_TUPLE_(T)&t, const GTEST_10_TUPLE_(U)&u)
Function Documentation
template<GTEST_1_TYPENAMES_(T) > std::tr1::GTEST_1_TUPLE_ (T) [inline]
References std::tr1::tuple<>::f0_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_2_TYPENAMES_(T) > std::tr1::GTEST_2_TUPLE_ (T) [inline]
References std::tr1::tuple<>::f0_, std::tr1::tuple<>::f1_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_3_TYPENAMES_(T) > class std::tr1::GTEST_3_TUPLE_ (T)
References std::tr1::tuple<>::f0_, std::tr1::tuple<>::f1_, std::tr1::tuple<>::f2_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_4_TYPENAMES_(T) > class std::tr1::GTEST_4_TUPLE_ (T)
References std::tr1::tuple<>::f0_, std::tr1::tuple<>::f1_, std::tr1::tuple<>::f2_, std::tr1::tuple<>::f3_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_5_TYPENAMES_(T) > class std::tr1::GTEST_5_TUPLE_ (T)
References std::tr1::tuple<>::f0_, std::tr1::tuple<>::f1_, std::tr1::tuple<>::f2_, std::tr1::tuple<>::f3_, std::tr1::tuple<>::f4_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_6_TYPENAMES_(T) > class std::tr1::GTEST_6_TUPLE_ (T)
References std::tr1::tuple<>::f0_, std::tr1::tuple<>::f1_, std::tr1::tuple<>::f2_, std::tr1::tuple<>::f3_, std::tr1::tuple<>::f4_, std::tr1::tuple<>::f5_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_7_TYPENAMES_(T) > class std::tr1::GTEST_7_TUPLE_ (T)
References std::tr1::tuple<>::f0_, std::tr1::tuple<>::f1_, std::tr1::tuple<>::f2_, std::tr1::tuple<>::f3_, std::tr1::tuple<>::f4_, std::tr1::tuple<>::f5_, std::tr1::tuple<>::f6_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_8_TYPENAMES_(T) > class std::tr1::GTEST_8_TUPLE_ (T)
References std::tr1::tuple<>::f0_, std::tr1::tuple<>::f1_, std::tr1::tuple<>::f2_, std::tr1::tuple<>::f3_, std::tr1::tuple<>::f4_, std::tr1::tuple<>::f5_, std::tr1::tuple<>::f6_, std::tr1::tuple<>::f7_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<GTEST_9_TYPENAMES_(T) > class std::tr1::GTEST_9_TUPLE_ (T)
References std::tr1::tuple<>::f0_, std::tr1::tuple<>::f1_, std::tr1::tuple<>::f2_, std::tr1::tuple<>::f3_, std::tr1::tuple<>::f4_, std::tr1::tuple<>::f5_, std::tr1::tuple<>::f6_, std::tr1::tuple<>::f7_, std::tr1::tuple<>::f8_, GTEST_BY_REF_(), and GTEST_DECLARE_TUPLE_AS_FRIEND_.
template<int k, GTEST_10_TYPENAMES_(T) > std::tr1::GTEST_ADD_REF_ (GTEST_TUPLE_ELEMENT_(k, GTEST_10_TUPLE_(T)))
References testing::Field().
template<int k, GTEST_10_TYPENAMES_(T) > std::tr1::GTEST_BY_REF_ (GTEST_TUPLE_ELEMENT_(k,GTEST_10_TUPLE_(T))) const
Referenced by GTEST_1_TUPLE_(), GTEST_2_TUPLE_(), GTEST_3_TUPLE_(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
tuple std::tr1::make_tuple () [inline]
Referenced by testing::internal::FunctionMocker< R(A1)>::With(), testing::internal::FunctionMocker< R(A1, A2)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With(), and testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>::With().
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) > bool std::tr1::operator!= (const GTEST_10_TUPLE_(T)& t, const GTEST_10_TUPLE_(U)& u) [inline]
template<GTEST_10_TYPENAMES_(T) , GTEST_10_TYPENAMES_(U) > bool std::tr1::operator== (const GTEST_10_TUPLE_(T)& t, const GTEST_10_TUPLE_(U)& u) [inline]
References testing::Eq(), and std::tr1::tuple_size< GTEST_10_TUPLE_(T) >::value.