ZNC: swigpyrun.h File Reference
swigpyrun.h File Reference
#include <string.h>
Classes
struct swig_type_info
struct swig_cast_info
struct swig_module_info
struct PyHeapTypeObject
struct swig_const_info
struct SwigPyClientData
struct SwigPyObject
struct SwigPyPacked
Defines
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGINLINE
#define SWIGUNUSED
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGEXPORT
#define SWIGSTDCALL
#define SWIG_UnknownError -1
#define SWIG_IOError -2
#define SWIG_RuntimeError -3
#define SWIG_IndexError -4
#define SWIG_TypeError -5
#define SWIG_DivisionByZero -6
#define SWIG_OverflowError -7
#define SWIG_SyntaxError -8
#define SWIG_ValueError -9
#define SWIG_SystemError -10
#define SWIG_AttributeError -11
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
#define SWIG_RUNTIME_VERSION "4"
#define SWIG_TYPE_TABLE_NAME
#define SWIGRUNTIME SWIGINTERN
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIG_BUFFER_SIZE 1024
#define SWIG_POINTER_DISOWN 0x1
#define SWIG_CAST_NEW_MEMORY 0x2
#define SWIG_POINTER_OWN 0x1
#define SWIG_OK (0)
#define SWIG_ERROR (-1)
#define SWIG_IsOK(r) (r >= 0)
#define SWIG_ArgError(r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_AddNewMask(r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_AddCast
#define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#define Py_TYPE(op) ((op)->ob_type)
#define SWIG_Python_str_FromFormat PyString_FromFormat
#define SWIG_Python_str_DelForPy3(x)
#define PyOS_snprintf snprintf
#define SWIG_PYBUFFER_SIZE 1024
#define PyObject_Del(op) PyMem_DEL((op))
#define PyObject_DEL PyObject_Del
#define PyExc_StopIteration PyExc_RuntimeError
#define PyObject_GenericGetAttr 0
#define Py_NotImplemented PyExc_RuntimeError
#define PyString_AsStringAndSize(obj, s, len) {*s = PyString_AsString(obj); *len = *s ? strlen(*s) : 0;}
#define PySequence_Size PySequence_Length
#define PY_SSIZE_T_MAX INT_MAX
#define PY_SSIZE_T_MIN INT_MIN
#define Py_VISIT(op)
#define PyDescr_TYPE(x) (((PyDescrObject *)(x))->d_type)
#define PyDescr_NAME(x) (((PyDescrObject *)(x))->d_name)
#define SWIG_PYTHON_INITIALIZE_THREADS
#define SWIG_PYTHON_THREAD_BEGIN_BLOCK
#define SWIG_PYTHON_THREAD_END_BLOCK
#define SWIG_PYTHON_THREAD_BEGIN_ALLOW
#define SWIG_PYTHON_THREAD_END_ALLOW
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY 5
#define SWIG_Python_ConvertPtr(obj, pptr, type, flags) SWIG_Python_ConvertPtrAndOwn(obj, pptr, type, flags, 0)
#define SWIG_ConvertPtr(obj, pptr, type, flags) SWIG_Python_ConvertPtr(obj, pptr, type, flags)
#define SWIG_ConvertPtrAndOwn(obj, pptr, type, flags, own) SWIG_Python_ConvertPtrAndOwn(obj, pptr, type, flags, own)
#define SWIG_NewPointerObj(ptr, type, flags) SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
#define SWIG_InternalNewPointerObj(ptr, type, flags) SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
#define SWIG_CheckImplicit(ty) SWIG_Python_CheckImplicit(ty)
#define SWIG_AcquirePtr(ptr, src) SWIG_Python_AcquirePtr(ptr, src)
#define swig_owntype int
#define SWIG_ConvertPacked(obj, ptr, sz, ty) SWIG_Python_ConvertPacked(obj, ptr, sz, ty)
#define SWIG_NewPackedObj(ptr, sz, type) SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_ConvertInstance(obj, pptr, type, flags) SWIG_ConvertPtr(obj, pptr, type, flags)
#define SWIG_NewInstanceObj(ptr, type, flags) SWIG_NewPointerObj(ptr, type, flags)
#define SWIG_ConvertFunctionPtr(obj, pptr, type) SWIG_Python_ConvertFunctionPtr(obj, pptr, type)
#define SWIG_NewFunctionPtrObj(ptr, type) SWIG_Python_NewPointerObj(NULL, ptr, type, 0)
#define SWIG_ConvertMember(obj, ptr, sz, ty) SWIG_Python_ConvertPacked(obj, ptr, sz, ty)
#define SWIG_NewMemberObj(ptr, sz, type) SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_GetModule(clientdata) SWIG_Python_GetModule()
#define SWIG_SetModule(clientdata, pointer) SWIG_Python_SetModule(pointer)
#define SWIG_NewClientData(obj) SwigPyClientData_New(obj)
#define SWIG_SetErrorObj SWIG_Python_SetErrorObj
#define SWIG_SetErrorMsg SWIG_Python_SetErrorMsg
#define SWIG_ErrorType(code) SWIG_Python_ErrorType(code)
#define SWIG_Error(code, msg) SWIG_Python_SetErrorMsg(SWIG_ErrorType(code), msg)
#define SWIG_fail goto fail
#define SWIG_Python_Raise(obj, type, desc) SWIG_Python_SetErrorObj(SWIG_Python_ExceptionType(desc), obj)
#define SWIG_Python_CallFunctor(functor, obj) PyObject_CallFunction(functor, "O", obj);
#define SWIG_STATIC_POINTER(var) var = 0; if (!var) var
#define SWIG_POINTER_NOSHADOW (SWIG_POINTER_OWN << 1)
#define SWIG_POINTER_NEW (SWIG_POINTER_NOSHADOW | SWIG_POINTER_OWN)
#define SWIG_POINTER_IMPLICIT_CONV (SWIG_POINTER_DISOWN << 1)
#define SWIG_BUILTIN_TP_INIT (SWIG_POINTER_OWN << 2)
#define SWIG_BUILTIN_INIT (SWIG_BUILTIN_TP_INIT | SWIG_POINTER_OWN)
#define SWIG_POINTER_EXCEPTION 0
#define SWIG_arg_fail(arg) SWIG_Python_ArgFail(arg)
#define SWIG_MustGetPtr(p, type, argnum, flags) SWIG_Python_MustGetPtr(p, type, argnum, flags)
Typedefs
typedef void *(* swig_converter_func)(void *, int *)
typedef struct swig_type_info *(* swig_dycast_func)(void **)
typedef struct swig_type_info swig_type_info
typedef struct swig_cast_info swig_cast_info
typedef struct swig_module_info swig_module_info
typedef int Py_ssize_t
typedef inquiry lenfunc
typedef intargfunc ssizeargfunc
typedef intintargfunc ssizessizeargfunc
typedef intobjargproc ssizeobjargproc
typedef intintobjargproc ssizessizeobjargproc
typedef getreadbufferproc readbufferproc
typedef getwritebufferproc writebufferproc
typedef getsegcountproc segcountproc
typedef getcharbufferproc charbufferproc
typedef destructor freefunc
typedef struct swig_const_info swig_const_info
Functions
SWIGRUNTIME int SWIG_TypeNameComp (const char *f1, const char *l1, const char *f2, const char *l2)
SWIGRUNTIME int SWIG_TypeEquiv (const char *nb, const char *tb)
SWIGRUNTIME int SWIG_TypeCompare (const char *nb, const char *tb)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheck (const char *c, swig_type_info *ty)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheckStruct (swig_type_info *from, swig_type_info *ty)
SWIGRUNTIMEINLINE void * SWIG_TypeCast (swig_cast_info *ty, void *ptr, int *newmemory)
SWIGRUNTIME swig_type_info * SWIG_TypeDynamicCast (swig_type_info *ty, void **ptr)
SWIGRUNTIMEINLINE const char * SWIG_TypeName (const swig_type_info *ty)
SWIGRUNTIME const char * SWIG_TypePrettyName (const swig_type_info *type)
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME swig_type_info * SWIG_MangledTypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME swig_type_info * SWIG_TypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME char * SWIG_PackData (char *c, void *ptr, size_t sz)
SWIGRUNTIME const char * SWIG_UnpackData (const char *c, void *ptr, size_t sz)
SWIGRUNTIME char * SWIG_PackVoidPtr (char *buff, void *ptr, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackVoidPtr (const char *c, void **ptr, const char *name)
SWIGRUNTIME char * SWIG_PackDataName (char *buff, void *ptr, size_t sz, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackDataName (const char *c, void *ptr, size_t sz, const char *name)
SWIGINTERN char * SWIG_Python_str_AsChar (PyObject *str)
SWIGINTERN PyObject * SWIG_Python_str_FromChar (const char *c)
SWIGRUNTIME PyObject * SWIG_Python_ErrorType (int code)
SWIGRUNTIME void SWIG_Python_AddErrorMsg (const char *mesg)
SWIGRUNTIME PyObject * SWIG_PyInstanceMethod_New (PyObject *SWIGUNUSEDPARM(self), PyObject *SWIGUNUSEDPARM(func))
SWIGINTERN void SWIG_Python_SetErrorObj (PyObject *errtype, PyObject *obj)
SWIGINTERN void SWIG_Python_SetErrorMsg (PyObject *errtype, const char *msg)
SWIGINTERN void SWIG_Python_SetConstant (PyObject *d, const char *name, PyObject *obj)
SWIGINTERN PyObject * SWIG_Python_AppendOutput (PyObject *result, PyObject *obj)
SWIGINTERN int SWIG_Python_UnpackTuple (PyObject *args, const char *name, Py_ssize_t min, Py_ssize_t max, PyObject **objs)
SWIGRUNTIMEINLINE PyObject * SWIG_Py_Void (void)
SWIGRUNTIMEINLINE int SWIG_Python_CheckImplicit (swig_type_info *ty)
SWIGRUNTIMEINLINE PyObject * SWIG_Python_ExceptionType (swig_type_info *desc)
SWIGRUNTIME SwigPyClientData * SwigPyClientData_New (PyObject *obj)
SWIGRUNTIME void SwigPyClientData_Del (SwigPyClientData *data)
SWIGRUNTIME PyObject * SwigPyObject_long (SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_format (const char *fmt, SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_oct (SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_hex (SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_repr (SwigPyObject *v, PyObject *args)
SWIGRUNTIME int SwigPyObject_print (SwigPyObject *v, FILE *fp, int SWIGUNUSEDPARM(flags))
SWIGRUNTIME PyObject * SwigPyObject_str (SwigPyObject *v)
SWIGRUNTIME int SwigPyObject_compare (SwigPyObject *v, SwigPyObject *w)
SWIGRUNTIME PyObject * SwigPyObject_richcompare (SwigPyObject *v, SwigPyObject *w, int op)
SWIGRUNTIME PyTypeObject * SwigPyObject_TypeOnce (void)
SWIGRUNTIME PyTypeObject * SwigPyObject_type (void)
SWIGRUNTIMEINLINE int SwigPyObject_Check (PyObject *op)
SWIGRUNTIME PyObject * SwigPyObject_New (void *ptr, swig_type_info *ty, int own)
SWIGRUNTIME void SwigPyObject_dealloc (PyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_append (PyObject *v, PyObject *next)
SWIGRUNTIME PyObject * SwigPyObject_next (PyObject *v, PyObject *SWIGUNUSEDPARM(args))
SWIGINTERN PyObject * SwigPyObject_disown (PyObject *v, PyObject *SWIGUNUSEDPARM(args))
SWIGINTERN PyObject * SwigPyObject_acquire (PyObject *v, PyObject *SWIGUNUSEDPARM(args))
SWIGINTERN PyObject * SwigPyObject_own (PyObject *v, PyObject *args)
SWIGINTERN PyObject * SwigPyObject_getattr (SwigPyObject *sobj, char *name)
SWIGRUNTIME int SwigPyPacked_print (SwigPyPacked *v, FILE *fp, int SWIGUNUSEDPARM(flags))
SWIGRUNTIME PyObject * SwigPyPacked_repr (SwigPyPacked *v)
SWIGRUNTIME PyObject * SwigPyPacked_str (SwigPyPacked *v)
SWIGRUNTIME int SwigPyPacked_compare (SwigPyPacked *v, SwigPyPacked *w)
SWIGRUNTIME PyTypeObject * SwigPyPacked_TypeOnce (void)
SWIGRUNTIME PyTypeObject * SwigPyPacked_type (void)
SWIGRUNTIMEINLINE int SwigPyPacked_Check (PyObject *op)
SWIGRUNTIME void SwigPyPacked_dealloc (PyObject *v)
SWIGRUNTIME PyObject * SwigPyPacked_New (void *ptr, size_t size, swig_type_info *ty)
SWIGRUNTIME swig_type_info * SwigPyPacked_UnpackData (PyObject *obj, void *ptr, size_t size)
SWIGRUNTIMEINLINE PyObject * _SWIG_This (void)
SWIGRUNTIME PyObject * SWIG_This (void)
SWIGRUNTIME SwigPyObject * SWIG_Python_GetSwigThis (PyObject *pyobj)
SWIGRUNTIME int SWIG_Python_AcquirePtr (PyObject *obj, int own)
SWIGRUNTIME int SWIG_Python_ConvertPtrAndOwn (PyObject *obj, void **ptr, swig_type_info *ty, int flags, int *own)
SWIGRUNTIME int SWIG_Python_ConvertFunctionPtr (PyObject *obj, void **ptr, swig_type_info *ty)
SWIGRUNTIME int SWIG_Python_ConvertPacked (PyObject *obj, void *ptr, size_t sz, swig_type_info *ty)
SWIGRUNTIME PyObject * SWIG_Python_NewShadowInstance (SwigPyClientData *data, PyObject *swig_this)
SWIGRUNTIME void SWIG_Python_SetSwigThis (PyObject *inst, PyObject *swig_this)
SWIGINTERN PyObject * SWIG_Python_InitShadowInstance (PyObject *args)
SWIGRUNTIME PyObject * SWIG_Python_NewPointerObj (PyObject *self, void *ptr, swig_type_info *type, int flags)
SWIGRUNTIMEINLINE PyObject * SWIG_Python_NewPackedObj (void *ptr, size_t sz, swig_type_info *type)
SWIGRUNTIME swig_module_info * SWIG_Python_GetModule (void)
SWIGINTERN int PyModule_AddObject (PyObject *m, char *name, PyObject *o)
SWIGRUNTIME void SWIG_Python_DestroyModule (void *vptr)
SWIGRUNTIME void SWIG_Python_SetModule (swig_module_info *swig_module)
SWIGRUNTIME PyObject * SWIG_Python_TypeCache (void)
SWIGRUNTIME swig_type_info * SWIG_Python_TypeQuery (const char *type)
SWIGRUNTIME int SWIG_Python_AddErrMesg (const char *mesg, int infront)
SWIGRUNTIME int SWIG_Python_ArgFail (int argnum)
SWIGRUNTIMEINLINE const char * SwigPyObject_GetDesc (PyObject *self)
SWIGRUNTIME void SWIG_Python_TypeError (const char *type, PyObject *obj)
SWIGRUNTIME void * SWIG_Python_MustGetPtr (PyObject *obj, swig_type_info *ty, int SWIGUNUSEDPARM(argnum), int flags)
SWIGRUNTIMEINLINE swig_type_info * SWIG_TypeQuery (const char *name)
SWIGRUNTIMEINLINE swig_type_info * SWIG_MangledTypeQuery (const char *name)
Define Documentation
#define Py_NotImplemented PyExc_RuntimeError
Referenced by SwigPyObject_richcompare().
#define PY_SSIZE_T_MAX INT_MAX
#define PY_SSIZE_T_MIN INT_MIN
#define Py_TYPE (op) ((op)->ob_type)
Referenced by SWIG_Python_NewShadowInstance(), and SwigPyObject_Check().
#define Py_VISIT (op)
Value:
do {                                            \
    if (op) {                                   \
      int vret = visit((op), arg);              \
      if (vret)                                 \
        return vret;                            \
    }                                           \
  } while (0)
#define PyDescr_NAME (x) (((PyDescrObject *)(x))->d_name)
#define PyDescr_TYPE (x) (((PyDescrObject *)(x))->d_type)
#define PyExc_StopIteration PyExc_RuntimeError
#define PyObject_Del (op) PyMem_DEL((op))
#define PyObject_DEL PyObject_Del
Referenced by SwigPyObject_dealloc(), SwigPyPacked_dealloc(), and SwigPyPacked_New().
#define PyObject_GenericGetAttr 0
Referenced by SwigPyObject_TypeOnce(), and SwigPyPacked_TypeOnce().
#define PyOS_snprintf snprintf
Referenced by SWIG_Python_ArgFail().
#define PySequence_Size PySequence_Length
#define PyString_AsStringAndSize (obj, s, len) {*s = PyString_AsString(obj); *len = *s ? strlen(*s) : 0;}
#define SWIG_AcquirePtr (ptr, src) SWIG_Python_AcquirePtr(ptr, src)
#define SWIG_AddCast
Referenced by SWIG_Python_ConvertPtrAndOwn().
#define SWIG_AddNewMask (r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
Referenced by SWIG_Python_ConvertPtrAndOwn().
#define SWIG_AddTmpMask (r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_arg_fail (arg) SWIG_Python_ArgFail(arg)
#define SWIG_ArgError (r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_AttributeError -11
Referenced by SWIG_Python_ErrorType().
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_BUFFER_SIZE 1024
Referenced by SwigPyObject_str(), SwigPyPacked_print(), SwigPyPacked_repr(), and SwigPyPacked_str().
#define SWIG_BUILTIN_INIT (SWIG_BUILTIN_TP_INIT | SWIG_POINTER_OWN)
#define SWIG_BUILTIN_TP_INIT (SWIG_POINTER_OWN << 2)
Referenced by SWIG_Python_NewPointerObj().
#define SWIG_CAST_NEW_MEMORY 0x2
Referenced by SWIG_Python_ConvertPtrAndOwn().
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_CheckImplicit (ty) SWIG_Python_CheckImplicit(ty)
#define SWIG_CheckState (r) (SWIG_IsOK(r) ? 1 : 0)
#define SWIG_ConvertFunctionPtr (obj, pptr, type) SWIG_Python_ConvertFunctionPtr(obj, pptr, type)
#define SWIG_ConvertInstance (obj, pptr, type, flags) SWIG_ConvertPtr(obj, pptr, type, flags)
#define SWIG_ConvertMember (obj, ptr, sz, ty) SWIG_Python_ConvertPacked(obj, ptr, sz, ty)
#define SWIG_ConvertPacked (obj, ptr, sz, ty) SWIG_Python_ConvertPacked(obj, ptr, sz, ty)
#define SWIG_ConvertPtr (obj, pptr, type, flags) SWIG_Python_ConvertPtr(obj, pptr, type, flags)
Referenced by SWIG_Python_ConvertFunctionPtr().
#define SWIG_ConvertPtrAndOwn (obj, pptr, type, flags, own) SWIG_Python_ConvertPtrAndOwn(obj, pptr, type, flags, own)
#define SWIG_DelNewMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_DelTmpMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_DivisionByZero -6
Referenced by SWIG_Python_ErrorType().
#define SWIG_ERROR (-1)
Referenced by PyModule_AddObject(), SWIG_Python_ConvertFunctionPtr(), SWIG_Python_ConvertPacked(), and SWIG_Python_ConvertPtrAndOwn().
#define SWIG_Error (code, msg) SWIG_Python_SetErrorMsg(SWIG_ErrorType(code), msg)
#define SWIG_ErrorType (code) SWIG_Python_ErrorType(code)
#define SWIG_fail goto fail
#define SWIG_GetModule (clientdata) SWIG_Python_GetModule()
Referenced by SWIG_MangledTypeQuery(), and SWIG_TypeQuery().
#define SWIG_IndexError -4
Referenced by SWIG_Python_ErrorType().
#define SWIG_InternalNewPointerObj (ptr, type, flags) SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
#define SWIG_IOError -2
Referenced by SWIG_Python_ErrorType().
#define SWIG_IsNewObj (r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_IsOK (r) (r >= 0)
Referenced by SWIG_Python_ConvertPtrAndOwn().
#define SWIG_IsTmpObj (r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_MemoryError -12
Referenced by SWIG_Python_ErrorType().
#define SWIG_MustGetPtr (p, type, argnum, flags) SWIG_Python_MustGetPtr(p, type, argnum, flags)
#define SWIG_NewClientData (obj) SwigPyClientData_New(obj)
#define SWIG_NewFunctionPtrObj (ptr, type) SWIG_Python_NewPointerObj(NULL, ptr, type, 0)
#define SWIG_NewInstanceObj (ptr, type, flags) SWIG_NewPointerObj(ptr, type, flags)
#define SWIG_NewMemberObj (ptr, sz, type) SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_NewPackedObj (ptr, sz, type) SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_NewPointerObj (ptr, type, flags) SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
#define SWIG_NullReferenceError -13
#define SWIG_OK (0)
Referenced by PyModule_AddObject(), SWIG_Python_ConvertFunctionPtr(), SWIG_Python_ConvertPacked(), and SWIG_Python_ConvertPtrAndOwn().
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_OverflowError -7
Referenced by SWIG_Python_ErrorType().
#define swig_owntype int
#define SWIG_POINTER_DISOWN 0x1
Referenced by SWIG_Python_ConvertPtrAndOwn().
#define SWIG_POINTER_EXCEPTION 0
#define SWIG_POINTER_IMPLICIT_CONV (SWIG_POINTER_DISOWN << 1)
Referenced by SWIG_Python_ConvertPtrAndOwn().
#define SWIG_POINTER_NEW (SWIG_POINTER_NOSHADOW | SWIG_POINTER_OWN)
#define SWIG_POINTER_NOSHADOW (SWIG_POINTER_OWN << 1)
Referenced by SWIG_Python_NewPointerObj().
#define SWIG_POINTER_OWN 0x1
Referenced by SWIG_Python_AcquirePtr(), SWIG_Python_NewPointerObj(), SwigPyObject_acquire(), and SwigPyObject_dealloc().
#define SWIG_PY_BINARY 5
#define SWIG_PY_POINTER 4
#define SWIG_PYBUFFER_SIZE 1024
#define SWIG_Python_CallFunctor (functor, obj) PyObject_CallFunction(functor, "O", obj);
Referenced by SWIG_Python_ConvertPtrAndOwn(), and SwigPyObject_dealloc().
#define SWIG_Python_ConvertPtr (obj, pptr, type, flags) SWIG_Python_ConvertPtrAndOwn(obj, pptr, type, flags, 0)
Referenced by SWIG_Python_MustGetPtr().
#define SWIG_PYTHON_INITIALIZE_THREADS
#define SWIG_Python_Raise (obj, type, desc) SWIG_Python_SetErrorObj(SWIG_Python_ExceptionType(desc), obj)
#define SWIG_Python_str_DelForPy3 (x)
Referenced by SWIG_Python_AddErrMesg(), SWIG_Python_AddErrorMsg(), SWIG_Python_TypeError(), and SwigPyObject_print().
#define SWIG_Python_str_FromFormat PyString_FromFormat
Referenced by SwigPyObject_repr(), SwigPyPacked_repr(), and SwigPyPacked_str().
#define SWIG_PYTHON_THREAD_BEGIN_ALLOW
#define SWIG_PYTHON_THREAD_BEGIN_BLOCK
Referenced by SWIG_Python_SetErrorMsg(), and SWIG_Python_SetErrorObj().
#define SWIG_PYTHON_THREAD_END_ALLOW
#define SWIG_PYTHON_THREAD_END_BLOCK
Referenced by SWIG_Python_SetErrorMsg(), and SWIG_Python_SetErrorObj().
#define SWIG_RUNTIME_VERSION "4"
Referenced by SWIG_Python_GetModule(), and SWIG_Python_SetModule().
#define SWIG_RuntimeError -3
Referenced by SWIG_Python_ErrorType().
#define SWIG_SetErrorMsg SWIG_Python_SetErrorMsg
#define SWIG_SetErrorObj SWIG_Python_SetErrorObj
#define SWIG_SetModule (clientdata, pointer) SWIG_Python_SetModule(pointer)
#define SWIG_STATIC_POINTER (var) var = 0; if (!var) var
Referenced by SWIG_Python_TypeCache(), SwigPyObject_type(), and SwigPyPacked_type().
#define SWIG_SyntaxError -8
Referenced by SWIG_Python_ErrorType().
#define SWIG_SystemError -10
Referenced by SWIG_Python_ErrorType().
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_TYPE_TABLE_NAME
Referenced by SWIG_Python_GetModule(), and SWIG_Python_SetModule().
#define SWIG_TypeError -5
Referenced by SWIG_Python_ErrorType().
#define SWIG_UnknownError -1
#define SWIG_ValueError -9
Referenced by SWIG_Python_ErrorType().
#define SWIGEXPORT
#define SWIGINLINE
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGRUNTIME SWIGINTERN
Referenced by SwigPyObject_TypeOnce(), and SwigPyPacked_TypeOnce().
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIGSTDCALL
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGUNUSED
#define SWIGUNUSEDPARM (p) p SWIGUNUSED
Typedef Documentation
typedef getcharbufferproc charbufferproc
typedef destructor freefunc
typedef inquiry lenfunc
typedef int Py_ssize_t
typedef getreadbufferproc readbufferproc
typedef getsegcountproc segcountproc
typedef intargfunc ssizeargfunc
typedef intobjargproc ssizeobjargproc
typedef intintargfunc ssizessizeargfunc
typedef intintobjargproc ssizessizeobjargproc
typedef struct swig_cast_info swig_cast_info
typedef struct swig_const_info swig_const_info
typedef void*(* swig_converter_func)(void *, int *)
typedef struct swig_type_info*(* swig_dycast_func)(void **)
typedef struct swig_module_info swig_module_info
typedef struct swig_type_info swig_type_info
typedef getwritebufferproc writebufferproc
Function Documentation
SWIGRUNTIMEINLINE PyObject* _SWIG_This (void)
References SWIG_Python_str_FromChar().
Referenced by SWIG_This().
SWIGINTERN int PyModule_AddObject (PyObject * m, char * name, PyObject * o)
References SWIG_ERROR, and SWIG_OK.
Referenced by SWIG_Python_SetModule().
SWIGRUNTIMEINLINE swig_type_info* SWIG_MangledTypeQuery (const char * name)
References SWIG_GetModule, and SWIG_MangledTypeQueryModule().
SWIGRUNTIME swig_type_info* SWIG_MangledTypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
References swig_type_info::name, swig_module_info::next, swig_module_info::size, and swig_module_info::types.
SWIGRUNTIME char* SWIG_PackData (char * c, void * ptr, size_t sz)
SWIGRUNTIME char* SWIG_PackDataName (char * buff, void * ptr, size_t sz, const char * name, size_t bsz)
References SWIG_PackData().
SWIGRUNTIME char* SWIG_PackVoidPtr (char * buff, void * ptr, const char * name, size_t bsz)
References SWIG_PackData().
SWIGRUNTIMEINLINE PyObject* SWIG_Py_Void (void)
Referenced by SWIG_Python_InitShadowInstance(), SWIG_Python_NewPackedObj(), SWIG_Python_NewPointerObj(), SwigPyObject_acquire(), SwigPyObject_append(), SwigPyObject_disown(), and SwigPyObject_next().
SWIGRUNTIME PyObject* SWIG_PyInstanceMethod_New (PyObject * SWIGUNUSEDPARMself, PyObject * SWIGUNUSEDPARMfunc)
SWIGRUNTIME int SWIG_Python_AcquirePtr (PyObject * obj, int own)
References SwigPyObject::own, SWIG_POINTER_OWN, and SWIG_Python_GetSwigThis().
SWIGRUNTIME int SWIG_Python_AddErrMesg (const char * mesg, int infront)
References SWIG_Python_str_AsChar(), and SWIG_Python_str_DelForPy3.
Referenced by SWIG_Python_ArgFail().
SWIGRUNTIME void SWIG_Python_AddErrorMsg (const char * mesg)
References SWIG_Python_str_AsChar(), and SWIG_Python_str_DelForPy3.
SWIGINTERN PyObject* SWIG_Python_AppendOutput (PyObject * result, PyObject * obj)
SWIGRUNTIME int SWIG_Python_ArgFail (int argnum)
References PyOS_snprintf, and SWIG_Python_AddErrMesg().
Referenced by SWIG_Python_MustGetPtr().
SWIGRUNTIMEINLINE int SWIG_Python_CheckImplicit (swig_type_info * ty)
References swig_type_info::clientdata, and SwigPyClientData::implicitconv.
SWIGRUNTIME int SWIG_Python_ConvertFunctionPtr (PyObject * obj, void ** ptr, swig_type_info * ty)
References swig_type_info::name, SWIG_ConvertPtr, SWIG_ERROR, SWIG_OK, SWIG_TypeCast(), SWIG_TypeCheck(), and SWIG_UnpackVoidPtr().
SWIGRUNTIME int SWIG_Python_ConvertPacked (PyObject * obj, void * ptr, size_t sz, swig_type_info * ty)
References swig_type_info::name, SWIG_ERROR, SWIG_OK, SWIG_TypeCheck(), and SwigPyPacked_UnpackData().
SWIGRUNTIME int SWIG_Python_ConvertPtrAndOwn (PyObject * obj, void ** ptr, swig_type_info * ty, int flags, int * own)
References swig_type_info::clientdata, SwigPyClientData::implicitconv, SwigPyClientData::klass, swig_type_info::name, SwigPyObject::next, SwigPyObject::own, SwigPyObject::ptr, SWIG_AddCast, SWIG_AddNewMask, SWIG_CAST_NEW_MEMORY, SWIG_ERROR, SWIG_IsOK, SWIG_OK, SWIG_POINTER_DISOWN, SWIG_POINTER_IMPLICIT_CONV, SWIG_Python_CallFunctor, SWIG_Python_GetSwigThis(), SWIG_TypeCast(), SWIG_TypeCheck(), and SwigPyObject::ty.
SWIGRUNTIME void SWIG_Python_DestroyModule (void * vptr)
References swig_type_info::clientdata, swig_type_info::owndata, swig_module_info::size, SWIG_This(), SwigPyClientData_Del(), and swig_module_info::types.
Referenced by SWIG_Python_SetModule().
SWIGRUNTIME PyObject* SWIG_Python_ErrorType (int code)
References SWIG_AttributeError, SWIG_DivisionByZero, SWIG_IndexError, SWIG_IOError, SWIG_MemoryError, SWIG_OverflowError, SWIG_RuntimeError, SWIG_SyntaxError, SWIG_SystemError, SWIG_TypeError, and SWIG_ValueError.
SWIGRUNTIMEINLINE PyObject* SWIG_Python_ExceptionType (swig_type_info * desc)
References swig_type_info::clientdata, and SwigPyClientData::klass.
SWIGRUNTIME swig_module_info* SWIG_Python_GetModule (void)
References SWIG_RUNTIME_VERSION, and SWIG_TYPE_TABLE_NAME.
Referenced by SWIG_Python_TypeQuery().
SWIGRUNTIME SwigPyObject* SWIG_Python_GetSwigThis (PyObject * pyobj)
References SWIG_This(), and SwigPyObject_Check().
Referenced by SWIG_Python_AcquirePtr(), SWIG_Python_ConvertPtrAndOwn(), and SWIG_Python_InitShadowInstance().
SWIGINTERN PyObject* SWIG_Python_InitShadowInstance (PyObject * args)
References SWIG_Py_Void(), SWIG_Python_GetSwigThis(), SWIG_Python_SetSwigThis(), SWIG_Python_UnpackTuple(), and SwigPyObject_append().
SWIGRUNTIME void* SWIG_Python_MustGetPtr (PyObject * obj, swig_type_info * ty, int SWIGUNUSEDPARMargnum, int flags)
References SWIG_Python_ArgFail(), SWIG_Python_ConvertPtr, SWIG_Python_TypeError(), and SWIG_TypePrettyName().
SWIGRUNTIMEINLINE PyObject* SWIG_Python_NewPackedObj (void * ptr, size_t sz, swig_type_info * type)
References SWIG_Py_Void(), and SwigPyPacked_New().
SWIGRUNTIME PyObject* SWIG_Python_NewPointerObj (PyObject * self, void * ptr, swig_type_info * type, int flags)
References swig_type_info::clientdata, SwigPyObject::next, SwigPyObject::own, SwigPyObject::ptr, SwigPyClientData::pytype, SWIG_BUILTIN_TP_INIT, SWIG_POINTER_NOSHADOW, SWIG_POINTER_OWN, SWIG_Py_Void(), SWIG_Python_NewShadowInstance(), SwigPyObject_New(), and SwigPyObject::ty.
SWIGRUNTIME PyObject* SWIG_Python_NewShadowInstance (SwigPyClientData * data, PyObject * swig_this)
References SwigPyClientData::newargs, SwigPyClientData::newraw, Py_TYPE, and SWIG_This().
Referenced by SWIG_Python_NewPointerObj().
SWIGINTERN void SWIG_Python_SetConstant (PyObject * d, const char * name, PyObject * obj)
SWIGINTERN void SWIG_Python_SetErrorMsg (PyObject * errtype, const char * msg)
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
SWIGINTERN void SWIG_Python_SetErrorObj (PyObject * errtype, PyObject * obj)
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
SWIGRUNTIME void SWIG_Python_SetModule (swig_module_info * swig_module)
References PyModule_AddObject(), SWIG_Python_DestroyModule(), SWIG_RUNTIME_VERSION, and SWIG_TYPE_TABLE_NAME.
SWIGRUNTIME void SWIG_Python_SetSwigThis (PyObject * inst, PyObject * swig_this)
References SWIG_This().
Referenced by SWIG_Python_InitShadowInstance().
SWIGINTERN char* SWIG_Python_str_AsChar (PyObject * str)
Referenced by SWIG_Python_AddErrMesg(), SWIG_Python_AddErrorMsg(), SWIG_Python_TypeError(), and SwigPyObject_print().
SWIGINTERN PyObject* SWIG_Python_str_FromChar (const char * c)
Referenced by _SWIG_This(), SWIG_Python_TypeQuery(), SwigPyObject_format(), SwigPyObject_str(), and SwigPyPacked_str().
SWIGRUNTIME PyObject* SWIG_Python_TypeCache (void)
References SWIG_STATIC_POINTER.
Referenced by SWIG_Python_TypeQuery().
SWIGRUNTIME void SWIG_Python_TypeError (const char * type, PyObject * obj)
References SWIG_Python_str_AsChar(), SWIG_Python_str_DelForPy3, SwigPyObject_Check(), and SwigPyObject_GetDesc().
Referenced by SWIG_Python_MustGetPtr().
SWIGRUNTIME swig_type_info* SWIG_Python_TypeQuery (const char * type)
References SWIG_Python_GetModule(), SWIG_Python_str_FromChar(), SWIG_Python_TypeCache(), and SWIG_TypeQueryModule().
SWIGINTERN int SWIG_Python_UnpackTuple (PyObject * args, const char * name, Py_ssize_t min, Py_ssize_t max, PyObject ** objs)
Referenced by SWIG_Python_InitShadowInstance().
SWIGRUNTIME PyObject* SWIG_This (void)
References _SWIG_This().
Referenced by SWIG_Python_DestroyModule(), SWIG_Python_GetSwigThis(), SWIG_Python_NewShadowInstance(), and SWIG_Python_SetSwigThis().
SWIGRUNTIMEINLINE void* SWIG_TypeCast (swig_cast_info * ty, void * ptr, int * newmemory)
References swig_cast_info::converter.
SWIGRUNTIME swig_cast_info* SWIG_TypeCheck (const char * c, swig_type_info * ty)
References swig_type_info::cast, swig_type_info::name, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
SWIGRUNTIME swig_cast_info* SWIG_TypeCheckStruct (swig_type_info * from, swig_type_info * ty)
References swig_type_info::cast, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info * ti, void * clientdata)
References swig_type_info::cast, swig_type_info::clientdata, swig_module_info::clientdata, swig_cast_info::converter, swig_cast_info::next, SWIG_TypeClientData(), and swig_cast_info::type.
SWIGRUNTIME int SWIG_TypeCompare (const char * nb, const char * tb)
References SWIG_TypeNameComp().
SWIGRUNTIME swig_type_info* SWIG_TypeDynamicCast (swig_type_info * ty, void ** ptr)
References swig_type_info::dcast.
SWIGRUNTIME int SWIG_TypeEquiv (const char * nb, const char * tb)
References SWIG_TypeNameComp().
SWIGRUNTIMEINLINE const char* SWIG_TypeName (const swig_type_info * ty)
References swig_type_info::name.
SWIGRUNTIME int SWIG_TypeNameComp (const char * f1, const char * l1, const char * f2, const char * l2)
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info * ti, void * clientdata)
References swig_type_info::owndata, and SWIG_TypeClientData().
SWIGRUNTIME const char* SWIG_TypePrettyName (const swig_type_info * type)
References swig_type_info::name, and swig_type_info::str.
SWIGRUNTIMEINLINE swig_type_info* SWIG_TypeQuery (const char * name)
References SWIG_GetModule, and SWIG_TypeQueryModule().
SWIGRUNTIME swig_type_info* SWIG_TypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
References swig_module_info::next, swig_module_info::size, swig_type_info::str, SWIG_MangledTypeQueryModule(), SWIG_TypeEquiv(), and swig_module_info::types.
SWIGRUNTIME const char* SWIG_UnpackData (const char * c, void * ptr, size_t sz)
SWIGRUNTIME const char* SWIG_UnpackDataName (const char * c, void * ptr, size_t sz, const char * name)
References SWIG_UnpackData().
SWIGRUNTIME const char* SWIG_UnpackVoidPtr (const char * c, void ** ptr, const char * name)
References SWIG_UnpackData().
SWIGRUNTIME void SwigPyClientData_Del (SwigPyClientData * data)
References SwigPyClientData::destroy, SwigPyClientData::newargs, and SwigPyClientData::newraw.
Referenced by SWIG_Python_DestroyModule().
SWIGRUNTIME SwigPyClientData* SwigPyClientData_New (PyObject * obj)
References SwigPyClientData::delargs, SwigPyClientData::destroy, SwigPyClientData::implicitconv, SwigPyClientData::klass, SwigPyClientData::newargs, SwigPyClientData::newraw, and SwigPyClientData::pytype.
SWIGINTERN PyObject* SwigPyObject_acquire (PyObject * v, PyObject * SWIGUNUSEDPARMargs)
References SwigPyObject::own, SWIG_POINTER_OWN, and SWIG_Py_Void().
Referenced by SwigPyObject_own().
SWIGRUNTIME PyObject* SwigPyObject_append (PyObject * v, PyObject * next)
References SwigPyObject::next, SWIG_Py_Void(), and SwigPyObject_Check().
Referenced by SWIG_Python_InitShadowInstance().
SWIGRUNTIMEINLINE int SwigPyObject_Check (PyObject * op)
References Py_TYPE, and SwigPyObject_type().
Referenced by SWIG_Python_GetSwigThis(), SWIG_Python_TypeError(), and SwigPyObject_append().
SWIGRUNTIME int SwigPyObject_compare (SwigPyObject * v, SwigPyObject * w)
References SwigPyObject::ptr.
Referenced by SwigPyObject_richcompare(), and SwigPyObject_TypeOnce().
SWIGRUNTIME void SwigPyObject_dealloc (PyObject * v)
References swig_type_info::clientdata, SwigPyClientData::delargs, SwigPyClientData::destroy, SwigPyObject::next, SwigPyObject::own, SwigPyObject::ptr, PyObject_DEL, SWIG_POINTER_OWN, SWIG_Python_CallFunctor, SWIG_TypePrettyName(), SwigPyObject_New(), and SwigPyObject::ty.
Referenced by SwigPyObject_TypeOnce().
SWIGINTERN PyObject* SwigPyObject_disown (PyObject * v, PyObject * SWIGUNUSEDPARMargs)
References SwigPyObject::own, and SWIG_Py_Void().
Referenced by SwigPyObject_own().
SWIGRUNTIME PyObject* SwigPyObject_format (const char * fmt, SwigPyObject * v)
References SWIG_Python_str_FromChar(), and SwigPyObject_long().
Referenced by SwigPyObject_hex(), and SwigPyObject_oct().
SWIGINTERN PyObject* SwigPyObject_getattr (SwigPyObject * sobj, char * name)
Referenced by SwigPyObject_TypeOnce().
SWIGRUNTIMEINLINE const char* SwigPyObject_GetDesc (PyObject * self)
References swig_type_info::str, and SwigPyObject::ty.
Referenced by SWIG_Python_TypeError().
SWIGRUNTIME PyObject* SwigPyObject_hex (SwigPyObject * v)
References SwigPyObject_format().
Referenced by SwigPyObject_TypeOnce().
SWIGRUNTIME PyObject* SwigPyObject_long (SwigPyObject * v)
References SwigPyObject::ptr.
Referenced by SwigPyObject_format(), and SwigPyObject_TypeOnce().
SWIGRUNTIME PyObject * SwigPyObject_New (void * ptr, swig_type_info * ty, int own)
References SwigPyObject::next, SwigPyObject::own, SwigPyObject::ptr, SwigPyObject_type(), and SwigPyObject::ty.
Referenced by SWIG_Python_NewPointerObj(), and SwigPyObject_dealloc().
SWIGRUNTIME PyObject* SwigPyObject_next (PyObject * v, PyObject * SWIGUNUSEDPARMargs)
References SwigPyObject::next, and SWIG_Py_Void().
SWIGRUNTIME PyObject* SwigPyObject_oct (SwigPyObject * v)
References SwigPyObject_format().
Referenced by SwigPyObject_TypeOnce().
SWIGINTERN PyObject* SwigPyObject_own (PyObject * v, PyObject * args)
References SwigPyObject::own, SwigPyObject_acquire(), and SwigPyObject_disown().
SWIGRUNTIME int SwigPyObject_print (SwigPyObject * v, FILE * fp, int SWIGUNUSEDPARMflags)
References SWIG_Python_str_AsChar(), SWIG_Python_str_DelForPy3, and SwigPyObject_repr().
Referenced by SwigPyObject_TypeOnce().
SWIGRUNTIME PyObject* SwigPyObject_repr (SwigPyObject * v, PyObject * args)
References SWIG_Python_str_FromFormat, SWIG_TypePrettyName(), and SwigPyObject::ty.
Referenced by SwigPyObject_print(), and SwigPyObject_TypeOnce().
SWIGRUNTIME PyObject* SwigPyObject_richcompare (SwigPyObject * v, SwigPyObject * w, int op)
References Py_NotImplemented, and SwigPyObject_compare().
Referenced by SwigPyObject_TypeOnce().
SWIGRUNTIME PyObject* SwigPyObject_str (SwigPyObject * v)
References swig_type_info::name, SwigPyObject::ptr, SWIG_BUFFER_SIZE, SWIG_PackVoidPtr(), SWIG_Python_str_FromChar(), and SwigPyObject::ty.
Referenced by SwigPyObject_TypeOnce().
SWIGRUNTIME PyTypeObject* SwigPyObject_type (void)
References SWIG_STATIC_POINTER, and SwigPyObject_TypeOnce().
Referenced by SwigPyObject_Check(), and SwigPyObject_New().
SWIGRUNTIME PyTypeObject * SwigPyObject_TypeOnce (void)
References PyObject_GenericGetAttr, SwigPyObject_compare(), SwigPyObject_dealloc(), SwigPyObject_getattr(), SwigPyObject_hex(), SwigPyObject_long(), SwigPyObject_oct(), SwigPyObject_print(), SwigPyObject_repr(), SwigPyObject_richcompare(), SwigPyObject_str(), and SWIGRUNTIME.
Referenced by SwigPyObject_type().
SWIGRUNTIMEINLINE int SwigPyPacked_Check (PyObject * op)
References SwigPyPacked_TypeOnce().
Referenced by SwigPyPacked_dealloc(), and SwigPyPacked_UnpackData().
SWIGRUNTIME int SwigPyPacked_compare (SwigPyPacked * v, SwigPyPacked * w)
References SwigPyPacked::pack, and SwigPyPacked::size.
Referenced by SwigPyPacked_TypeOnce().
SWIGRUNTIME void SwigPyPacked_dealloc (PyObject * v)
References SwigPyPacked::pack, PyObject_DEL, and SwigPyPacked_Check().
Referenced by SwigPyPacked_TypeOnce().
SWIGRUNTIME PyObject* SwigPyPacked_New (void * ptr, size_t size, swig_type_info * ty)
References SwigPyPacked::pack, PyObject_DEL, SwigPyPacked::size, SwigPyPacked_type(), and SwigPyPacked::ty.
Referenced by SWIG_Python_NewPackedObj().
SWIGRUNTIME int SwigPyPacked_print (SwigPyPacked * v, FILE * fp, int SWIGUNUSEDPARMflags)
References swig_type_info::name, SwigPyPacked::pack, SwigPyPacked::size, SWIG_BUFFER_SIZE, SWIG_PackDataName(), and SwigPyPacked::ty.
Referenced by SwigPyPacked_TypeOnce().
SWIGRUNTIME PyObject* SwigPyPacked_repr (SwigPyPacked * v)
References swig_type_info::name, SwigPyPacked::pack, SwigPyPacked::size, SWIG_BUFFER_SIZE, SWIG_PackDataName(), SWIG_Python_str_FromFormat, and SwigPyPacked::ty.
Referenced by SwigPyPacked_TypeOnce().
SWIGRUNTIME PyObject* SwigPyPacked_str (SwigPyPacked * v)
References swig_type_info::name, SwigPyPacked::pack, SwigPyPacked::size, SWIG_BUFFER_SIZE, SWIG_PackDataName(), SWIG_Python_str_FromChar(), SWIG_Python_str_FromFormat, and SwigPyPacked::ty.
Referenced by SwigPyPacked_TypeOnce().
SWIGRUNTIME PyTypeObject* SwigPyPacked_type (void)
References SWIG_STATIC_POINTER, and SwigPyPacked_TypeOnce().
Referenced by SwigPyPacked_New().
SWIGRUNTIME PyTypeObject * SwigPyPacked_TypeOnce (void)
References PyObject_GenericGetAttr, SwigPyPacked_compare(), SwigPyPacked_dealloc(), SwigPyPacked_print(), SwigPyPacked_repr(), SwigPyPacked_str(), and SWIGRUNTIME.
Referenced by SwigPyPacked_Check(), and SwigPyPacked_type().
SWIGRUNTIME swig_type_info* SwigPyPacked_UnpackData (PyObject * obj, void * ptr, size_t size)
References SwigPyPacked::pack, SwigPyPacked::size, SwigPyPacked_Check(), and SwigPyPacked::ty.
Referenced by SWIG_Python_ConvertPacked().