ZNC: swigperlrun.h File Reference
swigperlrun.h File Reference
#include <string.h>
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include <patchlevel.h>
#include <could_not_find_Perl_patchlevel.h>
#include <stdlib.h>
Classes
struct swig_type_info
struct swig_cast_info
struct swig_module_info
struct swig_command_info
struct swig_constant_info
struct swig_variable_info
Defines
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGINLINE
#define SWIGUNUSED
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGEXPORT
#define SWIGSTDCALL
#define SWIG_UnknownError -1
#define SWIG_IOError -2
#define SWIG_RuntimeError -3
#define SWIG_IndexError -4
#define SWIG_TypeError -5
#define SWIG_DivisionByZero -6
#define SWIG_OverflowError -7
#define SWIG_SyntaxError -8
#define SWIG_ValueError -9
#define SWIG_SystemError -10
#define SWIG_AttributeError -11
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
#define SWIG_RUNTIME_VERSION "4"
#define SWIG_TYPE_TABLE_NAME
#define SWIGRUNTIME SWIGINTERN
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIG_BUFFER_SIZE 1024
#define SWIG_POINTER_DISOWN 0x1
#define SWIG_CAST_NEW_MEMORY 0x2
#define SWIG_POINTER_OWN 0x1
#define SWIG_OK (0)
#define SWIG_ERROR (-1)
#define SWIG_IsOK(r) (r >= 0)
#define SWIG_ArgError(r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_AddNewMask(r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_AddCast(r) (r)
#define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#define PERL_PATCHLEVEL_H_IMPLICIT
#define PERL_REVISION (5)
#define PERL_VERSION PATCHLEVEL
#define PERL_SUBVERSION SUBVERSION
#define SvIOK_UV(sv) (SvIOK(sv) && (SvUVX(sv) == SvIVX(sv)))
#define SvUOK(sv) SvIOK_UV(sv)
#define PL_sv_undef sv_undef
#define PL_na na
#define PL_errgv errgv
#define PL_sv_no sv_no
#define PL_sv_yes sv_yes
#define PL_markstack_ptr markstack_ptr
#define IVSIZE 4 /* A bold guess, but the best we can make. */
#define PTRV unsigned long
#define INT2PTR(any, d) (any)(PTRV)(d)
#define NUM2PTR(any, d) (any)(PTRV)(d)
#define PTR2IV(p) INT2PTR(IV,p)
#define PTR2UV(p) INT2PTR(UV,p)
#define PTR2NV(p) NUM2PTR(NV,p)
#define PTR2ul(p) (unsigned long)(p)
#define SvPV_nolen(x) SvPV(x,PL_na)
#define get_sv perl_get_sv
#define ERRSV get_sv("@",FALSE)
#define pTHX_
#define SWIG_PERL_OBJECT_DECL
#define SWIG_PERL_OBJECT_CALL
#define SWIG_ConvertPtr(obj, pp, type, flags) SWIG_Perl_ConvertPtr(SWIG_PERL_OBJECT_CALL obj, pp, type, flags)
#define SWIG_ConvertPtrAndOwn(obj, pp, type, flags, own) SWIG_Perl_ConvertPtrAndOwn(SWIG_PERL_OBJECT_CALL obj, pp, type, flags, own)
#define SWIG_NewPointerObj(p, type, flags) SWIG_Perl_NewPointerObj(SWIG_PERL_OBJECT_CALL p, type, flags)
#define swig_owntype int
#define SWIG_ConvertPacked(obj, p, s, type) SWIG_Perl_ConvertPacked(SWIG_PERL_OBJECT_CALL obj, p, s, type)
#define SWIG_NewPackedObj(p, s, type) SWIG_Perl_NewPackedObj(SWIG_PERL_OBJECT_CALL p, s, type)
#define SWIG_ConvertInstance(obj, pptr, type, flags) SWIG_ConvertPtr(obj, pptr, type, flags)
#define SWIG_NewInstanceObj(ptr, type, flags) SWIG_NewPointerObj(ptr, type, flags)
#define SWIG_ConvertFunctionPtr(obj, pptr, type) SWIG_ConvertPtr(obj, pptr, type, 0)
#define SWIG_NewFunctionPtrObj(ptr, type) SWIG_NewPointerObj(ptr, type, 0)
#define SWIG_ConvertMember(obj, ptr, sz, ty) SWIG_ConvertPacked(obj, ptr, sz, ty)
#define SWIG_NewMemberObj(ptr, sz, type) SWIG_NewPackedObj(ptr, sz, type)
#define SWIG_GetModule(clientdata) SWIG_Perl_GetModule(clientdata)
#define SWIG_SetModule(clientdata, pointer) SWIG_Perl_SetModule(pointer)
#define SWIG_ErrorType(code) SWIG_Perl_ErrorType(code)
#define SWIG_Error(code, msg) sv_setpvf(get_sv("@", GV_ADD), "%s %s", SWIG_ErrorType(code), msg)
#define SWIG_fail goto fail
#define SWIG_MakePtr(sv, ptr, type, flags) SWIG_Perl_MakePtr(SWIG_PERL_OBJECT_CALL sv, ptr, type, flags)
#define SWIG_MakePackedObj(sv, p, s, type) SWIG_Perl_MakePackedObj(SWIG_PERL_OBJECT_CALL sv, p, s, type)
#define SWIG_SetError(str) SWIG_Error(SWIG_RuntimeError, str)
#define SWIG_PERL_DECL_ARGS_1(arg1) (SWIG_PERL_OBJECT_DECL arg1)
#define SWIG_PERL_CALL_ARGS_1(arg1) (SWIG_PERL_OBJECT_CALL arg1)
#define SWIG_PERL_DECL_ARGS_2(arg1, arg2) (SWIG_PERL_OBJECT_DECL arg1, arg2)
#define SWIG_PERL_CALL_ARGS_2(arg1, arg2) (SWIG_PERL_OBJECT_CALL arg1, arg2)
#define SWIG_POINTER_EXCEPTION 0
#define SWIG_OWNER SWIG_POINTER_OWN
#define SWIG_SHADOW SWIG_OWNER << 1
#define SWIG_MAYBE_PERL_OBJECT SWIG_PERL_OBJECT_DECL
#define XSPROTO(name) void name(pTHX_ CV* cv)
#define SWIG_CALLXS(_name) _name(cv)
#define MAGIC_PPERL
#define SWIGCLASS_STATIC static SWIGUNUSED
#define SWIG_MAGIC(a, b) (SV *a, MAGIC *b)
#define SWIG_PERL_STRICT_STR2NUM
#define SWIG_Str2NumCast(x) SWIG_AddCast(x)
#define SWIG_croak(x) { SWIG_Error(SWIG_RuntimeError, x); SWIG_fail; }
#define SWIG_INT 1
#define SWIG_FLOAT 2
#define SWIG_STRING 3
#define SWIG_POINTER 4
#define SWIG_BINARY 5
#define swig_create_magic(s, a, b, c) _swig_create_magic(s,(char*)(a),b,c)
Typedefs
typedef void *(* swig_converter_func)(void *, int *)
typedef struct swig_type_info *(* swig_dycast_func)(void **)
typedef struct swig_type_info swig_type_info
typedef struct swig_cast_info swig_cast_info
typedef struct swig_module_info swig_module_info
typedef int(* SwigMagicFunc)(SV *, MAGIC *)
typedef SwigPerlWrapper * SwigPerlWrapperPtr
typedef struct swig_constant_info swig_constant_info
Functions
SWIGRUNTIME int SWIG_TypeNameComp (const char *f1, const char *l1, const char *f2, const char *l2)
SWIGRUNTIME int SWIG_TypeCmp (const char *nb, const char *tb)
SWIGRUNTIME int SWIG_TypeEquiv (const char *nb, const char *tb)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheck (const char *c, swig_type_info *ty)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheckStruct (swig_type_info *from, swig_type_info *ty)
SWIGRUNTIMEINLINE void * SWIG_TypeCast (swig_cast_info *ty, void *ptr, int *newmemory)
SWIGRUNTIME swig_type_info * SWIG_TypeDynamicCast (swig_type_info *ty, void **ptr)
SWIGRUNTIMEINLINE const char * SWIG_TypeName (const swig_type_info *ty)
SWIGRUNTIME const char * SWIG_TypePrettyName (const swig_type_info *type)
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME swig_type_info * SWIG_MangledTypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME swig_type_info * SWIG_TypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME char * SWIG_PackData (char *c, void *ptr, size_t sz)
SWIGRUNTIME const char * SWIG_UnpackData (const char *c, void *ptr, size_t sz)
SWIGRUNTIME char * SWIG_PackVoidPtr (char *buff, void *ptr, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackVoidPtr (const char *c, void **ptr, const char *name)
SWIGRUNTIME char * SWIG_PackDataName (char *buff, void *ptr, size_t sz, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackDataName (const char *c, void *ptr, size_t sz, const char *name)
SWIGINTERN const char * SWIG_Perl_ErrorType (int code)
SWIGRUNTIME const char * SWIG_Perl_TypeProxyName (const swig_type_info *type)
SWIGRUNTIME swig_cast_info * SWIG_TypeProxyCheck (const char *c, swig_type_info *ty)
SWIGRUNTIME int SWIG_Perl_ConvertPtrAndOwn (SWIG_MAYBE_PERL_OBJECT SV *sv, void **ptr, swig_type_info *_t, int flags, int *own)
SWIGRUNTIME int SWIG_Perl_ConvertPtr (SWIG_MAYBE_PERL_OBJECT SV *sv, void **ptr, swig_type_info *_t, int flags)
SWIGRUNTIME void SWIG_Perl_MakePtr (SWIG_MAYBE_PERL_OBJECT SV *sv, void *ptr, swig_type_info *t, int flags)
SWIGRUNTIMEINLINE SV * SWIG_Perl_NewPointerObj (SWIG_MAYBE_PERL_OBJECT void *ptr, swig_type_info *t, int flags)
SWIGRUNTIME void SWIG_Perl_MakePackedObj (SWIG_MAYBE_PERL_OBJECT SV *sv, void *ptr, int sz, swig_type_info *type)
SWIGRUNTIME SV * SWIG_Perl_NewPackedObj (SWIG_MAYBE_PERL_OBJECT void *ptr, int sz, swig_type_info *type)
SWIGRUNTIME int SWIG_Perl_ConvertPacked (SWIG_MAYBE_PERL_OBJECT SV *obj, void *ptr, int sz, swig_type_info *ty)
typedef XSPROTO (SwigPerlWrapper)
SWIGRUNTIME void _swig_create_magic (SV *sv, char *name, int(*set)(SV *, MAGIC *), int(*get)(SV *, MAGIC *))
SWIGRUNTIME swig_module_info * SWIG_Perl_GetModule (void *SWIGUNUSEDPARM(clientdata))
SWIGRUNTIME void SWIG_Perl_SetModule (swig_module_info *module)
SWIGRUNTIMEINLINE swig_type_info * SWIG_TypeQuery (const char *name)
SWIGRUNTIMEINLINE swig_type_info * SWIG_MangledTypeQuery (const char *name)
Define Documentation
#define ERRSV get_sv("@",FALSE)
#define get_sv perl_get_sv
Referenced by SWIG_Perl_GetModule(), and SWIG_Perl_SetModule().
#define INT2PTR (any, d) (any)(PTRV)(d)
Referenced by SWIG_Perl_ConvertPtrAndOwn(), and SWIG_Perl_GetModule().
#define IVSIZE 4 /* A bold guess, but the best we can make. */
#define MAGIC_PPERL
#define NUM2PTR (any, d) (any)(PTRV)(d)
#define PERL_PATCHLEVEL_H_IMPLICIT
#define PERL_REVISION (5)
#define PERL_SUBVERSION SUBVERSION
#define PERL_VERSION PATCHLEVEL
#define PL_errgv errgv
#define PL_markstack_ptr markstack_ptr
#define PL_na na
#define PL_sv_no sv_no
#define PL_sv_undef sv_undef
#define PL_sv_yes sv_yes
#define pTHX_
#define PTR2IV (p) INT2PTR(IV,p)
Referenced by SWIG_Perl_SetModule().
#define PTR2NV (p) NUM2PTR(NV,p)
#define PTR2ul (p) (unsigned long)(p)
#define PTR2UV (p) INT2PTR(UV,p)
#define PTRV unsigned long
#define SvIOK_UV (sv) (SvIOK(sv) && (SvUVX(sv) == SvIVX(sv)))
#define SvPV_nolen (x) SvPV(x,PL_na)
Referenced by SWIG_Perl_ConvertPacked().
#define SvUOK (sv) SvIOK_UV(sv)
#define SWIG_AddCast (r) (r)
#define SWIG_AddNewMask (r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_AddTmpMask (r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_ArgError (r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_AttributeError -11
Referenced by SWIG_Perl_ErrorType().
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_BINARY 5
#define SWIG_BUFFER_SIZE 1024
#define SWIG_CALLXS (_name) _name(cv)
#define SWIG_CAST_NEW_MEMORY 0x2
Referenced by SWIG_Perl_ConvertPtrAndOwn().
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_CheckState (r) (SWIG_IsOK(r) ? 1 : 0)
#define SWIG_ConvertFunctionPtr (obj, pptr, type) SWIG_ConvertPtr(obj, pptr, type, 0)
#define SWIG_ConvertInstance (obj, pptr, type, flags) SWIG_ConvertPtr(obj, pptr, type, flags)
#define SWIG_ConvertMember (obj, ptr, sz, ty) SWIG_ConvertPacked(obj, ptr, sz, ty)
#define SWIG_ConvertPacked (obj, p, s, type) SWIG_Perl_ConvertPacked(SWIG_PERL_OBJECT_CALL obj, p, s, type)
#define SWIG_ConvertPtr (obj, pp, type, flags) SWIG_Perl_ConvertPtr(SWIG_PERL_OBJECT_CALL obj, pp, type, flags)
#define SWIG_ConvertPtrAndOwn (obj, pp, type, flags, own) SWIG_Perl_ConvertPtrAndOwn(SWIG_PERL_OBJECT_CALL obj, pp, type, flags, own)
#define swig_create_magic (s, a, b, c) _swig_create_magic(s,(char*)(a),b,c)
#define SWIG_croak (x) { SWIG_Error(SWIG_RuntimeError, x); SWIG_fail; }
#define SWIG_DelNewMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_DelTmpMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_DivisionByZero -6
Referenced by SWIG_Perl_ErrorType().
#define SWIG_ERROR (-1)
Referenced by SWIG_Perl_ConvertPacked(), and SWIG_Perl_ConvertPtrAndOwn().
#define SWIG_Error (code, msg) sv_setpvf(get_sv("@", GV_ADD), "%s %s", SWIG_ErrorType(code), msg)
#define SWIG_ErrorType (code) SWIG_Perl_ErrorType(code)
#define SWIG_fail goto fail
#define SWIG_FLOAT 2
#define SWIG_GetModule (clientdata) SWIG_Perl_GetModule(clientdata)
Referenced by SWIG_MangledTypeQuery(), and SWIG_TypeQuery().
#define SWIG_IndexError -4
Referenced by SWIG_Perl_ErrorType().
#define SWIG_INT 1
#define SWIG_IOError -2
Referenced by SWIG_Perl_ErrorType().
#define SWIG_IsNewObj (r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_IsOK (r) (r >= 0)
#define SWIG_IsTmpObj (r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_MAGIC (a, b) (SV *a, MAGIC *b)
#define SWIG_MakePackedObj (sv, p, s, type) SWIG_Perl_MakePackedObj(SWIG_PERL_OBJECT_CALL sv, p, s, type)
#define SWIG_MakePtr (sv, ptr, type, flags) SWIG_Perl_MakePtr(SWIG_PERL_OBJECT_CALL sv, ptr, type, flags)
Referenced by SWIG_Perl_NewPointerObj().
#define SWIG_MAYBE_PERL_OBJECT SWIG_PERL_OBJECT_DECL
#define SWIG_MemoryError -12
Referenced by SWIG_Perl_ErrorType().
#define SWIG_NewFunctionPtrObj (ptr, type) SWIG_NewPointerObj(ptr, type, 0)
#define SWIG_NewInstanceObj (ptr, type, flags) SWIG_NewPointerObj(ptr, type, flags)
Referenced by CPyRetString::wrap(), and CPyRetBool::wrap().
#define SWIG_NewMemberObj (ptr, sz, type) SWIG_NewPackedObj(ptr, sz, type)
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_NewPackedObj (p, s, type) SWIG_Perl_NewPackedObj(SWIG_PERL_OBJECT_CALL p, s, type)
#define SWIG_NewPointerObj (p, type, flags) SWIG_Perl_NewPointerObj(SWIG_PERL_OBJECT_CALL p, type, flags)
#define SWIG_NullReferenceError -13
#define SWIG_OK (0)
Referenced by SWIG_Perl_ConvertPacked(), and SWIG_Perl_ConvertPtrAndOwn().
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_OverflowError -7
Referenced by SWIG_Perl_ErrorType().
#define SWIG_OWNER SWIG_POINTER_OWN
#define swig_owntype int
#define SWIG_PERL_CALL_ARGS_1 (arg1) (SWIG_PERL_OBJECT_CALL arg1)
#define SWIG_PERL_CALL_ARGS_2 (arg1, arg2) (SWIG_PERL_OBJECT_CALL arg1, arg2)
#define SWIG_PERL_DECL_ARGS_1 (arg1) (SWIG_PERL_OBJECT_DECL arg1)
#define SWIG_PERL_DECL_ARGS_2 (arg1, arg2) (SWIG_PERL_OBJECT_DECL arg1, arg2)
#define SWIG_PERL_OBJECT_CALL
#define SWIG_PERL_OBJECT_DECL
#define SWIG_PERL_STRICT_STR2NUM
#define SWIG_POINTER 4
#define SWIG_POINTER_DISOWN 0x1
Referenced by SWIG_Perl_ConvertPtrAndOwn().
#define SWIG_POINTER_EXCEPTION 0
#define SWIG_POINTER_OWN 0x1
Referenced by SWIG_Perl_MakePtr(), CPyRetString::wrap(), and CPyRetBool::wrap().
#define SWIG_RUNTIME_VERSION "4"
Referenced by SWIG_Perl_GetModule(), and SWIG_Perl_SetModule().
#define SWIG_RuntimeError -3
Referenced by SWIG_Perl_ErrorType().
#define SWIG_SetError (str) SWIG_Error(SWIG_RuntimeError, str)
#define SWIG_SetModule (clientdata, pointer) SWIG_Perl_SetModule(pointer)
#define SWIG_SHADOW SWIG_OWNER << 1
Referenced by SWIG_Perl_MakePtr().
#define SWIG_Str2NumCast (x) SWIG_AddCast(x)
#define SWIG_STRING 3
#define SWIG_SyntaxError -8
Referenced by SWIG_Perl_ErrorType().
#define SWIG_SystemError -10
Referenced by SWIG_Perl_ErrorType().
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_TYPE_TABLE_NAME
Referenced by SWIG_Perl_GetModule(), and SWIG_Perl_SetModule().
#define SWIG_TypeError -5
Referenced by SWIG_Perl_ErrorType().
#define SWIG_UnknownError -1
#define SWIG_ValueError -9
Referenced by SWIG_Perl_ErrorType().
#define SWIGCLASS_STATIC static SWIGUNUSED
#define SWIGEXPORT
#define SWIGINLINE
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGRUNTIME SWIGINTERN
Referenced by SWIG_Perl_ConvertPtrAndOwn().
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIGSTDCALL
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGUNUSED
#define SWIGUNUSEDPARM (p) p SWIGUNUSED
#define XSPROTO (name) void name(pTHX_ CV* cv)
Typedef Documentation
typedef struct swig_cast_info swig_cast_info
typedef struct swig_constant_info swig_constant_info
typedef void*(* swig_converter_func)(void *, int *)
typedef struct swig_type_info*(* swig_dycast_func)(void **)
typedef struct swig_module_info swig_module_info
typedef struct swig_type_info swig_type_info
typedef int(* SwigMagicFunc)(SV *, MAGIC *)
typedef SwigPerlWrapper* SwigPerlWrapperPtr
Function Documentation
SWIGRUNTIME void _swig_create_magic (SV * sv, char * name, int(*)(SV *, MAGIC *) set, int(*)(SV *, MAGIC *) get)
SWIGRUNTIMEINLINE swig_type_info* SWIG_MangledTypeQuery (const char * name)
References SWIG_GetModule, and SWIG_MangledTypeQueryModule().
SWIGRUNTIME swig_type_info* SWIG_MangledTypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
References swig_type_info::name, swig_module_info::next, swig_module_info::size, and swig_module_info::types.
Referenced by SWIG_MangledTypeQuery(), and SWIG_TypeQueryModule().
SWIGRUNTIME char* SWIG_PackData (char * c, void * ptr, size_t sz)
Referenced by SWIG_PackDataName(), SWIG_PackVoidPtr(), and SWIG_Perl_MakePackedObj().
SWIGRUNTIME char* SWIG_PackDataName (char * buff, void * ptr, size_t sz, const char * name, size_t bsz)
References SWIG_PackData().
Referenced by SwigPyPacked_print(), SwigPyPacked_repr(), and SwigPyPacked_str().
SWIGRUNTIME char* SWIG_PackVoidPtr (char * buff, void * ptr, const char * name, size_t bsz)
References SWIG_PackData().
SWIGRUNTIME int SWIG_Perl_ConvertPacked (SWIG_MAYBE_PERL_OBJECT SV * obj, void * ptr, int sz, swig_type_info * ty)
References SvPV_nolen, SWIG_ERROR, SWIG_OK, SWIG_TypeCheck(), and SWIG_UnpackData().
SWIGRUNTIME int SWIG_Perl_ConvertPtr (SWIG_MAYBE_PERL_OBJECT SV * sv, void ** ptr, swig_type_info * _t, int flags)
References SWIG_Perl_ConvertPtrAndOwn().
SWIGRUNTIME int SWIG_Perl_ConvertPtrAndOwn (SWIG_MAYBE_PERL_OBJECT SV * sv, void ** ptr, swig_type_info * _t, int flags, int * own)
References INT2PTR, SWIG_CAST_NEW_MEMORY, SWIG_ERROR, SWIG_OK, SWIG_Perl_TypeProxyName(), SWIG_POINTER_DISOWN, SWIG_TypeCast(), SWIG_TypeProxyCheck(), and SWIGRUNTIME.
Referenced by SWIG_Perl_ConvertPtr().
SWIGINTERN const char* SWIG_Perl_ErrorType (int code)
References SWIG_AttributeError, SWIG_DivisionByZero, SWIG_IndexError, SWIG_IOError, SWIG_MemoryError, SWIG_OverflowError, SWIG_RuntimeError, SWIG_SyntaxError, SWIG_SystemError, SWIG_TypeError, and SWIG_ValueError.
SWIGRUNTIME swig_module_info* SWIG_Perl_GetModule (void * SWIGUNUSEDPARMclientdata)
References get_sv, INT2PTR, SWIG_RUNTIME_VERSION, and SWIG_TYPE_TABLE_NAME.
SWIGRUNTIME void SWIG_Perl_MakePackedObj (SWIG_MAYBE_PERL_OBJECT SV * sv, void * ptr, int sz, swig_type_info * type)
References SWIG_PackData(), and SWIG_Perl_TypeProxyName().
Referenced by SWIG_Perl_NewPackedObj().
SWIGRUNTIME void SWIG_Perl_MakePtr (SWIG_MAYBE_PERL_OBJECT SV * sv, void * ptr, swig_type_info * t, int flags)
References SWIG_Perl_TypeProxyName(), SWIG_POINTER_OWN, and SWIG_SHADOW.
SWIGRUNTIME SV* SWIG_Perl_NewPackedObj (SWIG_MAYBE_PERL_OBJECT void * ptr, int sz, swig_type_info * type)
References SWIG_Perl_MakePackedObj().
SWIGRUNTIMEINLINE SV* SWIG_Perl_NewPointerObj (SWIG_MAYBE_PERL_OBJECT void * ptr, swig_type_info * t, int flags)
References SWIG_MakePtr.
SWIGRUNTIME void SWIG_Perl_SetModule (swig_module_info * module)
References get_sv, PTR2IV, SWIG_RUNTIME_VERSION, and SWIG_TYPE_TABLE_NAME.
SWIGRUNTIME const char* SWIG_Perl_TypeProxyName (const swig_type_info * type)
References swig_type_info::clientdata, and swig_type_info::name.
Referenced by SWIG_Perl_ConvertPtrAndOwn(), SWIG_Perl_MakePackedObj(), SWIG_Perl_MakePtr(), and SWIG_TypeProxyCheck().
SWIGRUNTIMEINLINE void* SWIG_TypeCast (swig_cast_info * ty, void * ptr, int * newmemory)
References swig_cast_info::converter.
Referenced by SWIG_Perl_ConvertPtrAndOwn(), SWIG_Python_ConvertFunctionPtr(), and SWIG_Python_ConvertPtrAndOwn().
SWIGRUNTIME swig_cast_info* SWIG_TypeCheck (const char * c, swig_type_info * ty)
References swig_type_info::cast, swig_type_info::name, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
Referenced by SWIG_Perl_ConvertPacked(), SWIG_Python_ConvertFunctionPtr(), SWIG_Python_ConvertPacked(), and SWIG_Python_ConvertPtrAndOwn().
SWIGRUNTIME swig_cast_info* SWIG_TypeCheckStruct (swig_type_info * from, swig_type_info * ty)
References swig_type_info::cast, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info * ti, void * clientdata)
References swig_type_info::cast, swig_type_info::clientdata, swig_module_info::clientdata, swig_cast_info::converter, swig_cast_info::next, and swig_cast_info::type.
Referenced by SWIG_TypeClientData(), and SWIG_TypeNewClientData().
SWIGRUNTIME int SWIG_TypeCmp (const char * nb, const char * tb)
References SWIG_TypeNameComp().
Referenced by SWIG_TypeEquiv().
SWIGRUNTIME swig_type_info* SWIG_TypeDynamicCast (swig_type_info * ty, void ** ptr)
References swig_type_info::dcast.
SWIGRUNTIME int SWIG_TypeEquiv (const char * nb, const char * tb)
References SWIG_TypeCmp().
Referenced by SWIG_TypeQueryModule().
SWIGRUNTIMEINLINE const char* SWIG_TypeName (const swig_type_info * ty)
References swig_type_info::name.
SWIGRUNTIME int SWIG_TypeNameComp (const char * f1, const char * l1, const char * f2, const char * l2)
Referenced by SWIG_TypeCmp().
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info * ti, void * clientdata)
References swig_type_info::owndata, and SWIG_TypeClientData().
SWIGRUNTIME const char* SWIG_TypePrettyName (const swig_type_info * type)
References swig_type_info::name, and swig_type_info::str.
Referenced by SWIG_Python_MustGetPtr(), SwigPyObject_dealloc(), and SwigPyObject_repr().
SWIGRUNTIME swig_cast_info* SWIG_TypeProxyCheck (const char * c, swig_type_info * ty)
References swig_type_info::cast, swig_cast_info::next, swig_cast_info::prev, SWIG_Perl_TypeProxyName(), and swig_cast_info::type.
Referenced by SWIG_Perl_ConvertPtrAndOwn().
SWIGRUNTIMEINLINE swig_type_info* SWIG_TypeQuery (const char * name)
References SWIG_GetModule, and SWIG_TypeQueryModule().
Referenced by CPyRetString::wrap(), and CPyRetBool::wrap().
SWIGRUNTIME swig_type_info* SWIG_TypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
References swig_module_info::next, swig_module_info::size, swig_type_info::str, SWIG_MangledTypeQueryModule(), SWIG_TypeEquiv(), and swig_module_info::types.
Referenced by SWIG_Python_TypeQuery(), and SWIG_TypeQuery().
SWIGRUNTIME const char* SWIG_UnpackData (const char * c, void * ptr, size_t sz)
Referenced by SWIG_Perl_ConvertPacked(), SWIG_UnpackDataName(), and SWIG_UnpackVoidPtr().
SWIGRUNTIME const char* SWIG_UnpackDataName (const char * c, void * ptr, size_t sz, const char * name)
References SWIG_UnpackData().
SWIGRUNTIME const char* SWIG_UnpackVoidPtr (const char * c, void ** ptr, const char * name)
References SWIG_UnpackData().
Referenced by SWIG_Python_ConvertFunctionPtr().
typedef XSPROTO (SwigPerlWrapper)