ZNC: Utils.h File Reference
Utils.h File Reference
#include <znc/zncconfig.h>
#include <znc/ZNCString.h>
#include <assert.h>
#include <cstdio>
#include <fcntl.h>
#include <map>
#include <sys/file.h>
#include <sys/time.h>
#include <unistd.h>
#include <vector>
#include <openssl/aes.h>
#include <openssl/blowfish.h>
#include <openssl/md5.h>
Classes
class CUtils
class CException
class CTable
Generate a grid-like output from a given input.
class CBlowfish
does Blowfish w/64 bit feedback, no padding
class TCacheMap< K, V >
Insert an object with a time-to-live and check later if it still exists.
class CSmartPtr< T >
This is a standard reference counting pointer. Be careful not to have two of these point to the same raw pointer or one will be deleted while the other still thinks it is valid.
Functions
template<typename T >
bool operator== (T *lhs, const CSmartPtr< T > &rhs)
template<typename T >
bool operator== (const CSmartPtr< T > &lhs, T *rhs)
template<typename T >
bool operator== (const CSmartPtr< T > &lhs, const CSmartPtr< T > &rhs)
Function Documentation
template<typename T > bool operator== (T * lhs, const CSmartPtr< T > & rhs)
References CSmartPtr< T >::GetPtr().
template<typename T > bool operator== (const CSmartPtr< T > & lhs, T * rhs)
References CSmartPtr< T >::GetPtr().
template<typename T > bool operator== (const CSmartPtr< T > & lhs, const CSmartPtr< T > & rhs)
References CSmartPtr< T >::GetPtr().